### ISSUE TITLE
关于MVP部署包中“新增节点”功能

### ISSUE THREAD

**Issue by mtl802** [secretflow/kuscia#113]
当我在服务端搭建环境之后，新增了一个物理隔离的新节点。
节点注册界面显示所有节点状态是可用的。
当我选择用新增的节点添加”合作节点“alice后显示通讯状态不可用
alice和bob的节点可以通讯，alice和新增节点无法通讯

**Comment by UniqueMarvin** [comment]
需要确认新增节点与alice节点之间能够互相访问，两边的通信地址要能够互相 telnet 通

**Comment by mtl802** [comment]
我新增的节点使用的是wsl centos，启用了wsl2中docker内部网络的端口转发功能。我用本地机新增的节点容器telnet 服务器的28080端口显示正常，使用服务器的alice容器telnet本地机ip的30002端口也是正常，但是节点的通讯状态仍是不可用

**Comment by mtl802** [comment]
你好，我现在新增了另一台centos的节点，telnet的端口应该是什么，是配置的时候-p 30002，还是映射的1080。我现在用alice容器telnet的是配置参数的30002可以连接，但是节点的通信状态仍然不可用

**Comment by UniqueMarvin** [comment]
你好，可以画个网络拓扑图描述一下组网么

**Comment by mtl802** [comment]
你好，我现在已经配置完成，确实是需要使用-p的参数端口。需要第一次配置的时候就需要信息的正确。
现在没办法直接修改节点信息，需要删除之后再添加。
并且需要在两方都删除，不然两方信息不同步，会导致无法通信

**Comment by longshan-ant** [comment]
> 

是的，如果是多机部署，端口的确是一开始部署的时候就暴露出来，我们优化一下文档，强调一下端口暴露的事情

**Comment by mtl802** [comment]
> > 
> 
> 是的，如果是多机部署，端口的确是一开始部署的时候就暴露出来，我们优化一下文档，强调一下端口暴露的事情

你好，目前还有一个问题。
就是我在alice节点中添加的test合作节点是可以通讯的。
系统自动在test节点中添加的alice合作节点是无法通讯的。
这是怎么回事

**Comment by UniqueMarvin** [comment]
> > > 
> > 
> > 
> > 是的，如果是多机部署，端口的确是一开始部署的时候就暴露出来，我们优化一下文档，强调一下端口暴露的事情
> 
> 你好，目前还有一个问题。 就是我在alice节点中添加的test合作节点是可以通讯的。 系统自动在test节点中添加的alice合作节点是无法通讯的。 这是怎么回事

你好，根据你的描述 alice 节点侧 看到的test合作节点是通的， 证明 test访问alice方向 （test --> alice） 是通的，  但 alice --> test 方向不通，可以检查下在alice 物理机上是否能够 telnet通 test节点的地址 。

**Comment by mtl802** [comment]
> > 
> 
> 是的，如果是多机部署，端口的确是一开始部署的时候就暴露出来，我们优化一下文档，强调一下端口暴露的事情

我发现了，原来是自动添加的节点目标地址是127.0.0.1，但是由于是物理隔离的原因，所以必须使用 IP地址 才可以。
麻烦了
