### ISSUE TITLE
怎么通过脚本部署lite节点？

### ISSUE THREAD

**Issue by portalll** [secretflow/kuscia#114]
![1694509312070](https://github.com/secretflow/kuscia/assets/43346110/9d7b0b76-7803-4392-80d0-583003124f1d)
文档只给了样例节点bob和alice的部署，想了解在实际生产环境部署中心化机器的时候，怎么在服务器新增节点？不使用MVP部署包，想只通过镜像和脚本来部署。

**Comment by longshan-ant** [comment]
目前我们针对的是虚机来部署节点，所以还是把所有的内容都放在了脚本中；
我们后续仍然会持续优化部署这块，会设计kuscia command体系，把相关的部署命令从脚本中拆分出来，方便按照自己的需求来部署； 目前如果要从镜像部署可能需要您这边看一下[deploy.sh](https://github.com/secretflow/kuscia/blob/main/scripts/deploy/deploy.sh) 人肉拆分一下相关的工作。
