### ISSUE TITLE
多任务执行方式

### ISSUE THREAD

**Issue by zhangning2222** [secretflow/kuscia#119]
请问执行多个任务时，目前的执行流程是多任务可以同时执行吗，还是多任务串行排队执行呢

**Comment by yushiqie** [comment]
如果任务之间没有依赖关系，可以多任务并发执行， 创建有并发度设置[max_parallelism](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/apis/kusciajob_cn#create-job)

**Comment by zhangning2222** [comment]
好的 我试一下
