### ISSUE TITLE
训练图节点路由不可用 

### ISSUE THREAD

**Issue by lllabmaster** [secretflow/kuscia#120]
1. 根据 https://www.secretflow.org.cn/docs/quickstart/fn9h9yqoievouz2a 完成了平台部署、节点注册、数据注册；
2. 创建了“联合圈人模版”任务；
3. alice节点：部署手册上自动生成的节点，IP地址为 xx.xx.xx.137
4. 138_node1节点：自主注册的节点，节点状态正常，IP地址为 xx.xx.xx.138，是同一内网，网络通的；
5. 两个节点的数据集授权正常，运行任务，报错：“**训练图节点路由不可用: 138_node1->alice**”

**Comment by lllabmaster** [comment]
> 138_node1 <-> alice 之间的合作节点授权做了吗

感谢回复提醒，我尝试做了合作节点授权，端口号是自定义的，不过



合作节点 | 合作节点通讯地址 | 本方通讯地址 | 发起合作节点 | 通讯状态 | 合作时间 | 编辑时间 | 操作
-- | -- | -- | -- | -- | -- | -- | --
138_node1jnjnuryk | XX.XX.XX.138:10801 | XX.XX.XX.137:28081 | alice |  **不可用** | 2023-09-26 16:59:44 | 2023-09-26 16:59:44

**Comment by yushiqie** [comment]
后台 docker 一下 看下安装的节点端口呢

**Comment by yushiqie** [comment]
1. alice/138_node1 是部署在一台主机，还是不同主机。
2. XX.XX.XX.138 XX.XX.XX.137 如果是容器ip地址，需要配置XX.XX.XX.138:1080  XX.XX.XX.137:1080
3. XX.XX.XX.138 XX.XX.XX.137 是主机ip地址， docker ps看下当初部署的主机端口是多少，alice默认应该是28080
