### ISSUE TITLE
k8s部署

### ISSUE THREAD

**Issue by zhangning2222** [secretflow/kuscia#121]
在使用k8s适配时，报错，可以帮忙看下吗

2023-09-26 16:39:12.617 INFO queue/queue.go:104 Start processing item: queue id[domain-controller], key[alice]
2023-09-26 16:39:12.617 INFO domain/namespace.go:72 Update domain namespace alice
2023-09-26 16:39:12.617 INFO queue/queue.go:125 Finish processing item: queue id[domain-controller], key[alice] (38.529µs)
W0926 16:39:19.295517     856 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:psi:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E0926 16:39:19.295557     856 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:psi:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
W0926 16:39:58.223146     856 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:psi:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E0926 16:39:58.223186     856 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:psi:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
W0926 16:40:39.935763     856 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:psi:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"
E0926 16:40:39.935821     856 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.6/tools/cache/reflector.go:169: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:psi:default" cannot list resource "configmaps" in API group "" in the namespace "kube-system"

**Comment by longshan-ant** [comment]
你好，能再详细描述一下你的问题吗？
这个错误是把kuscia部署到K8s上？还是把Kuscia自带的K3s改成K8s？

**Comment by zhangning2222** [comment]
是把kuscia部署到K8s上

**Comment by longshan-ant** [comment]
因为我们还没正式出K8s的部署文档，能方便把你现在的部署yaml贴出来吗？ 我们看一下

**Comment by zhangning2222** [comment]
目前已经解决了这个部署问题，现在有个新问题是任务执行失败
![image](https://github.com/secretflow/kuscia/assets/51704769/4b4bd16a-7128-48be-8e33-025acbc11882)

**Comment by longshan-ant** [comment]
如果任务调度成功，从kuscia自身的日志可能并不一定会看出来错误的原因，从上面的日志来看，也是正常的。
任务失败可以参考这个文档来排查，如果文档没有解决问题，可以参考文档中的一些步骤把一些命令输出或者日志贴图上来
https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/faq_cn#jon-run-failed

**Comment by zhangning2222** [comment]
按照排查方式，错误信息是这个
[root@kuscia-autonomy-alice logs]# kubectl get kt secretflow-task-20230928150221-single-psi -o yaml

apiVersion: kuscia.secretflow/v1alpha1

kind: KusciaTask

metadata:

  creationTimestamp: "2023-09-28T07:02:22Z"

  generation: 1

  labels:

    kuscia.secretflow/controller: kuscia-job

    kuscia.secretflow/interconn-protocol-type: kuscia

    kuscia.secretflow/job-id: secretflow-task-20230928150221

    kuscia.secretflow/self-cluster-as-initiator: "true"

    kuscia.secretflow/task-alias: single-psi

  name: secretflow-task-20230928150221-single-psi

  ownerReferences:

  - apiVersion: kuscia.secretflow/v1alpha1

    blockOwnerDeletion: true

    controller: true

    kind: KusciaJob

    name: secretflow-task-20230928150221

    uid: e68e79fc-7ce8-49c0-9cc8-44165d62cb16

  resourceVersion: "146353"

  uid: 65c51ab1-9ef6-4422-aa65-e6a33f54a57e

spec:

  initiator: alice

  parties:

  - appImageRef: secretflow-image-chinaunicom

    domainID: alice

    template:

      spec: {}

  - appImageRef: secretflow-image-chinaunicom

    domainID: bob

    template:

      spec: {}

  scheduleConfig: {}

  taskInputConfig: '{"sf_datasource_config":{"bob":{"id":"default-data-source"},"alice":{"id":"default-data-source"}},"sf_cluster_desc":{"parties":["alice","bob"],"devices":[{"name":"spu","type":"spu","parties":["alice","bob"],"config":"{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"},{"name":"heu","type":"heu","parties":["alice","bob"],"config":"{\"mode\":

    \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"}]},"sf_node_eval_param":{"domain":"preprocessing","name":"psi","version":"0.0.1","attr_paths":["input/receiver_input/key","input/sender_input/key","protocol","precheck_input","bucket_size","curve_type"],"attrs":[{"ss":["id1"]},{"ss":["id2"]},{"s":"ECDH_PSI_2PC"},{"b":true},{"i64":"1048576"},{"s":"CURVE_FOURQ"}],"inputs":[{"type":"sf.table.individual","meta":{"@type":"type.googleapis.com/secretflow.component.IndividualTable","schema":{"ids":["id1"],"features":["age","education","default","balance","housing","loan","day","duration","campaign","pdays","previous","job_blue-collar","job_entrepreneur","job_housemaid","job_management","job_retired","job_self-employed","job_services","job_student","job_technician","job_unemployed","marital_divorced","marital_married","marital_single"],"id_types":["str"],"feature_types":["float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float"]},"num_lines":"-1"},"data_refs":[{"uri":"alice.csv","party":"alice","format":"csv"}]},{"type":"sf.table.individual","meta":{"@type":"type.googleapis.com/secretflow.component.Indi vidualTable","schema":{"ids":["id2"],"features":["contact_cellular","contact_telephone","contact_unknown","month_apr","month_aug","month_dec","month_feb","month_jan","month_jul","month_jun","month_mar","month_may","month_nov","month_oct","month_sep","poutcome_failure","poutcome_other","poutcome_success","poutcome_unknown"],"labels":["y"],"id_types":["str"],"feature_types":["float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float"],"label_types":["int"]},"num_lines":"-1"},"data_refs":[{"uri":"bob.csv","party":"bob","format":"csv"}]}]},"sf_output_uris":["psi-output.csv"],"sf_output_ids":["psi-output"]}'

status:

  completionTime: "2023-09-28T07:07:22Z"

  conditions:

  - lastTransitionTime: "2023-09-28T07:02:22Z"

    status: "True"

    type: ResourceCreated

  - lastTransitionTime: "2023-09-28T07:02:22Z"

    status: "True"

    type: Running

  - lastTransitionTime: "2023-09-28T07:07:22Z"

    status: "False"

    type: Success

  lastReconcileTime: "2023-09-28T07:07:22Z"

  message: The remaining number of parties 1 is less than the schedulable threshold

    2

  phase: Failed

  podStatuses:

    alice/secretflow-task-20230928150221-single-psi-0:

      createTime: "2023-09-28T07:02:22Z"

      message: '0/1 nodes are available: task resource secretflow-task-20230928150221-single-psi-e554c86d79b1

        status phase is Failed, skip scheduling the pod. preemption: 0/1 nodes are

        available: 1 No preemption victims found for incoming pod., reject the pod

        secretflow-task-20230928150221-single-psi-0 is unschedulable even after PostFilter.'

      namespace: alice

      podName: secretflow-task-20230928150221-single-psi-0

      podPhase: Failed

      reason: Unschedulable

    bob/secretflow-task-20230928150221-single-psi-0:

      createTime: "2023-09-28T07:02:22Z"

      namespace: bob

      podName: secretflow-task-20230928150221-single-psi-0

      podPhase: Failed

  reason: TaskResourceGroupPhaseFailed

  serviceStatuses:

    alice/secretflow-task-20230928150221-single-psi-0-fed:

      createTime: "2023-09-28T07:02:22Z"

      namespace: alice

      serviceName: secretflow-task-20230928150221-single-psi-0-fed

    alice/secretflow-task-20230928150221-single-psi-0-global:

      createTime: "2023-09-28T07:02:22Z"

      namespace: alice

      serviceName: secretflow-task-20230928150221-single-psi-0-global

    alice/secretflow-task-20230928150221-single-psi-0-spu:

      createTime: "2023-09-28T07:02:22Z"

      namespace: alice

      serviceName: secretflow-task-20230928150221-single-psi-0-spu

    bob/secretflow-task-20230928150221-single-psi-0-fed:

      createTime: "2023-09-28T07:02:22Z"

      namespace: bob

      serviceName: secretflow-task-20230928150221-single-psi-0-fed

    bob/secretflow-task-20230928150221-single-psi-0-global:

      createTime: "2023-09-28T07:02:22Z"

      namespace: bob

      serviceName: secretflow-task-20230928150221-single-psi-0-global

    bob/secretflow-task-20230928150221-single-psi-0-spu:

      createTime: "2023-09-28T07:02:22Z"

      namespace: bob

      serviceName: secretflow-task-20230928150221-single-psi-0-spu

  startTime: "2023-09-28T07:02:22Z"

**Comment by longshan-ant** [comment]
看起来是alice这边没有可用的机器实例， 
可以在master中执行 `kubectl get nodes`  能够看到可用的机器实例。
另外想请问一下 alice和bob是部署在K8s中还是普通的机器（虚机or物理机orECS等）上的？ 如果是K8s上的话，因为我们现在默认用的是runc的模式，部署时需要特权容器。

**Comment by zhangning2222** [comment]
是部署在k8s上的
[root@kuscia-autonomy-alice admin]# kubectl get nodes -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      node.alpha.kubernetes.io/ttl: "0"
    creationTimestamp: "2023-09-27T09:07:17Z"
    finalizers:
    - wrangler.cattle.io/node
    labels:
      beta.kubernetes.io/arch: x86_64
      beta.kubernetes.io/os: linux
      domain: alice
      kubernetes.io/apiVersion: v0.26.3
      kubernetes.io/arch: x86_64
      kubernetes.io/hostname: kuscia-autonomy-alice
      kubernetes.io/os: linux
      kubernetes.io/role: agent
      kuscia.secretflow/namespace: alice
    name: kuscia-autonomy-alice
    resourceVersion: "161257"
    uid: 1b5469fc-9dd1-4064-9f65-beec2471c47c
  spec:
    podCIDR: 10.42.0.0/24
    podCIDRs:
    - 10.42.0.0/24
    taints:
    - effect: NoSchedule
      key: kuscia.secretflow/agent
      value: v1
  status:
    addresses:
    - address: 172.57.135.134
      type: InternalIP
    allocatable:
      cpu: "96"
      memory: 201683204Ki
      pods: "500"
      storage: 437201864Ki
    capacity:
      cpu: "96"
      memory: 264044524Ki
      pods: "500"
      storage: 511750Mi
    conditions:
    - lastHeartbeatTime: "2023-09-27T09:07:17Z"
      lastTransitionTime: "2023-09-27T09:07:17Z"
      message: RouteController created a route
      reason: RouteCreated
      status: "False"
      type: NetworkUnavailable
    - lastHeartbeatTime: "2023-09-27T09:07:17Z"
      lastTransitionTime: "2023-09-27T09:07:17Z"
      message: Agent has sufficient PID available
      reason: AgentHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2023-09-28T09:20:19Z"
      lastTransitionTime: "2023-09-27T09:07:17Z"
      message: Agent is ready
      reason: AgentReady
      status: "True"
      type: Ready
    - lastHeartbeatTime: "2023-09-28T09:20:19Z"
      lastTransitionTime: "2023-09-27T09:07:17Z"
      message: Agent has sufficient memory available, total=251.8GB, available=192.2GB
      reason: AgentHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2023-09-28T09:20:19Z"
      lastTransitionTime: "2023-09-27T09:07:17Z"
      message: 'Agent has no disk pressure. @agent_volume: space=92.9GB/499.8GB(18.6%)
        inode=224.7k/262.1M(0.1%)'
      reason: AgentHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2023-09-28T09:20:19Z"
      lastTransitionTime: "2023-09-27T09:07:17Z"
      message: 'Agent has sufficient disk space available. @agent_volume: free_space=406.9GB,
        free_inode=261.9M'
      reason: AgentHasSufficientDisk
      status: "False"
      type: OutOfDisk
    daemonEndpoints:
      kubeletEndpoint:
        Port: 0
    nodeInfo:
      architecture: x86_64
      bootID: 1693930828-1695805637751692807
      containerRuntimeVersion: ""
      kernelVersion: 4.19.0-91.82.42.uelc20.x86_64
      kubeProxyVersion: ""
      kubeletVersion: 0b7ff64
      machineID: c95d05b4-3b8e-03e8-11ec-42e5156f48db
      operatingSystem: linux
      osImage: kvm://linux/anolis:8.8 (host)
      systemUUID: ""
kind: List
metadata:
  resourceVersion: ""

**Comment by zhangning2222** [comment]
在容器里创建pod失败，任务执行失败是不是和这个相关，还有日志里只显示pod不存在，其它的日志好像没办法定位问题

**Comment by zhangning2222** [comment]
var/logs/envoy/kubernetes.log 有http 401 错误
![image](https://github.com/secretflow/kuscia/assets/51704769/fbe9b14b-1075-4342-84a9-4b1b2b6a42f5)

**Comment by gshilei** [comment]
401 表示节点之间的授权有问题，检查是否把授权都创建好了。
