### ISSUE TITLE
windows bash安装mvp包无反应

### ISSUE THREAD

**Issue by waterxyj** [secretflow/kuscia#122]
1.使用windows 安装dockerdesktop设置了内存6g
2.使用cmd执行bash install.sh
3.一直闪烁无反应
![image](https://github.com/secretflow/kuscia/assets/35448106/15a63553-569d-478e-a2df-cd8c1c3bc895)

**Comment by waterxyj** [comment]
切换wsl引擎后，执行命令回车无反应
![image](https://github.com/secretflow/kuscia/assets/35448106/eb9950c0-e2e4-4dcb-9452-ac301622088d)

**Comment by longshan-ant** [comment]
应该是wsl的系统中执行 install.sh

**Comment by waterxyj** [comment]
![image](https://github.com/secretflow/kuscia/assets/35448106/a32ead1d-a592-4c81-a88a-47241d69d1b6)
现在操作是这样，提示另一个images/xxx.tar

**Comment by waterxyj** [comment]
发行版设置为ubantu可以运行

**Comment by longshan-ant** [comment]
> 发行版设置为ubantu可以运行

所以现在已经部署好了是吗？
如果是的话，你原来设置的是哪个系统？

**Comment by waterxyj** [comment]
原来没有安装unbantu，也没有更新wsl。默认是dockor-desktop-data

**Comment by waterxyj** [comment]
现在mvp平台是部署好了
