### ISSUE TITLE
关于加密问题

### ISSUE THREAD

**Issue by mtl802** [secretflow/kuscia#126]
kuscia目前使用的是什么加密方案，如何保护数据和模型的安全性和隐私性。
secretpad是一个基于Kuscia的隐私计算的web框架，他使用的又是什么加密方案。

能帮忙解答一下吗

**Comment by yushiqie** [comment]
1. 目前 kuscia 通过建立授权的方式保证节点间的通信链路的安全，授权方式由mtls,token等，其中token方式是 rsa 加密算法，具体可参考[test](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/concepts/domainroute_cn)。首先节点的数据和模型是不出域（不在节点外明文访问），如果节点间存在联合数据建模，数据和模型本身的数据安全性是由引擎算法保证
2. secretpad作为隐私计算的web框架，是为了提高隐私计算的易用性，但本身不提供加密方案。通信链路的安全由kuscia保证， 数据/模型本身的安全性由引擎算法保证。

**Comment by mtl802** [comment]
目前kuscia的算法引擎是哪一个，SPU吗

**Comment by yushiqie** [comment]
> 目前kuscia的算法引擎是哪一个，SPU吗

是的，目前接入到kuscia 叫 secretflow 引擎，底层是用的 SPU。

**Comment by mtl802** [comment]
> > 目前kuscia的算法引擎是哪一个，SPU吗
> 
> 是的，目前接入到kuscia 叫 secretflow 引擎，底层是用的 SPU。

好的，谢谢解答
