### ISSUE TITLE
扩展 Kuscia 注册自定义算法镜像脚本功能

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#135]
> > 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第三期](https://github.com/orgs/secretflow/discussions/1007)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～
**任务介绍**
- 任务名称：扩展 Kuscia 注册自定义算法镜像脚本功能
- 技术方向：Kuscia/脚本开发
- 任务难度：热身🌟  

**详细要求**
- 需求：
   - 新增flag，可以指定容器名称，支持多参数。默认可选，若不填写，则使用以alice和bob为后缀的默认名称
   - 优化脚本，即可以并发的方式导入AppImage Docker镜像，提高镜像导入速度
- 参考文档：

      [https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/register_custom_image](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/register_custom_image)
- 参考代码：

[https://github.com/secretflow/kuscia/blob/main/scripts/tools/register_app_image/register_app_image.sh](https://github.com/secretflow/kuscia/blob/main/scripts/tools/register_app_image/register_app_image.sh)
- 提交说明：
   - 完成开发后，关联该 ISSUE 并提交代码和修改文档

**能力要求**
- 了解基本 git 操作
- 对 Kuscia 原理有一定了解
- 熟悉 shell

**操作说明**
- Kuscia 开发参考：[https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by imwangyt** [comment]
imwangyt + Give it to me

**Comment by imwangyt** [comment]
@gshilei 请教一下：

**Comment by gshilei** [comment]
> @gshilei 老师，请教一下： 需求一：新增flag，可以指定容器名称，支持多参数。默认可选，若不填写，则使用以alice和bob为后缀的默认名称 1.1、这里的多参数，是指-d alice -d bob么？还是-d alice,bob也可以？ 1.2、容器名称是否可以改为domain ids，个人觉得目前基本都是用脚本部署的，即使不是，约定按照{USER}-kuscia-lite/autonomy-{DOMAIN}的格式命名容器，似乎也比较好一点？ 需求二：优化脚本，即可以并发的方式导入AppImage Docker镜像，提高镜像导入速度 2.1、除了[secretflow#988](https://github.com/secretflow/secretflow/issues/988)提到的进程并发方式，有没有其他方式，比如直接操控containerd的镜像存储，是否可行？

@imwangyt  感谢认领。
需求一：新增flag，可以指定容器名称，支持多参数。默认可选，若不填写，则使用以alice和bob为后缀的默认名称
1.1  多参数可以采用 -d domainID-1, domainID-2 这种形式
1.2 容器名称可以按照当前的约定格式 {USER}-kuscia-lite/autonomy-{DOMAIN} 进行拼写。即通过 -d {domain1, domain2} -u {user} -m {deplyMode} 参数可组装前面的容器名称containerd的镜像存储。

2.1 这里的并发不限于直接操控containerd的镜像存储。 即使采用并发，最后的并发度可能也有瓶颈，再增大的话，实际镜像导入的速度也提升不了多大。

**Comment by imwangyt** [comment]
验证环境：WSL2
