### ISSUE TITLE
Kuscia 节点转发支持增加 UrlPathPrefix

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#137]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第三期](https://github.com/orgs/secretflow/discussions/1007)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- 任务名称：Kuscia 节点转发支持增加 UrlPathPrefix
- 技术方向：Kuscia/节点路由
- 任务难度：进阶🌟🌟

## 详细要求

- 需求描述：机构B部署了两个Lite节点Bob、Carol，机构B对外只提供一个域名，这个域名映射到机构自行部署的Nginx网关的端口，Nginx网关上配置了转发规则，即根据URIPath的前缀将请求分别路由Bob、Carol节点。机构A部署一个Lite节点Alice，对Alice而言，Bob和Carol的网关地址都是机构B的网关地址，在发送请求给节点Bob的时候，给ULRPATH加上/bob/前缀；给Carol发请求的时候，给ULRPATH加上/Carol/前缀。
- 功能性
  - DomainRouteSpec 增加 PathPrefix 字段
  - Lite侧DomainRouteController识别到PathPrefix字段后，将Source节点访问Destination节点的VirtualHost.Routes[i].Action.Route.PrefixRewrite修改为DomainRouteSpec.PathPrefix
- 提交说明：关联该 ISSUE 并提交代码至 https://github.com/secretflow/kuscia/blob/main/pkg/crd/apis/kuscia/v1alpha1/domainroute_types.go 和     https://github.com/secretflow/kuscia/blob/main/pkg/gateway/controller/interconn/kuscia_handler.go 。
- 代码规范：https://github.com/uber-go/guide/blob/master/style.md

## 能力要求
- 了解基本 git 操作
- 对 Kuscia 有一定了解
- 了解 K8S 、Envoy
- 熟悉 Golang

## 操作说明
- 请构造需求所述的网络拓扑，部署节点Alice、Bob和Carol、以及机构B的Nginx网关，将测试结果的截图贴在 ISSUE 下。截图中应有Alice发送给Bob的请求在Alice的Envoy→机构B的Nginx网关→Bob的Envoy的日志，以及Alice与Bob、Alice与Carol的任务执行成功的状态。
-  补充用户使用教程。
- Kuscia 开发参考：https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn

**Comment by chaogaofeng** [comment]
【23396178 + Give it to me】

**Comment by Candicepan** [comment]
> 【23396178 + Give it to me】

hello～您貌似还没有报名哈 记得报个名呀 https://www.wjx.top/vm/QKio0dq.aspx

**Comment by chaogaofeng** [comment]
可能之前是使用昵称chaogaofeng报名的吧
