### ISSUE TITLE
windows10 mvp部署问题

### ISSUE THREAD

**Issue by jieyugithub** [secretflow/kuscia#142]
![image](https://github.com/secretflow/kuscia/assets/11512980/7bd1eb0e-df87-4ef7-9489-e700a0233b91)

报错：cp: cannot stat 'D:/Program Files/Git/home/kuscia/scripts/deploy/start_standalon
e.sh': No such file or directory

在电脑里确实没找到这个文件，甚至Git下都没这个目录

**Comment by UniqueMarvin** [comment]
> ![image](https://user-images.githubusercontent.com/11512980/281597488-7bd1eb0e-df87-4ef7-9489-e700a0233b91.png)
> 
> 报错：cp: cannot stat 'D:/Program Files/Git/home/kuscia/scripts/deploy/start_standalon e.sh': No such file or directory
> 
> 在电脑里确实没找到这个文件，甚至Git下都没这个目录

hi， @jieyugithub  
看着像是脚本中的 docker run 执行失败了。
windows os 安装时，要使用WSL2，帮忙确认下环境信息。
https://www.secretflow.org.cn/docs/quickstart/zgnd8oqo5chsqhzm

<img width="1174" alt="image" src="https://github.com/secretflow/kuscia/assets/22186553/bbcc20eb-bd28-45d4-9593-8ff274d347e7">

**Comment by Sebastian-CQ** [comment]
我也是这个问题，请问解决了吗？我的docker desktop是windows安装的，同时也是wsl2

**Comment by xiushuiguande** [comment]
1、请用window cmd 来运行 git bash默认采用的终端是mintty 会有路径冲突问题
2、win  wsl2 bash 执行 error 参考 https://github.com/microsoft/WSL/issues/5923
