### ISSUE TITLE
根据教程点对点部署添加证书就i报错

### ISSUE THREAD

**Issue by zhengyang16** [secretflow/kuscia#150]
创建好alice和bob的容器后：
1、准备 alice 的公钥，在 alice 节点的机器上，可以看到包含公钥的 crt 文件：
2、将 alice 的公钥拷贝到 bob 的机器上的 ${PWD}/kuscia-autonomy-bob-certs 目录中并重命名为 alice.domain.crt：
3、在 bob 里添加 alice 的证书等信息
就报错了
![image](https://github.com/secretflow/kuscia/assets/51041934/81351a2f-3842-466d-8a8d-ec75f6cadaf2)

**Comment by zhengyang16** [comment]
我是在同一台机器上部署点对点kuscia，执行完这些步骤就出现了上述报错
![image](https://github.com/secretflow/kuscia/assets/51041934/2a3e9a23-5ee5-4aca-9056-85ff5d582920)

**Comment by yushiqie** [comment]
这个不影响功能使用，我们会优化一下更新资源策略。可以具体看看p2p部署的节点是否能正常的下发任务

**Comment by zhengyang16** [comment]
任务执行结果是Failed
<img width="457" alt="image" src="https://github.com/secretflow/kuscia/assets/51041934/43d624b1-f625-40d7-988f-c168ad412766">
这是docker的部分日志
<img width="684" alt="image" src="https://github.com/secretflow/kuscia/assets/51041934/cd788eb9-ec45-4318-9830-85caf9e3ba1f">
这是我在同一台机器上按照教程的完整部署命令
<img width="629" alt="1699847863600" src="https://github.com/secretflow/kuscia/assets/51041934/5ab9e1a0-3900-4316-a062-7d5d9c63b3a9">

**Comment by yushiqie** [comment]
请根据 [配置授权](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/deploy_p2p_cn#id3 ) 示例文档进行排查，初步看是授权错了

**Comment by zhengyang16** [comment]
是根据这个示例文档进行部署以及排查的，这个文档有一个问题
![image](https://github.com/secretflow/kuscia/assets/51041934/fabf73f7-05b1-4152-9d71-f3e66e48dff1)
建立通信使用了8082端口，而8082端口应该是  KusciaAPI 映射到主机的 HTTP 端口，此处是否有问题

**Comment by yushiqie** [comment]
上面是示例文档，应该是你部署的bob主机映射端口，28081

**Comment by yushiqie** [comment]
嗯嗯，示例文档我们再改一下，这边是写错了

**Comment by zhengyang16** [comment]
如果端口配置没问题的话，其他步骤都是按照示例文档：将crt文件从docker中复制出来并放入对应的certs目录中并重命名为xxx.domain.crt，然后添加证书信息再建立通信
这样子如果是授权错了我应该怎么排查呢~

**Comment by zhengyang16** [comment]
如果端口配置没问题的话，其他步骤都是按照示例文档：将crt文件从docker中复制出来并放入对应的certs目录中并重命名为xxx.domain.crt，然后添加证书信息再建立通信
这样子如果是授权错了我应该怎么排查呢~

**Comment by zhengyang16** [comment]
![image](https://github.com/secretflow/kuscia/assets/51041934/6f596765-1d0f-48ee-a10f-1f194b6b374d)
这个是按照示例文档步骤进行部署的全过程，可以麻烦帮忙看一下是哪一步出问题了吗~

**Comment by yushiqie** [comment]
![Screen Shot 2023-11-13 at 15 21 08](https://github.com/secretflow/kuscia/assets/21165026/ef599442-fabc-485b-b283-b5a68b41d5c5)

autonomy 节点授权端口默认是 https，

**Comment by zhengyang16** [comment]
好的，我尝试一下

**Comment by zhengyang16** [comment]
按照最新的教程也是不行，任务failed
![image](https://github.com/secretflow/kuscia/assets/51041934/575238cd-0e83-403d-a0c9-c5d339417220)

**Comment by longshan-ant** [comment]
你首先确认一下授权状态是否正确：
kubectl get cdr

**Comment by zhengyang16** [comment]
alice和bob的授权状态：
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by zhengyang16** [comment]
alice和bob的授权状态：
![image](https://github.com/secretflow/kuscia/assets/51041934/0bd47163-6782-4c11-a24c-bd36b413e253)
![image](https://github.com/secretflow/kuscia/assets/51041934/14c06bf3-631a-4f92-8b06-2b6c5026c6ff)

**Comment by longshan-ant** [comment]
看起来网络授权是正常的，那么可以看看任务的日志了，参考这个文档 [日志说明](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/logdescription)

看一下任务的日志
![image](https://github.com/secretflow/kuscia/assets/72000290/2e66f314-a5ad-441c-b9d8-4349c641c15a)

**Comment by zhengyang16** [comment]
/home/kuscia/var/stdout/pods目录下是空的
![image](https://github.com/secretflow/kuscia/assets/51041934/cf40fd68-9651-4e44-8260-b092462c959a)

**Comment by longshan-ant** [comment]
你看一下这个目录下的日志文件，找到对应的任务ID， 比如 secretflow-task- 开头

**Comment by zhengyang16** [comment]
两方的/home/kuscia/var/stdout/pods目录下都是空的
![image](https://github.com/secretflow/kuscia/assets/51041934/07bc1e8f-8ec0-49b8-925a-963d311caf3b)
![image](https://github.com/secretflow/kuscia/assets/51041934/e8c8499c-3784-4498-943f-e0971779b5cc)

**Comment by longshan-ant** [comment]
那看起来是任务还没有被调度起来， 可以尝试这两个命令：
kubectl get kt 
然后查看某个具体的task； kubectl describe kt xxxxx

**Comment by zhengyang16** [comment]
kubectl describe kt的部分输出结果：
![image](https://github.com/secretflow/kuscia/assets/51041934/75792fdf-c306-45f3-a2aa-bbf2a65523da)

**Comment by cho-chem** [comment]
Hi @zhengyang16 ，可以在 alice 和 bob 节点内都执行下 `kubectl get node -o yaml` 吗

**Comment by zhengyang16** [comment]
alice：
![1699945200736](https://github.com/secretflow/kuscia/assets/51041934/db97210d-a01e-40e8-aaa6-211688a944fa)
bob：
![image](https://github.com/secretflow/kuscia/assets/51041934/f6b88268-c133-471b-a41c-15e19da2acbd)

**Comment by gshilei** [comment]
> 按照最新的教程也是不行，任务failed ![image](https://user-images.githubusercontent.com/51041934/282428821-575238cd-0e83-403d-a0c9-c5d339417220.png)

能贴一下bob中的这一块相关日志？

**Comment by zhengyang16** [comment]
这是bob中这一块相关的日志
![image](https://github.com/secretflow/kuscia/assets/51041934/529b47ed-18ca-4341-ad5c-dbaabfba9283)

**Comment by gshilei** [comment]
> 这是bob中这一块相关的日志 ![image](https://user-images.githubusercontent.com/51041934/282697328-529b47ed-18ca-4341-ad5c-dbaabfba9283.png)

alice容器下发任务，会在alice容器中bob namespace下创建任务pod, 这个pod会同步到bob容器中的bob的namespace下。可以在bob容器的日志中，搜索下该pod相关的信息，pod名称如下
![image](https://github.com/secretflow/kuscia/assets/136570416/53ecdc01-57ef-40b1-9261-8d84e4343105)

**Comment by zhengyang16** [comment]
bob容器没有pod相关信息
![image](https://github.com/secretflow/kuscia/assets/51041934/b1e243f7-efe5-4be3-a689-d8e159e7fe07)
bob容器中kubectl get interop -n bob -o yaml 
![image](https://github.com/secretflow/kuscia/assets/51041934/848aca8c-8856-46cf-9491-f21067cca787)

**Comment by zhengyang16** [comment]
这是bob的容器信息
![image](https://github.com/secretflow/kuscia/assets/51041934/56fb99e6-c3ff-4f72-b2d3-4d14005705f2)

**Comment by gshilei** [comment]
> 这是bob的容器信息 ![image](https://user-images.githubusercontent.com/51041934/282701182-56fb99e6-c3ff-4f72-b2d3-4d14005705f2.png)

试一下下面操作，运行完之后，再kubectl get interop -n bob -o yaml 贴一下结果

本地新建文件bob-2-alice.yaml
```
cat bob-2-alice.yaml
apiVersion: kuscia.secretflow/v1alpha1
kind: InteropConfig
metadata:
  annotations:
  name: bob-2-alice
spec:
  host: alice
  members:
  - bob
```
创建在bob集群下
`kubectl apply -f bob-2-alice.yaml`

**Comment by zhengyang16** [comment]
![Uploading image.png…]()

**Comment by zhengyang16** [comment]
![image](https://github.com/secretflow/kuscia/assets/51041934/ebda9ef8-c4aa-4d8f-8680-74942ed64c29)

**Comment by gshilei** [comment]
不好意思，官方文档下面这条命令多了一个参数" ${USER}-kuscia-autonomy-bob"
`docker exec -it ${USER}-kuscia-autonomy-bob scripts/deploy/add_domain.sh alice ${USER}-kuscia-autonomy-bob p2p
`
按照下面命令，重新执行下这两个命令
```
docker exec -it ${USER}-kuscia-autonomy-bob scripts/deploy/add_domain.sh alice p2p
docker exec -it ${USER}-kuscia-autonomy-alice scripts/deploy/add_domain.sh bob p2p
```

**Comment by zhengyang16** [comment]
嗯嗯，我启动了一个新的任务终于成功了，谢谢
![image](https://github.com/secretflow/kuscia/assets/51041934/6d56d151-6c57-42fc-aa31-552b755463df)

**Comment by gshilei** [comment]
不客气。😁

**Comment by gshilei** [comment]
> 我请问一下可以部署之前版本的kuscia吗？因为我目前的开发任务是基于之前版本的，但是现在docker镜像latest以及部署文档都被更新了，我可以在哪查到历史版本号以及对应的部署脚本呢？

问一下，你的开发任务指的是基于kuscia代码做二开，还是基于kuscia之前的部署脚本，做部署优化？

**Comment by zhengyang16** [comment]
是基于kuscia代码API做二开

**Comment by gshilei** [comment]
> 是基于kuscia代码API做二开

如果是基于kuscia代码API做二开，最新的镜像应该不影响使用，接口应该都是兼容的，调整很小。

**Comment by zhengyang16** [comment]
嗯好的，那我没有问题了，谢谢

**Comment by gshilei** [comment]
刚刚看了下，Kuscia现在是有记录老镜像的信息。

在kuscia官网，可以看到kuscia镜像tag信息
https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/quickstart_cn#id6
https://hub.docker.com/r/secretflow/kuscia/tags

每个镜像对应的ChangeLog，可以参考
https://github.com/secretflow/kuscia/blob/main/CHANGELOG.md

**Comment by zhengyang16** [comment]
好的！
