### ISSUE TITLE
windows11本地部署，docker desktop启动install.sh，提示No such file or directory

### ISSUE THREAD

**Issue by Sebastian-CQ** [secretflow/kuscia#152]
![d9d7daa706d7f95b92f11b0ffaac067](https://github.com/secretflow/kuscia/assets/57433301/4f63cb57-4cd9-4777-b00c-b080fbfce3b1)
如何解决呢？我使用了wsl2，同时docker desktop内存也设置为了6G，但一直报这个错误。同时我的电脑并没有/home/kuscia这个文件夹。

**Comment by xiushuiguande** [comment]
检查一下，解压的package包，是否在当前目录。需要进入到解压包所在的实际路径安装。

**Comment by haha-zwx-ooo** [comment]
请使用window cmd 运行命令
git bash默认采用的终端是mintty 会有路径冲突问题

**Comment by xiushuiguande** [comment]
hello，问题解决了吗？
