### ISSUE TITLE
kuscia版本v0.4.0.dev231013的部署问题

### ISSUE THREAD

**Issue by zhengyang16** [secretflow/kuscia#156]
kuscia版本v0.4.0.dev231013的部署脚本是不是被修改过...
我需要基于之前没有domainDataGrant的版本进行二次开发，上周五还可以部署，今天使用同样的命令部署就报错了
![image](https://github.com/secretflow/kuscia/assets/51041934/0e06c971-f284-4bd9-b604-bdf207d2dbc0)

**Comment by Chrisdehe** [comment]
OK，我们来复现一下。

**Comment by yujun4464** [comment]
@zhengyang16 kuscia最新镜像新增了init_confmanager_cert.sh脚本，建议拉取最新镜像并且使用最新的deploy.sh脚本

**Comment by zhengyang16** [comment]
但是目前我需要使用没有domainDataGrant的版本，那目前看来历史版本没办法部署了吗？

**Comment by xiushuiguande** [comment]
看下绿色日志的第一行，虽然上边export旧版本了，但是部署的时候还是latest，是不是没有export成功？？

**Comment by xiushuiguande** [comment]
kuscia:v0.4.0.dev231013版本复现日志：
(base) [root@test01 sk]# export KUSCIA_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:v0.4.0.dev231013
(base) [root@test01 sk]# docker run --rm --pull always $KUSCIA_IMAGE cat /home/kuscia/scripts/deploy/deploy.sh > deploy.sh && chmod u+x deploy.sh
v0.4.0.dev231013: Pulling from secretflow/kuscia
Digest: sha256:ec0251f120f24a518f61999a47cf86b237547384d8358127b593c920f4d71ae9
Status: Downloaded newer image for secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:v0.4.0.dev231013
(base) [root@wangdehe01 sk]# ./deploy.sh autonomy -n alice -i 172.19.245.231 -p 28081 -k 28082 -g 28083
KUSCIA_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:v0.4.0.dev231013
SECRETFLOW_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.2.0.dev20230926
ROOT=/home/sk
DOMAIN_ID=alice
DOMAIN_HOST_IP=172.19.245.231
DOMAIN_HOST_PORT=28081
DOMAIN_DATA_DIR=/home/sk/kuscia-autonomy-alice-data
DOMAIN_CERTS_DIR=/home/sk/kuscia-autonomy-alice-certs
KUSCIA_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:v0.4.0.dev231013
KUSCIAAPI_HTTP_PORT=28082
KUSCIAAPI_GRPC_PORT=28083
x86_64 architecture. Continuing...
The container 'root-kuscia-autonomy-alice' already exists. Do you need to recreate it? [y/n]:y
Remove container root-kuscia-autonomy-alice ...
root-kuscia-autonomy-alice
Starting container root-kuscia-autonomy-alice ...
Generating RSA private key, 2048 bit long modulus (2 primes)
............................................................................................................+++++
...............................................................................................................+++++
e is 65537 (0x010001)
Signature ok
subject=CN = alice_ENVOY_EXTERNAL
Getting CA Private Key
/home/kuscia/etc/certs /home/kuscia
Generating RSA private key, 2048 bit long modulus (2 primes)
......................................................+++++
..........................+++++
e is 65537 (0x010001)
Ignoring -days; not generating a certificate
Signature ok
subject=CN = ConfManager
Getting CA Private Key
Generating RSA private key, 2048 bit long modulus (2 primes)
.............................................................................................................................+++++
..........................+++++
e is 65537 (0x010001)
Ignoring -days; not generating a certificate
Signature ok
subject=CN = KusciaAPI
Getting CA Private Key
....+++++
.........+++++
Ignoring -days; not generating a certificate
Signature ok
subject=CN = KusciaAPIClient
Getting CA Private Key
8eb628dc3605646c1f61925cf45db14f41e9b276f0a338d22e71d9f9b2a416d8
Container root-kuscia-autonomy-alice started successfully
Image 'secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.2.0.dev20230926' already exists in domain 'alice'
appimage.kuscia.secretflow/secretflow-image created
appimage.kuscia.secretflow/secretflow-nsjail-image created
Create secretflow app image done
domaindata.kuscia.secretflow/alice-table created
domaindata.kuscia.secretflow/bob-table created
Create domain data table done
Autonomy domain 'alice' deployed successfully

**Comment by xiushuiguande** [comment]
hi,尝试把旧deploy.sh文件rm掉，然后重新用231013，pull部署一下

**Comment by zhengyang16** [comment]
> hi,尝试把旧deploy.sh文件rm掉，然后重新用231013，pull部署一下

我每次都是这样子的，又试了一次还是这个状况。我之前都是sudo执行的deploy.sh使用的都是lates版本，刚刚试了一下不加sudo执行，就是使用export的版本，但是我的账号不sudo无法使用docker，这种情况应该怎么办呢？
![image](https://github.com/secretflow/kuscia/assets/51041934/46584960-688b-48cc-be74-8516715aff93)

**Comment by xiushuiguande** [comment]
hi，尝试一下
1、sudo export
2、sudo docker

**Comment by zhengyang16** [comment]
> sudo export
export不可以sudo：

sudo: export: command not found

**Comment by xiushuiguande** [comment]
![image](https://github.com/secretflow/kuscia/assets/34685731/da5d4d94-9f77-4269-9e93-3bbed2f55729)
尝试把deploy.sh文件里边这行直接改一下，试下

**Comment by zhengyang16** [comment]
成功部署了，谢谢！
