### ISSUE TITLE
secretpad 能否部署在linux系统上

### ISSUE THREAD

**Issue by fly78lv** [secretflow/kuscia#173]
secretpad 能否部署在linux系统上

**Comment by wangyixianggogo** [comment]
哈喽，我们支持Centos7、Centos8，这里是[操作步骤](https://www.secretflow.org.cn/docs/quickstart/zgnd8oqo5chsqhzm#bjWCV)，可以参考一下

**Comment by xiushuiguande** [comment]
@fly78lv 你好，官网安装步骤，在linux中执行步骤也是一样的
1、下载安装包，解压
2、./install
