### ISSUE TITLE
关于使用场景的疑问。

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/kuscia#174]
您好，在Fate的示例中，有参与方没部署Kuscia，因此需要配置镜像。那是否在所有参与方都部署Kuscia的情况下，可以直接通过配置KusciaJob调用第三方的SDK？还是说，必须要配置镜像才能运行第三方的SDK？

感谢您的帮助！

**Comment by longshan-ant** [comment]
你好，你这里的提到的配置镜像，指的是FATE的镜像还是adaptor的镜像？__

**Comment by zzx-QDU** [comment]
真是太感谢了！
