### ISSUE TITLE
kuscia镜像版本源码对应问题

### ISSUE THREAD

**Issue by sqh539** [secretflow/kuscia#180]
我在镜像内获取的 kuscia版本是: version 3b1cceb ，请问这个kuscia编译程序对应git上哪个tag的源码？

**Comment by cho-chem** [comment]
你好，你用的应该是一个 dev 镜像，dev 镜像之前并没有打 tag，镜像是基于这次 commit 构建的：https://github.com/secretflow/kuscia/tree/3b1cceb07c493a9b427287d71462077ccc1d0f19

**Comment by sqh539** [comment]
> 你好，你用的应该是一个 dev 镜像，dev 镜像之前并没有打 tag，镜像是基于这次 commit 构建的：https://github.com/secretflow/kuscia/tree/3b1cceb07c493a9b427287d71462077ccc1d0f19

好的，谢谢
