### ISSUE TITLE
执行样例求交任务时报错

### ISSUE THREAD

**Issue by sqh539** [secretflow/kuscia#183]
点对点部署后，执行scripts/user/create_example_job.sh测试时报错

podStatuses:
    alice/secretflow-task-20231206105303-single-psi-0:
      message: '0/1 nodes are available: failed to get task resource alice/ for pod.
        preemption: 0/1 nodes are available: 1 No preemption victims found for incoming
        pod., can not find related task resource.'
      namespace: alice
      podName: secretflow-task-20231206105303-single-psi-0
      podPhase: Pending
      reason: Unschedulable
    bob/secretflow-task-20231206105303-single-psi-0:
      namespace: bob
      podName: secretflow-task-20231206105303-single-psi-0
      podPhase: Pending

任务执行过程中，一直使用get nodes查看都是Ready 状态
NAME                         STATUS   ROLES   AGE   VERSION
root-kuscia-autonomy-alice   Ready    agent   82m   3b1cceb

我使用的kuscia版本是：
kuscia version 3b1cceb
secretflow版本是 v1.0.0b0 

节点信息是：
NAME                         STATUS   ROLES   AGE   VERSION
root-kuscia-autonomy-alice   Ready    agent   82m   3b1cceb
[root@root-kuscia-autonomy-alice kuscia]# kubectl describe node root-kuscia-autonomy-alice                         
Name:               root-kuscia-autonomy-alice
Roles:              agent
Labels:             beta.kubernetes.io/arch=x86_64
                    beta.kubernetes.io/os=linux
                    domain=alice
                    kubernetes.io/apiVersion=v0.26.3
                    kubernetes.io/arch=x86_64
                    kubernetes.io/hostname=root-kuscia-autonomy-alice
                    kubernetes.io/os=linux
                    kubernetes.io/role=agent
                    kuscia.secretflow/namespace=alice
Annotations:        node.alpha.kubernetes.io/ttl: 0
CreationTimestamp:  Wed, 06 Dec 2023 09:40:44 +0800
Taints:             kuscia.secretflow/agent=v1:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  root-kuscia-autonomy-alice
  AcquireTime:     <unset>
  RenewTime:       Wed, 06 Dec 2023 11:06:08 +0800
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                     Message
  ----                 ------  -----------------                 ------------------                ------                     -------
  NetworkUnavailable   False   Wed, 06 Dec 2023 09:40:44 +0800   Wed, 06 Dec 2023 09:40:44 +0800   RouteCreated               RouteController created a route
  PIDPressure          False   Wed, 06 Dec 2023 09:40:44 +0800   Wed, 06 Dec 2023 09:40:44 +0800   AgentHasSufficientPID      Agent has sufficient PID available
  Ready                True    Wed, 06 Dec 2023 11:01:14 +0800   Wed, 06 Dec 2023 09:40:44 +0800   AgentReady                 Agent is ready
  MemoryPressure       False   Wed, 06 Dec 2023 11:01:14 +0800   Wed, 06 Dec 2023 09:40:44 +0800   AgentHasSufficientMemory   Agent has sufficient memory available, total=15.4GB, available=13.6GB
  DiskPressure         False   Wed, 06 Dec 2023 11:01:14 +0800   Wed, 06 Dec 2023 09:40:44 +0800   AgentHasNoDiskPressure     Agent has no disk pressure. @agent_volume: space=305.7GB/3.6TB(8.3%) inode=1.7M/384.5M(0.5%)
  OutOfDisk            False   Wed, 06 Dec 2023 11:01:14 +0800   Wed, 06 Dec 2023 09:40:44 +0800   AgentHasSufficientDisk     Agent has sufficient disk space available. @agent_volume: free_space=3.3TB, free_inode=382.8M
Addresses:
  InternalIP:  172.19.0.2
Capacity:
  cpu:     8
  memory:  16543408128
  pods:    500
Allocatable:
  cpu:     8
  memory:  14340008Ki
  pods:    500
System Info:
  Machine ID:                 4fe99c5d-1cf7-6a11-5392-fc3497b0da3f
  System UUID:                
  Boot ID:                    1700370488-1701826844123327454
  Kernel Version:             3.10.0-1160.99.1.el7.x86_64
  OS Image:                   docker://linux/anolis:8.8 (guest)
  Operating System:           linux
  Architecture:               x86_64
  Container Runtime Version:  
  Kubelet Version:            3b1cceb
  Kube-Proxy Version:         
PodCIDR:                      10.42.0.0/24
PodCIDRs:                     10.42.0.0/24
Non-terminated Pods:          (0 in total)
  Namespace                   Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
Events:              <none>

**Comment by sqh539** [comment]
> 有没有双向配置过授权？ https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/deploy_p2p_cn#id3

授权都做过了，有没有办法让我们验证下通道？

**Comment by cho-chem** [comment]
你好，要验证授权有两种方式：
1. 在双方的节点容器中使用命令 `kubectl get dr -owide` 查看状态是否 ready
2. 在双方的节点容器内 curl 对端的 test svc：例如在 bob 容器中 curl alice：`curl test.alice.svc`，如果返回对端返回 401 说明正常

关于任务报错麻烦给下以下信息：
1. 在对端的节点容器中（例如是 bob）使用 `kubectl get node -owide` 命令查看 node 状态是否 ready
2. 在对端的节点容器中使用命令 `grep "secretflow-task-20231206105303" /home/kuscia/var/logs/kuscia.log` 贴一下输出结果

**Comment by sqh539** [comment]
1、 
[root@root-kuscia-autonomy-alice kuscia]# kubectl get dr --all-namespaces  -owide
NAMESPACE   NAME        SOURCE   DESTINATION   HOST                         AUTHENTICATION
alice       alice-bob   alice    bob           192.168.0.163                MTLS
alice       bob-alice   bob      alice         root-kuscia-autonomy-alice   MTLS

[root@root-kuscia-autonomy-bob kuscia]# kubectl get dr --all-namespaces  -owide
NAMESPACE   NAME        SOURCE   DESTINATION   HOST                       AUTHENTICATION
bob         alice-bob   alice    bob           root-kuscia-autonomy-bob   MTLS
bob         bob-alice   bob      alice         192.168.0.98               MTLS

2、
[root@root-kuscia-autonomy-alice kuscia]#  curl test.bob.svc
upstream connect error or disconnect/reset before headers. reset reason: connection failure
[root@root-kuscia-autonomy-bob kuscia]# curl test.alice.svc
upstream connect error or disconnect/reset before headers. reset reason: connection failure

3、
[root@root-kuscia-autonomy-alice kuscia]# kubectl get node -owide
NAME                         STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                            KERNEL-VERSION                CONTAINER-RUNTIME
root-kuscia-autonomy-alice   Ready    agent   48m   3b1cceb   172.18.0.2    <none>        docker://linux/anolis:8.8 (guest)   3.10.0-1160.99.1.el7.x86_64   <unknown>

[root@root-kuscia-autonomy-bob kuscia]# kubectl get node -owide
NAME                       STATUS   ROLES   AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                            KERNEL-VERSION                CONTAINER-RUNTIME
root-kuscia-autonomy-bob   Ready    agent   47m   3b1cceb   172.18.0.2    <none>        docker://linux/anolis:8.8 (guest)   3.10.0-1160.99.1.el7.x86_64   <unknown>

4、日志输出到文件中
[task_log.log](https://github.com/secretflow/kuscia/files/13577468/task_log.log)

**Comment by cho-chem** [comment]
从2中可以看到，当前节点之间的网络是不通的。
1. 首先确认下 root-kuscia-autonomy-bob ， 192.168.0.98 这两个地址是互通的
2. 加上 -v 参数，输出详细信息：`curl -v test.bob.svc`

**Comment by sqh539** [comment]
> 从2中可以看到，当前节点之间的网络是不通的。
> 
> 1. 首先确认下 root-kuscia-autonomy-bob ， 192.168.0.98 这两个地址是互通的
> 2. 加上 -v 参数，输出详细信息：`curl -v test.bob.svc`

感谢，确实是网络问题
