### ISSUE TITLE
点对点方式部署两方求交任务执行失败

### ISSUE THREAD

**Issue by liufan1029** [secretflow/kuscia#187]
1.执行kubectl get kt secretflow-task-20231207153231-single-psi -o yaml命令查看报错信息：
apiVersion: kuscia.secretflow/v1alpha1
kind: KusciaTask
metadata:
  creationTimestamp: "2023-12-07T07:32:32Z"
  generation: 1
  labels:
    kuscia.secretflow/controller: kuscia-job
    kuscia.secretflow/interconn-protocol-type: kuscia
    kuscia.secretflow/job-id: secretflow-task-20231207153231
    kuscia.secretflow/self-cluster-as-initiator: "true"
    kuscia.secretflow/task-alias: single-psi
  name: secretflow-task-20231207153231-single-psi
  ownerReferences:
  - apiVersion: kuscia.secretflow/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KusciaJob
    name: secretflow-task-20231207153231
    uid: 13736228-5fc6-4aab-ae4d-707f6a5b9dc7
  resourceVersion: "8385"
  uid: 4bb0e9e5-9338-4038-a577-6acf9e2eca0e
spec:
  initiator: alice
  parties:
  - appImageRef: secretflow-image
    domainID: alice
    template:
      spec: {}
  - appImageRef: secretflow-image
    domainID: bob
    template:
      spec: {}
  scheduleConfig: {}
  taskInputConfig: '{"sf_datasource_config":{"bob":{"id":"default-data-source"},"alice":{"id":"default-data-source"}},"sf_cluster_desc":{"parties":["alice","bob"],"devices":[{"name":"spu","type":"spu","parties":["alice","bob"],"config":"{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"},{"name":"heu","type":"heu","parties":["alice","bob"],"config":"{\"mode\":
    \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"}]},"sf_node_eval_param":{"domain":"preprocessing","name":"psi","version":"0.0.1","attr_paths":["input/receiver_input/key","input/sender_input/key","protocol","precheck_input","bucket_size","curve_type"],"attrs":[{"ss":["id1"]},{"ss":["id2"]},{"s":"ECDH_PSI_2PC"},{"b":true},{"i64":"1048576"},{"s":"CURVE_FOURQ"}],"inputs":[{"type":"sf.table.individual","meta":{"@type":"type.googleapis.com/secretflow.component.IndividualTable","schema":{"ids":["id1"],"features":["age","education","default","balance","housing","loan","day","duration","campaign","pdays","previous","job_blue-collar","job_entrepreneur","job_housemaid","job_management","job_retired","job_self-employed","job_services","job_student","job_technician","job_unemployed","marital_divorced","marital_married","marital_single"],"id_types":["str"],"feature_types":["float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float"]},"num_lines":"-1"},"data_refs":[{"uri":"alice.csv","party":"alice","format":"csv"}]},{"type":"sf.table.individual","meta":{"@type":"type.googleapis.com/secretflow.component.IndividualTable","schema":{"ids":["id2"],"features":["contact_cellular","contact_telephone","contact_unknown","month_apr","month_aug","month_dec","month_feb","month_jan","month_jul","month_jun","month_mar","month_may","month_nov","month_oct","month_sep","poutcome_failure","poutcome_other","poutcome_success","poutcome_unknown"],"labels":["y"],"id_types":["str"],"feature_types":["float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float","float"],"label_types":["int"]},"num_lines":"-1"},"data_refs":[{"uri":"bob.csv","party":"bob","format":"csv"}]}]},"sf_output_uris":["psi-output.csv"],"sf_output_ids":["psi-output"]}'
status:
  completionTime: "2023-12-07T07:32:39Z"
  conditions:
  - lastTransitionTime: "2023-12-07T07:32:32Z"
    status: "True"
    type: ResourceCreated
  - lastTransitionTime: "2023-12-07T07:32:32Z"
    status: "True"
    type: Running
  - lastTransitionTime: "2023-12-07T07:32:39Z"
    status: "False"
    type: Success
  lastReconcileTime: "2023-12-07T07:32:39Z"
  message: The remaining non-failed parties counts 1 is less than the task success
    threshold 2
  partyTaskStatus:
  - domainID: alice
    phase: Failed
  - domainID: bob
    message: Kuscia task failed
    phase: Failed
  phase: Failed
  podStatuses:
    alice/secretflow-task-20231207153231-single-psi-0:
      namespace: alice
      nodeName: root-kuscia-autonomy-alice
      podName: secretflow-task-20231207153231-single-psi-0
      podPhase: Failed
      reason: Error
    bob/secretflow-task-20231207153231-single-psi-0:
      namespace: bob
      podName: secretflow-task-20231207153231-single-psi-0
      podPhase: Failed
      reason: Error
  startTime: "2023-12-07T07:32:32Z"
2. 执行kubectl logs -n alice  secretflow-task-20231207153231-single-psi-0得到以下信息
Error from server: Get "https://172.18.0.2:10250/containerLogs/alice/secretflow-task-20231207153231-single-psi-0/secretflow": proxy error from 0.0.0.0:6443 while dialing 172.18.0.2:10250, code 503: 503 Service Unavailable
3.查看kuscia.log 日志  cat kuscia.log | grep secretflow-task-20231207153231-single-psi如下：
[
[Uploading kuscia_log.txt…]()
](url)

**Comment by 6fj** [comment]
Hi @liufan1029 

麻烦放一下日志，感谢！

**Comment by liufan1029** [comment]
> Hi @liufan1029
> 
> 麻烦放一下日志，感谢！



> Hi @liufan1029
> 
> 麻烦放一下日志，感谢！

 kuscia.log的日志见附件：
[kuscia_log.txt](https://github.com/secretflow/kuscia/files/13597981/kuscia_log.txt)

**Comment by 6fj** [comment]
@UniqueMarvin 能否指导一下获取secretflow的日志，kuscia的日志看不出什么问题，感谢！

**Comment by cho-chem** [comment]
> @UniqueMarvin 能否指导一下获取secretflow的日志，kuscia的日志看不出什么问题，感谢！

看了下 Kuscia 日志，SecretFlow 的 exitcode 是132，而且是启动后立即就挂掉的，所以才没有日志

**Comment by liufan1029** [comment]
> > @UniqueMarvin 能否指导一下获取secretflow的日志，kuscia的日志看不出什么问题，感谢！
> 
> 看了下 Kuscia 日志，SecretFlow 的 exitcode 是132，而且是启动后立即就挂掉的，所以才没有日志

您好   像这种情况该怎么解决呢

**Comment by cho-chem** [comment]
你好
1. 麻烦给下机器环境，操作系统、内核版本、 CPU 型号
2. 请提供下对端节点的 kuscia.log

**Comment by liufan1029** [comment]
> 你好
> 
> 1. 麻烦给下机器环境，操作系统、内核版本、 CPU 型号
> 2. 请提供下对端节点的 kuscia.log

环境信息如下：
1.操作系统版本：CentOS Linux release 7.9.2009 (Core)
2.CPU信息:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                8
On-line CPU(s) list:   0-7
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             8
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Model name:            Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)
Stepping:              9
CPU MHz:               2699.998
BogoMIPS:              5399.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
L3 cache:              16384K
NUMA node0 CPU(s):     0-7
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat md_clear spec_ctrl intel_stibp

3.内存信息：
            total        used        free      shared  buff/cache   available
Mem:    15G        6.6G        230M         97M        8.7G        8.5G
Swap:     0B          0B          0B


4.内核版本：Linux version 3.10.0-1160.45.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Oct 13 17:20:51 UTC 2021	

本端和对端的日志见文件：
[本端kuscia日志.txt](https://github.com/secretflow/kuscia/files/13609288/kuscia.txt)
[对端节点kuscia.txt](https://github.com/secretflow/kuscia/files/13609289/kuscia.txt)

**Comment by cho-chem** [comment]
Hi @liufan1029 我看日志只有今天上午的，两边的节点应该被重装过了，重装后跑任务还有这个问题吗？

**Comment by liufan1029** [comment]
> Hi @liufan1029 我看日志只有今天上午的，两边的节点应该被重装过了，重装后跑任务还有这个问题吗？

是的，重新装了  装完后还有这个问题

**Comment by cho-chem** [comment]
secretflow 镜像是你自定义的吗？在 kuscia 这层看不到详细的错误日志，猜测可能是 ray 启动失败，有以下两个方案可以排查下：
1. 参考 https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/getting_started/deployment 在两边手动启动下 secretflow 看下报错，ray 的日志在 /tmp 目录
2. 在发起方的节点容器中使用命令 `kubectl edit appimage secretflow-image` 将启动参数修改为 "sleep 36000" 保存退出，再发起任务，再使用命令 `crictl ps` 查看运行的容器 ID，使用命令 `crictl exec -it ${容器ID} bash 进入  secretflow 容器中，手动执行 `python -m secretflow.kuscia.entry /etc/kuscia/task-config.conf` 查看 stdout 和 ray 的错误日志。

**Comment by liufan1029** [comment]
secretflow镜像是我们自定义的镜像，在别的环境运行是没问题的，使用第二种方法执行python -m secretflow.kuscia.entry /etc/kuscia/task-config.conf 报 “Illegal instruction (core dumped)“，查看stdout 日志内容为空，/tmp下没有看到ray相关的日志信息

**Comment by daydayuphere** [comment]
@cho-chem  “Illegal instruction (core dumped)“ 这是不是跟指令集有关系

**Comment by 6fj** [comment]
hi @liufan1029 

看上去是镜像有问题，你可以使用我们官方的镜像吗？

**Comment by 6fj** [comment]
那两个环境有什么不同呢？

比如cpu型号，操作系统等。

**Comment by daydayuphere** [comment]
另外，能跑通的环境是物理机。
有问题的是虚拟机环境。

**Comment by sqh539** [comment]
> hi @liufan1029
> 
> 看上去是镜像有问题，你可以使用我们官方的镜像吗？

换成官方镜像也是同样的情况。

**Comment by sqh539** [comment]
> > hi @liufan1029
> > 看上去是镜像有问题，你可以使用我们官方的镜像吗？
> 
> 换成官方镜像也是同样的情况。

使用的镜像版本是：
secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia                    latest           77c6e5f3c466  
secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8   latest           03805cb4d393

**Comment by daydayuphere** [comment]
> > 你好
> > 
> > 1. 麻烦给下机器环境，操作系统、内核版本、 CPU 型号
> > 2. 请提供下对端节点的 kuscia.log
> 
> 环境信息如下： 1.操作系统版本：CentOS Linux release 7.9.2009 (Core) 2.CPU信息: Architecture: x86_64 CPU op-mode(s): 32-bit, 64-bit Byte Order: Little Endian CPU(s): 8 On-line CPU(s) list: 0-7 Thread(s) per core: 1 Core(s) per socket: 1 Socket(s): 8 NUMA node(s): 1 Vendor ID: GenuineIntel CPU family: 6 Model: 58 Model name: Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS) Stepping: 9 CPU MHz: 2699.998 BogoMIPS: 5399.99 Hypervisor vendor: KVM Virtualization type: full L1d cache: 32K L1i cache: 32K L2 cache: 4096K L3 cache: 16384K NUMA node0 CPU(s): 0-7 Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm ssbd ibrs ibpb stibp fsgsbase tsc_adjust smep erms xsaveopt arat md_clear spec_ctrl intel_stibp
> 
> 3.内存信息： total used free shared buff/cache available Mem: 15G 6.6G 230M 97M 8.7G 8.5G Swap: 0B 0B 0B
> 
> 4.内核版本：Linux version 3.10.0-1160.45.1.el7.x86_64 ([mockbuild@kbuilder.bsys.centos.org](mailto:mockbuild@kbuilder.bsys.centos.org)) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Wed Oct 13 17:20:51 UTC 2021
> 
> 本端和对端的日志见文件： [本端kuscia日志.txt](https://github.com/secretflow/kuscia/files/13609288/kuscia.txt) [对端节点kuscia.txt](https://github.com/secretflow/kuscia/files/13609289/kuscia.txt)

这个有问题的环境，cpu也是支持AVX的，请问是不是还有什么指令是必须要支持但是这里面没有的？
@6fj

**Comment by 6fj** [comment]
hi @daydayuphere

**Comment by 6fj** [comment]
hi @daydayuphere ,

所以现在你在一台宿主机上使用qemu来模拟intel x64来运行centos是吗？
宿主机本身是什么情况呢？
我们目前没有测试过emulator。请问你这边是有适配信创的需求吗？

**Comment by daydayuphere** [comment]
对的，我们是分步骤的两个测试，第一步是在x86上的虚拟机环境，测试虚机的支持情况，遇到上面的问题；
第二步是在飞腾ARM的虚拟机环境上测试，我问的另一个问题https://github.com/secretflow/kuscia/issues/192
