### ISSUE TITLE
最新的镜像包kuscia-autonomy-alice-certs 目录下是空的

### ISSUE THREAD

**Issue by liuhaichaogithub** [secretflow/kuscia#194]
![image](https://github.com/secretflow/kuscia/assets/40063899/d336ee33-4d64-4b56-8f4f-e9800dfee3a2)
原来的那些证书没有了，镜像里面certs目录下也是空的
![image](https://github.com/secretflow/kuscia/assets/40063899/bbac0302-4261-49e1-953c-b80642fbdc0a)

**Comment by liuhaichaogithub** [comment]
有，看来deploy.sh需要修改一下了

**Comment by gshilei** [comment]
我们正在更新官方文档，可以暂时参考代码中的docs
https://github.com/secretflow/kuscia/tree/main/docs
