### ISSUE TITLE
目前 Kuscia 仅支持`localfs`数据源,何时支持oss在内的其他数据源呢？

### ISSUE THREAD

**Issue by john8628** [secretflow/kuscia#197]
目前企业级别的应用数据量至少都是千万级别甚至千亿级别，
1: 目前 Kuscia 仅支持`localfs`数据源,何时支持oss在内的其他数据源呢？
2: 计算引擎是否支持第三方，或者secretFlow 计算引擎能否支持这种量级的数据计算吗？

**Comment by Eiji911** [comment]
预计1月8号发版，OSS数据源已经在开源流程中。
计算引擎可以支持第三方。
请问您想要使用哪个引擎啊？
