### ISSUE TITLE
安装kuscia lite节点的时候，出现unknown flag: --mount 

### ISSUE THREAD

**Issue by john8628** [secretflow/kuscia#206]
在secretePad中增加一个节点，参考https://www.secretflow.org.cn/docs/quickstart/fn9h9yqoievouz2a 或者https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/deploy_master_lite_cn 会出现unknown flag: --mount  ；
由于docker版本过旧;会导致--mount参数不能识别

- 参考 https://stackoverflow.com/questions/48167955/docker-unknown-flag-mount

**Comment by Chrisdehe** [comment]
您好，请问问题是解决了吗？是否还有其他疑问？

**Comment by john8628** [comment]
> 您好，请问问题是解决了吗？是否还有其他疑问？

升级docker版本，解决了
