### ISSUE TITLE
bug: start_standalone.sh init_sf_image_info未正确设置SF_IMAGE_REGISTRY

### ISSUE THREAD

**Issue by imwangyt** [secretflow/kuscia#208]
1、ctr导入docker镜像时，如果镜像名没有register，会默认成是docker.io的；
2、当前的secretflow-allinone-package里使用了secretflow/secretflow-lite-anolis8:1.3.0.dev20231109，等同register是docker.io；
3、上述情况下，lite的环境变量REGISTRY_ENDPOINT应该是docker.io/secretflow，但start_standalone.sh脚本的init_sf_image_info有问题，导致SF_IMAGE_REGISTRY设置错误，进而环境变量REGISTRY_ENDPOINT设置错误，依然是secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow，所以任务拉起的时候，会重新去pull镜像，如果此时lite容器无法访问外网，就会报错。
4、修改脚本如下：
```shell
function init_sf_image_info() {
  if [ "$SECRETFLOW_IMAGE" != "" ]; then
    SF_IMAGE_TAG=${SECRETFLOW_IMAGE##*:}
    path_separator_count="$(echo "$SECRETFLOW_IMAGE" | tr -cd "/" | wc -c)"
    if [ ${path_separator_count} == 1 ]; then
      registry="docker.io"
      bucket=$(echo $SECRETFLOW_IMAGE | cut -d "/" -f 1)
      name_and_tag=$(echo $SECRETFLOW_IMAGE | cut -d "/" -f 2)
      name=$(echo "$name_and_tag" | sed "s/:${SF_IMAGE_TAG}//")
      SF_IMAGE_REGISTRY="$registry/$bucket"
      SF_IMAGE_NAME="$name"
      #SF_IMAGE_NAME=$(echo "$SECRETFLOW_IMAGE" | sed "s/:${SF_IMAGE_TAG}//")
    elif [ $path_separator_count == 2 ]; then
      registry=$(echo $SECRETFLOW_IMAGE | cut -d "/" -f 1)
      bucket=$(echo $SECRETFLOW_IMAGE | cut -d "/" -f 2)
      name_and_tag=$(echo $SECRETFLOW_IMAGE | cut -d "/" -f 3)
      name=$(echo "$name_and_tag" | sed "s/:${SF_IMAGE_TAG}//")
      SF_IMAGE_REGISTRY="$registry/$bucket"
      SF_IMAGE_NAME="$name"
    fi
  fi
}
```

**Comment by cho-chem** [comment]
hi @imwangyt 感谢反馈，我们推荐默认使用阿里云的镜像，我们会在 secretflow-allinone-package 里修改下镜像的默认地址。

**Comment by imwangyt** [comment]
> hi @imwangyt 感谢反馈，我们推荐默认使用阿里云的镜像，我们会在 secretflow-allinone-package 里修改下镜像的默认地址。

那start_standalone.sh脚本的init_sf_image_info要修复么？

**Comment by yushiqie** [comment]
> > hi @imwangyt 感谢反馈，我们推荐默认使用阿里云的镜像，我们会在 secretflow-allinone-package 里修改下镜像的默认地址。
> 
> 那start_standalone.sh脚本的init_sf_image_info要修复么？

目前不用修复，我们将去除默认使阿里云镜像仓库的参数， start_standalone.sh 里默认使用的 SECRETFLOW_IMAGE 是阿里云的。如果你想设置成 docker.io 的镜像，可以使用 export SECRETFLOW_IMAGE=secretflow/secretflow-lite-anolis8:1.3.0.dev20231109 方式。
