### ISSUE TITLE
Kuscia API中CreateDomainRoute的使用

### ISSUE THREAD

**Issue by zhengyang16** [secretflow/kuscia#211]
使用Kuscia API新建DomainRoute的时候，请求和报错是这样的：
![image](https://github.com/secretflow/kuscia/assets/51041934/e952689b-f9fc-423a-b25d-9a7c3dce43f7)
使用脚本
sudo docker exec -it kuscia-autonomy-alice-0.5.0.dev231207 scripts/deploy/join_to_host.sh alice bob https://10.24.93.11:38081
就是正常的
因为没有API使用的例子，所以不清楚这个报错是什么问题

**Comment by zhengyang16** [comment]
补充：使用的kuscia版本是v0.5.0.dev231207

**Comment by zhengyang16** [comment]
尝试了之后，接口DomainRoute不报错了，但是任务失败了，我对比了以下脚本部署和API部署的`kubectl get dr -n alice -o yaml`
脚本部署：
![image](https://github.com/secretflow/kuscia/assets/51041934/57fb7ffb-61ab-40b5-8f1a-8664cfd1988d)
API部署：
<img width="637" alt="1704874809674" src="https://github.com/secretflow/kuscia/assets/51041934/5b8adcd7-d620-48fb-9543-5bf44d855af8">

**Comment by zhengyang16** [comment]
补充，脚本部署在status下token非空，api部署为空
![image](https://github.com/secretflow/kuscia/assets/51041934/b9740d5a-0517-4cd0-9a2a-5aad9d9d43c3)

**Comment by yujun4464** [comment]
@zhengyang16  使用https授权，字段可以使用 ："protocol": "HTTPS"。这个我们也会在文档中补充上 HTTPS 选项

**Comment by zhengyang16** [comment]
好的成功了，谢谢
