### ISSUE TITLE
用阿里云k8s部署kuscia报错

### ISSUE THREAD

**Issue by uguesswhoami** [secretflow/kuscia#216]
在用阿里云的k8s部署kuscia镜像的时候 报了
2024-01-16 16:45:45.487 FATAL modules/modules.go:72 error building kubernetes client config from token, detail-> build config from flags failed, detail-> stat /home/kuscia/etc/kubeconfig: no such file or directory这个异常  
应该怎么解决呢

**Comment by longshan-ant** [comment]
使用mysql backend，请手动创建一下kine表结构，请参考 [配置文件](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/kuscia_config_cn) 中关于datastoreEndpoint的介绍

**Comment by uguesswhoami** [comment]
已经创建了表  是和数据表的创建有关系？这个报错我看是kubeconfig读不到

**Comment by uguesswhoami** [comment]
> 使用mysql backend，请手动创建一下kine表结构，请参考 [配置文件](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/deployment/kuscia_config_cn) 中关于datastoreEndpoint的介绍


已经创建了表 是和数据表的创建有关系？这个报错我看是kubeconfig读不到

**Comment by yushiqie** [comment]
目前发布的 kuscia， 对数据库表用户有权限要求：
1. 用户有创建数据库权限
2. 用户有创建数据表 kine 权限
3. 用户对表 kine 记录有增删改查权限。

请确认配置的数据库用户是否有上述3个权限， 另外也确保数据库的连通性正常

下一个版本的 kuscia：
1. 去除上述 1，2 的限制，对数据库用户的最低要求是 3。
2. 增加数据库的连通性的检查，给出明确的数据库相关的报错信息
3. 优化` stat /home/kuscia/etc/kubeconfig no such file or directory`  的报错，这个根本原因是k3s 没有正确启动，k3s 没有正确启动的根因大概率跟上面的数据表权限有关。

**Comment by yushiqie** [comment]
请问你当前用的 kuscia 镜像版本是什么啊，我们发布了kuscia的最新版本 0.6.0.dev240115， 推荐使用最新版本 kuscia呢

**Comment by yushiqie** [comment]
请问这个问题解决了吗
