### ISSUE TITLE
3机点对点部署下，3方参与的求交任务执行

### ISSUE THREAD

**Issue by T-ze-yu** [secretflow/kuscia#217]
3机的信任关系如下：
![image](https://github.com/secretflow/kuscia/assets/75960285/85800a2c-7134-476c-8f83-69d814a1df96)
![image](https://github.com/secretflow/kuscia/assets/75960285/03b05071-71f2-4873-af66-57bc5aa1a7c0)
![image](https://github.com/secretflow/kuscia/assets/75960285/0ea7ef34-7629-4910-979a-e5678c643b64)

3机的数据关系如下：
![image](https://github.com/secretflow/kuscia/assets/75960285/c2e4e47c-0adc-4ace-8e06-26f9d0d081f8)
![image](https://github.com/secretflow/kuscia/assets/75960285/f479406c-e3f4-4e5b-9b24-d5dcbc6c9d32)
![image](https://github.com/secretflow/kuscia/assets/75960285/d5a64ec7-fc00-4326-b4ce-5fffbdb9e1e2)

其中p169节点作为任务的发起方，使用kuscia API创建任务，使用的数据是["41ce8146b44211ee883400505695ad3a", "4f108d4ab44211ee969300505695d109", "b11d3074b44211eea92800505695dbc9"]，整体提交的数据参数是：{'job_id': 'rj6fk6gd9hq277sm', 'initiator': 'p169', 'max_parallelism': 2, 'tasks': [{'app_image': 'secretflow-image', 'parties': [{'domain_id': 'p169'}, {'domain_id': 'p170'}, {'domain_id': 'p131'}], 'alias': 'psi', 'task_id': 'rj6fk6gd9hq277sm', 'task_input_config': '{"sf_datasource_config": {"p169": {"id": "default-data-source"}, "p170": {"id": "default-data-source"}, "p131": {"id": "default-data-source"}}, "sf_cluster_desc": {"parties": ["p169", "p170", "p131"], "devices": [{"name": "spu", "type": "spu", "parties": ["p169", "p170", "p131"], "config": "{\\"runtime_config\\":{\\"protocol\\":\\"REF2K\\",\\"field\\":\\"FM64\\"},\\"link_desc\\":{\\"connect_retry_times\\":60,\\"connect_retry_interval_ms\\":1000,\\"brpc_channel_protocol\\":\\"http\\",\\"brpc_channel_connection_type\\":\\"pooled\\",\\"recv_timeout_ms\\":1200000,\\"http_timeout_ms\\":1200000}}"}, {"name": "heu", "type": "heu", "parties": ["p169", "p170", "p131"], "config": "{\\"mode\\": \\"PHEU\\", \\"schema\\": \\"paillier\\", \\"key_size\\": 2048}"}], "ray_fed_config": {"cross_silo_comm_backend": "brpc_link"}}, "sf_node_eval_param": {"domain": "preprocessing", "name": "psi", "version": "0.0.1", "attr_paths": ["input/receiver_input/key", "input/sender_input/key", "protocol", "precheck_input", "bucket_size", "curve_type"], "attrs": [{"ss": ["id2"]}, {"ss": ["id1"]}, {"ss": ["id0"]}, {"s": "ECDH_PSI_2PC"}, {"b": true}, {"i64": "1048576"}, {"s": "CURVE_FOURQ"}]}, "sf_input_ids": ["41ce8146b44211ee883400505695ad3a", "4f108d4ab44211ee969300505695d109", "b11d3074b44211eea92800505695dbc9"], "sf_output_ids": ["rj6fk6gd9hq277sm"], "sf_output_uris": ["jobs/202401161538167599970/rj6fk6gd9hq277sm-psi-res.csv"]}', 'priority': '100'}]}，但最后任务失败了。请帮忙看下

**Comment by T-ze-yu** [comment]
任务详细信息：
Name:         rj6fk6gd9hq277sm
Namespace:    
Labels:       kuscia.secretflow/interconn-protocol-type=kuscia
              kuscia.secretflow/self-cluster-as-initiator=true
Annotations:  <none>
API Version:  kuscia.secretflow/v1alpha1
Kind:         KusciaJob
Metadata:
  Creation Timestamp:  2024-01-17T02:20:57Z
  Generation:          2
  Managed Fields:
    API Version:  kuscia.secretflow/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:kuscia.secretflow/interconn-protocol-type:
          f:kuscia.secretflow/self-cluster-as-initiator:
      f:spec:
        .:
        f:initiator:
        f:maxParallelism:
        f:scheduleMode:
        f:stage:
        f:tasks:
    Manager:      kuscia
    Operation:    Update
    Time:         2024-01-17T02:20:57Z
    API Version:  kuscia.secretflow/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:completionTime:
        f:conditions:
        f:lastReconcileTime:
        f:phase:
        f:startTime:
        f:taskStatus:
          .:
          f:rj6fk6gd9hq277sm:
    Manager:         kuscia
    Operation:       Update
    Subresource:     status
    Time:            2024-01-17T02:21:07Z
  Resource Version:  125196
  UID:               43465b36-2205-49c5-93e9-34ebd0646793
Spec:
  Initiator:        p169
  Max Parallelism:  2
  Schedule Mode:    BestEffort
  Stage:            Start
  Tasks:
    Alias:      psi
    App Image:  secretflow-image
    Parties:
      Domain ID:        p169
      Domain ID:        p170
      Domain ID:        p131
    Priority:           100
    Task ID:            rj6fk6gd9hq277sm
    Task Input Config:  {"sf_datasource_config": {"p169": {"id": "default-data-source"}, "p170": {"id": "default-data-source"}, "p131": {"id": "default-data-source"}}, "sf_cluster_desc": {"parties": ["p169", "p170", "p131"], "devices": [{"name": "spu", "type": "spu", "parties": ["p169", "p170", "p131"], "config": "{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"}, {"name": "heu", "type": "heu", "parties": ["p169", "p170", "p131"], "config": "{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"}], "ray_fed_config": {"cross_silo_comm_backend": "brpc_link"}}, "sf_node_eval_param": {"domain": "preprocessing", "name": "psi", "version": "0.0.1", "attr_paths": ["input/receiver_input/key", "input/sender_input/key", "protocol", "precheck_input", "bucket_size", "curve_type"], "attrs": [{"ss": ["id2"]}, {"ss": ["id1"]}, {"ss": ["id0"]}, {"s": "ECDH_PSI_2PC"}, {"b": true}, {"i64": "1048576"}, {"s": "CURVE_FOURQ"}]}, "sf_input_ids": ["41ce8146b44211ee883400505695ad3a", "4f108d4ab44211ee969300505695d109", "b11d3074b44211eea92800505695dbc9"], "sf_output_ids": ["rj6fk6gd9hq277sm"], "sf_output_uris": ["jobs/202401161538167599970/rj6fk6gd9hq277sm-psi-res.csv"]}
    Tolerable:          false
Status:
  Completion Time:  2024-01-17T02:21:07Z
  Conditions:
    Last Transition Time:  2024-01-17T02:20:57Z
    Status:                True
    Type:                  JobValidated
    Last Transition Time:  2024-01-17T02:20:57Z
    Status:                True
    Type:                  JobCreateInitialized
    Last Transition Time:  2024-01-17T02:20:57Z
    Status:                True
    Type:                  JobCreateSucceeded
    Last Transition Time:  2024-01-17T02:20:57Z
    Status:                True
    Type:                  JobStartInitialized
    Last Transition Time:  2024-01-17T02:20:57Z
    Status:                True
    Type:                  JobStartSucceeded
  Last Reconcile Time:     2024-01-17T02:21:07Z
  Phase:                   Failed
  Start Time:              2024-01-17T02:20:57Z
  Task Status:
    rj6fk6gd9hq277sm:  Failed
Events:                <none>

**Comment by T-ze-yu** [comment]
[0.log](https://github.com/secretflow/kuscia/files/13958045/0.log)
任务日志文件

**Comment by 6fj** [comment]
所以你是尝试在做三方求交吗？

我们现在还没有多方求交的组件，需要你自行包装成组件才行。

**Comment by T-ze-yu** [comment]
是的，可以讲讲大概要在哪些地方修改包装吗？

**Comment by 6fj** [comment]
hi @T-ze-yu 

以下是你可能需要阅读的文档：
三方求交原理：https://yuque.antfin-inc.com/fengjun.feng/vvm538/mke8sdzusbxfovoz
三方求交教程：https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/tutorial/PSI_On_SPU#%E4%B8%89%E6%96%B9%E9%9A%90%E7%A7%81%E6%B1%82%E4%BA%A4
创建新组件：https://www.secretflow.org.cn/docs/quickstart/mfbgum8vi3ngs4y9

**Comment by T-ze-yu** [comment]
好的，非常感谢

**Comment by T-ze-yu** [comment]
三方求交原理：https://yuque.antfin-inc.com/fengjun.feng/vvm538/mke8sdzusbxfovoz
这个网站一直打不开

**Comment by T-ze-yu** [comment]
三方求交原理：https://yuque.antfin-inc.com/fengjun.feng/vvm538/mke8sdzusbxfovoz
这个网站一直打不开

**Comment by 6fj** [comment]
> 好的，非常感谢

三方求交链接为：https://www.secretflow.org.cn/en/docs/secretflow/v1.3.0b0/user_guide/psi#ecdh-psi-3p
感谢！

**Comment by john8628** [comment]
> > 好的，非常感谢
> 
> 三方求交链接为：https://www.secretflow.org.cn/en/docs/secretflow/v1.3.0b0/user_guide/psi#ecdh-psi-3p 感谢！
@6fj 
如果加了三方隐私求交组件，后续的流程，是否按照两方的组件继续执行，就能完成三方的训练的流程啊？即其他组件不需要做特别的开发和改动啊
