### ISSUE TITLE
kuscia中使用的几种distdata数据表具体的结构在哪边可以查看？

### ISSUE THREAD

**Issue by zhouhansheng** [secretflow/kuscia#219]
secretflow.component.data_utils中定义了9中数据表类型：class DistDataType(BaseEnum):
    VERTICAL_TABLE = "sf.table.vertical_table"
    INDIVIDUAL_TABLE = "sf.table.individual"
    SS_SGD_MODEL = "sf.model.ss_sgd"
    SS_GLM_MODEL = "sf.model.ss_glm"
    SGB_MODEL = "sf.model.sgb"
    BIN_RUNNING_RULE = "sf.rule.binning"
    SS_XGB_MODEL = "sf.model.ss_xgb"
    ONEHOT_RULE = "sf.rule.onehot_encode"
    REPORT = "sf.report"
请问这几种类型的具体结构在哪边可以查看？

**Comment by bulletjet786** [comment]
sf 特有的：
https://github.com/secretflow/secretflow/tree/main/secretflow/protos/secretflow/spec/extend

通用的：
https://github.com/secretflow/spec/blob/main/secretflow/spec/v1/data.proto
https://github.com/secretflow/spec/blob/main/secretflow/spec/v1/report.proto

您可以参考这个文档。
