### ISSUE TITLE
如何在两台机器上分别部署alice、bob，做一个真正的p2p？

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/kuscia#22]
目前使用的脚本，是在单个机器上部署alice和bob节点。

如何在两台机器上分别部署alice、bob，做一个真正的p2p？

./start_standalone.sh p2p
docker exec -it ${USER}-kuscia-autonomy-alice bash
scripts/user/create_example_job.sh
kubectl get kj

**Comment by 6fj** [comment]
Hi @longshan-ant 你能看一下这个问题吗，感谢！

**Comment by longshan-ant** [comment]
参考Issue [17](https://github.com/secretflow/kuscia/issues/17) ， 我们目前在优化节点的创建和优化流程， 还没有正式的文档；我们会在近期（8月初）升级这块能力。 如果比较紧急，可以参考 start_standalone 脚本中的逻辑手动部署下。
主要是在2台机器上手动签发公私钥以及暴露好容器端口。
