### ISSUE TITLE
Kuscia 观测指标导出及其可视化技术

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#220]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第三期](https://github.com/orgs/secretflow/discussions/1007)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

### 任务介绍
任务名称：Kuscia 观测指标导出及其可视化技术
方向：Kuscia/可观测性
任务难度：挑战🌟🌟🌟

### 详细要求
1. 集成node_exporter: [https://github.com/prometheus/node_exporter](https://github.com/prometheus/node_exporter) 至每一个结点容器]
2. 将现有 metricexporter 观测指标统一导出至promethtus，配置grafana容器，参考 https://github.com/secretflow/kuscia/tree/main/pkg/metricexporter;
3. 提供kuscia-monitor容器（包含promethues/grafana能力）
4. P2P模式下，每一个节点对应一个kuscia-monitor容器；中心化模式下，统一在kuscia-master提供监控kuscia-monitor容器
5. 制作 grafana 大盘，包括机器实例大盘、结点大盘、kuscia-master 大盘;
6. 提供一个脚本根据不同模式自动配置、部署该 kuscia-monitor 容器;
7. 提供一份操作文档;
8. 提交说明：
- 请先准备你的设计思路方案，并在 ISSUE 下评论提交方案;
- 经过 Reviewer 确认设计思路方案后再根据确认后的方案，进行相关的功能开发;
- 完成开发后，关联该 ISSUE 并提交代码至 [https://github.com/secretflow/kuscia/](https://github.com/secretflow/kuscia/tree/main/pkg/controller);
- 代码规范：[https://github.com/uber-go/guide/blob/master/style.md](https://github.com/uber-go/guide/blob/master/style.md);

### 能力要求
- 了解 Kuscia 原理
- 熟悉 golang
- 熟悉 Prometheus
- 熟悉 Grafana

### 操作说明
Kuscia 开发参考：[https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_c](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by Vancasola** [comment]
Vancasola Give it to me
