### ISSUE TITLE
kuscia 中的算法组件清单

### ISSUE THREAD

**Issue by zhangning2222** [secretflow/kuscia#222]
kuscia 中是否支持pir任务，是否有相关的示例

**Comment by Chrisdehe** [comment]
目前PIR尚未包装成组件，预计近期会支持，敬请期待。

**Comment by Chrisdehe** [comment]
目前无较多业务场景，优先级较低，暂时hold

**Comment by zhangning2222** [comment]
> 目前无较多业务场景，优先级较低，暂时hold

想了解下，如果我们把secretflow里的pir集成到kuscia里面，有相关的手册可以参考吗

**Comment by Chrisdehe** [comment]
我们有kuscia注册自定义算法镜像的教程可以参考下
https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/register_custom_image

另外 您目前这部分的需求和场景是怎样呢？

**Comment by Chrisdehe** [comment]
很多PIR场景其实是可以用PSI替代的， 所以对于PIR的需求，我们一般想了解的更加细致一点。

**Comment by zhangning2222** [comment]
> 很多PIR场景其实是可以用PSI替代的， 所以对于PIR的需求，我们一般想了解的更加细致一点。

目前我们的需求比较多的是key-value这种方式的，使用key值查询value值这种方式

**Comment by longshan-ant** [comment]
> 了解下，如果我们把secretflow里的pir集成到kuscia里面，有相关的手册可以参

你们是期望PIR每一次query是一个短作业，还是PIR是一个常驻服务？
