### ISSUE TITLE
kuscia支持pod跑在TEE中吗

### ISSUE THREAD

**Issue by GLei16** [secretflow/kuscia#225]

**Comment by longshan-ant** [comment]
可以参考 [枢纽模式](https://www.secretflow.org.cn/docs/quickstart/og3dcwxx2u7zv18m),  kuscia 会拉起一个基于occlum 的容器，如果跑在真实TEE硬件上，对应的pod就是跑在TEE中。

**Comment by henrysun007** [comment]
这个拉起的pod支持mount device或者sgx device plugin吗？

**Comment by bulletjet786** [comment]
目前Kuscia的AppImage还尚未支持挂载文件，AppImage的文档位置为：https://www.secretflow.org.cn/docs/kuscia/v0.5.0b0/zh-Hans/reference/concepts/appimage_cn。所以Kuscia现在还暂未支持跑在真实TEE硬件上的TEE应用。

**Comment by bulletjet786** [comment]
/home/kuscia/var/storage/data 这个目录是由Kuscia的agent在启动pod时挂载进去的，是kuscia的agent本身默认挂载的，目前还没有支持AppImage上的文件挂载功能。
