### ISSUE TITLE
Kuscia 模块ready探测函数抽取

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#226]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

### 任务介绍
- 任务名称：Kuscia 模块ready探测函数抽取
- 方向：Kuscia/代码重构
- 任务难度：进阶🌟🌟
- 任务期望完成时间：4-5 周

### 任务描述
kuscia的各模块进行启动状态检查时，大部分都是访问模块的HTTP服务来进行探活，但是目前各个模块都是独立实现，导致代码有点重复，期望重构相关逻辑，减少重复逻辑

### 详细要求
1. 提供一份操作文档;
2. 提交说明：
- 请先准备你的设计思路方案，并在 ISSUE 下评论提交方案;
- 经过 Reviewer 确认设计思路方案后再根据确认后的方案，进行相关的功能开发;
- 完成开发后，关联该 ISSUE 并提交代码至 [https://github.com/secretflow/kuscia/](https://github.com/secretflow/kuscia/);
- 代码规范：[https://github.com/uber-go/guide/blob/master/style.md](https://github.com/uber-go/guide/blob/master/style.md);

### 能力要求
- 了解 Kuscia 原理
- 熟悉 Golang

**Comment by imwangyt** [comment]
Give it to me!

**Comment by Yeekin-GYJ** [comment]
经沟通该任务回收，欢迎其他小伙伴认领～

**Comment by pa4s** [comment]
我想参与一下这个issue  您方便告诉我一下具体需要重构探活的模块在哪几个文件夹么？

**Comment by Candicepan** [comment]
> 我想参与一下这个issue 您方便告诉我一下具体需要重构探活的模块在哪几个文件夹么？

hello～感谢关注呀～该任务已有内部实现，欢迎关注 kusica 其他任务并参与共建～

**Comment by Candicepan** [comment]
具体实现代码：https://github.com/secretflow/kuscia/tree/main/cmd/kuscia/modules
