### ISSUE TITLE
验证 Kuscia 《快速入门》文档，包括文档流程和 standalone.sh 脚本

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#23]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
-  任务名称：验证 Kuscia [《快速入门》](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/quickstart_cn)文档和脚本，包括文档流程和 standalone.sh 脚本验证，保证文档和脚本的正确性
-  技术方向：Kuscia/docs
-  任务难度：热身🌟

## 详细要求
请基于 Kuscia master 验证上述文档的具体操作流程和脚本是否能够成功运行。在部署脚本的同时，也欢迎对文档内容通顺（语句与错别字）进行修正。

## 能力要求
-  了解基本 git 操作
-  熟悉 Docker、shell
-  对 Kuscia 有一定了解，成功运行过部分示例文档

## 操作指引
-  若脚本能够正常运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若脚本执行过程中报错，关联本 ISSUE 并提交修复后的代码提交至 https://github.com/secretflow/kuscia/tree/main/scripts/deploy
-  若文档存在错误，关联本 ISSUE 并将修复后的文档提交至 https://github.com/secretflow/kuscia/tree/main/docs/getting_started 
   - 注意在提交修复后的文档之前，请先使用 make docs 命令验证文档正确性

**Comment by fffmath** [comment]
fffmath Give it to me

**Comment by fffmath** [comment]
系统 Windows(Ubuntu 20.04 on WSL2)
需要注意的是wsl使用docker需要把systemctl start docker中 systemctl 换成service。
# 前置操作
配置 Kuscia 镜像，以下示例选择使用 latest 版本镜像（更多镜像版本请参考 Kuscia tags）：
![66438318c48f025c35564bccdbf30be](https://github.com/secretflow/kuscia/assets/58581109/e8201674-3647-43ed-a5fc-abedffcb8d07)
获取 Kuscia 安装脚本，安装脚本会下载到当前目录：
![25b438360dfbaad11856337a02befce](https://github.com/secretflow/kuscia/assets/58581109/b6621bc5-ab9d-4513-a2d2-6d0cf3e47836)
# 中心化组网模式
## 启动集群，会拉起 3 个 docker 容器，包括一个控制平面 master 和两个 Lite 节点 alice 和 bob。
![77585faee5adc480c8939ce76e19b6e](https://github.com/secretflow/kuscia/assets/58581109/834f6afe-9d05-4e10-bd8c-bde6650f472b)
![79c1ccae353f4040f46bff11f2676bd](https://github.com/secretflow/kuscia/assets/58581109/77349409-0df7-4330-8105-2c9a4314dcbc)
登入 master 容器&创建并启动作业（两方 PSI 任务）&查看作业状态。
![7db98b26fa96bbcd22a2c753397b560](https://github.com/secretflow/kuscia/assets/58581109/4a8789a8-24b7-4891-bf05-9a68ff4c70be)
# 点对点组网模式
启动集群，会拉起两个 docker 容器，分别表示 Autonomy 节点 alice 和 bob。
![8372fe580977c9488d007335773e997](https://github.com/secretflow/kuscia/assets/58581109/4762764b-942b-4260-898d-b8d15e3cd354)
![8b8934d93d2421760f017c0fc2f4aa0](https://github.com/secretflow/kuscia/assets/58581109/25bc19e6-bee9-4c02-9cff-cb48ab1016aa)
登入 alice 节点容器（或 bob 节点容器）& 创建并启动作业（两方 PSI 任务）。
![db0cdfd49a8c9d34fb4cdec59f3f607](https://github.com/secretflow/kuscia/assets/58581109/f12ec139-1315-4a76-ae5b-edb472183c84)
查看作业状态（注：有时出现作业失败的情况）
![3c2160d89efdbc900cd27372e259fa2](https://github.com/secretflow/kuscia/assets/58581109/ec555651-6db7-453c-8255-b51ff1feb449)
![b5752fd6ea38569476fcd83221cafcd](https://github.com/secretflow/kuscia/assets/58581109/a00a0093-811b-4ddc-8a0e-6fac3614de7e)
结果输出（仅前4行）：
![ed3342360f9e3192e6b2f8b6eddafc6](https://github.com/secretflow/kuscia/assets/58581109/b46728e4-1466-4486-b09f-a87b79e1a7d6)

**Comment by Eiji911** [comment]
LGTM

**Comment by Candicepan** [comment]
> fffmath Give it to me

Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx#) to complete the registration.
If you are an overseas developer, you can complete the event registration by sending an email. Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com) Title：[OSCP] sign up + GitHub ID Text：Name + GitHub ID + Current school/Company + Major/Technical fields
