### ISSUE TITLE
kuscia如何支持的端口复用

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/kuscia#231]
envoy和xds server，确保了支持动态配置。
如果通过kuscia API server创建一个psi任务，怎样的一种机制保证了动态配置注入到了xds server呢，具体的流程是什么样的？

**Comment by LeeTheByRiver** [comment]
envoy xds 中的配置分为两类：1）和集群本身相关的配置，集群配置好之后基本不变；2）和任务相关的配置，和 task 强关联，在 task 启动时触发配置，在 task 完成后摘除。

在kuscia中，一个job对应多个task，task是任务执行的最小单元。以示例中的psi为例，执行子task时对应会创建 3 个 k8s service，提供服务发现能力，这 3 个 service 分别对应：

* rayfed 服务——service-${task-name}-global
* ray 服务——service-${task-name}-fed
* spu 服务——service-${task-name}-spu

kuscia 的 gateway 模块通过 List-Watch 从 api-server 获取 service 和 endpoint 变更，对应生成 xds cluster 和 route 配置。gateway 模块同时也是一个xds server，envoy 通过 grpc 从 gateway 获取更新的cds和rds配置。

![image](https://github.com/secretflow/kuscia/assets/148946228/31dc50d4-2e68-4e03-927f-d0ea44398eaa)

![image](https://github.com/secretflow/kuscia/assets/148946228/3a4648a1-1357-410b-9a4d-9c25de5d347a)

**Comment by daydayuphere** [comment]
多谢老师答复。
下面创建各个service的代码没有找到，在哪里呢
------
以示例中的psi为例，执行子task时对应会创建 3 个 k8s service，提供服务发现能力，这 3 个 service 分别对应：

rayfed 服务——service-${task-name}-global
ray 服务——service-${task-name}-fed
spu 服务——service-${task-name}-spu

**Comment by nfangxu** [comment]
kuscia 对 envoy 添加了多个 filter，他们是否在端口复用中起到了一些作用呢？

**Comment by cho-chem** [comment]
Hi @nfangxu  是的，确实起到了一些作用，Kuscia envoy 中的 filter 其中一个作用就是替换请求的 host，将 host 替换为 header 中保存的后端真正的 service name， 以此实现暴露一个网关支持访问多个服务的能力。

**Comment by nfangxu** [comment]
后续是否有计划将端口复用相关的逻辑抽离出来做一个单独功能呢？这样的话可以更加灵活的适配一些实际应用场景，而不是与kuscia强绑定。

**Comment by cho-chem** [comment]
目前没有这个计划，这个需求我们带回去后续内部评估一下
