### ISSUE TITLE
fate作业执行失败

### ISSUE THREAD

**Issue by linushio** [secretflow/kuscia#233]
运行脚本sh scripts/templates/fate/lr_job.sh
提示：
/home/kuscia /home/kuscia
The AppImage "fate-image" is invalid: spec.deployTemplates[0].spec.containers[0].workingDir: Required value

**Comment by linushio** [comment]
中心化组网模式

**Comment by Chrisdehe** [comment]
好的我们复现一下

**Comment by linushio** [comment]
感谢

**Comment by bulletjet786** [comment]
您可以先尝试下修改文件：scripts/templates/fate/app_image.fate.yaml
在L19后增加
```
            workingDir: /home/kuscia
```
注意锁进，与L19行的name同级。

我们将会在后续版本修复这个问题。

**Comment by linushio** [comment]
/home/kuscia /home/kuscia
appimage.kuscia.secretflow/fate-image created
With JOB_EXAMPLE=FATE LR, job via APP_IMAGE=fate-image creating ...
kusciajob.kuscia.secretflow/fate-task-20240223092848 created
Job 'fate-task-20240223092848' created successfully. You can use the following command to display job status:
  kubectl get kj -n cross-domain
  
kubectl get kj -n cross-domain
No resources found in cross-domain namespace.这里找不到任务

**Comment by linushio** [comment]
kubectl get kj
NAME                       STARTTIME   COMPLETIONTIME   LASTRECONCILETIME   PHASE
fate-task-20240223092848

**Comment by bulletjet786** [comment]
好的，多谢，我们这边跟进下这个问题

**Comment by bigdadel** [comment]
请先按照文档 https://www.secretflow.org.cn/docs/kuscia/v0.5.0b0/zh-Hans/tutorial/run_fate_cn#id4
确认 FATE 集群节点部署完毕

**Comment by linushio** [comment]
之前出现错误时节点部署是完成的，刚才重试了下，打镜像报错 make fate-adaptor-app-image
 Errors during downloading metadata for repository 'AppStream':
  - Status code: 404 for http://mirrors.openanolis.cn/anolis/8/AppStream/x86_64/os/repodata/5019c723b5c0882e066e622c413cfc1105df49dafadfa07d3caed0967ce4e4b2-primary.xml.gz (IP: 120.226.194.108)
  - Status code: 404 for http://mirrors.openanolis.cn/anolis/8/AppStream/x86_64/os/repodata/8c754e1b3861c36cc1f592ef1175436fc6dd0964d3afc33900d1a3c15a70a9fe-filelists.xml.gz (IP: 120.226.194.108)
Error: Failed to download metadata for repo 'AppStream': Yum repo downloading error: Downloading error(s): repodata/5019c723b5c0882e066e622c413cfc1105df49dafadfa07d3caed0967ce4e4b2-primary.xml.gz - Cannot download, all mirrors were already tried without success; repodata/8c754e1b3861c36cc1f592ef1175436fc6dd0964d3afc33900d1a3c15a70a9fe-filelists.xml.gz - Cannot download, all mirrors were already tried without success; repodata/3dfc3222c7a40ccd53f8e65905971eae94637bb5b52f576fe2120e3561628867-modules.yaml.xz - Cannot download, all mirrors were already tried without success

**Comment by bigdadel** [comment]
这个看起来是网络问题，下载资源的时候网络访问失败

**Comment by linushio** [comment]
应该不是吧，这代表着找不到这个包

**Comment by bigdadel** [comment]
> /home/kuscia /home/kuscia appimage.kuscia.secretflow/fate-image created With JOB_EXAMPLE=FATE LR, job via APP_IMAGE=fate-image creating ... kusciajob.kuscia.secretflow/fate-task-20240223092848 created Job 'fate-task-20240223092848' created successfully. You can use the following command to display job status: kubectl get kj -n cross-domain
> 
> kubectl get kj -n cross-domain No resources found in cross-domain namespace.这里找不到任务

fate 任务不在 cross-domain 的 namespace 下，kubectl get kj -A 应该是可以看到的

**Comment by linushio** [comment]
kubectl get kj
NAME STARTTIME COMPLETIONTIME LASTRECONCILETIME PHASE
fate-task-20240223092848后续这里，显示出来后边为空的

**Comment by bigdadel** [comment]
> kubectl get kj NAME STARTTIME COMPLETIONTIME LASTRECONCILETIME PHASE fate-task-20240223092848后续这里，显示出来后边为空的

可以尝试在 scripts/templates/fate/fate_job.yaml L3 的 metadata 字段新增加一行参数：
`  namespace: cross-domain`
注意缩进与参数   name: {{.JOB_NAME}} 一致，这样可以让 FATE 任务的 pod 在 cross-domain 的 Namespace 下，任务就可以正常直行了。
后续我们会修复这个问题。

**Comment by linushio** [comment]
fate-task-20240313113635         10s         6s               6s                  Failed重试之后提示failed

**Comment by bigdadel** [comment]
> fate-task-20240313113635 10s 6s 6s Failed重试之后提示failed
> 
> kubectl logs -f fate-task-20240313113635-data-reader-0 -n bob Error from server: Get "https://172.20.0.4:10250/containerLogs/bob/fate-task-20240313113635-data-reader-0/fate-adapter?follow=true": proxy error from 0.0.0.0:6443 while dialing 172.20.0.4:10250, code 502: 502 Bad Gateway

请先确保 Fate 容器和 Pod 处于运行正常的状态。

**Comment by linushio** [comment]
![Uploading image.png…]()
部署成功的

**Comment by linushio** [comment]
![image](https://github.com/secretflow/kuscia/assets/44011200/86a06113-872c-417c-ac77-356ba4f89095)

**Comment by UniqueMarvin** [comment]
hi， 这个问题 @bulletjet786 已修改，但代码还未发布，预计03-15 推送代码

> ![image](https://private-user-images.githubusercontent.com/44011200/312326764-86a06113-872c-417c-ac77-356ba4f89095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTAzNjQsIm5iZiI6MTcxMDMxMDA2NCwicGF0aCI6Ii80NDAxMTIwMC8zMTIzMjY3NjQtODZhMDYxMTMtODcyYy00MTdjLWFjNzctMzU2YmE0Zjg5MDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA2MDc0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OGU0YmZiNzFmN2EzNjY1N2UxODQ0MzA0YjQ2NDg0NDQwNTA3ZTk3OGZmY2Q0NTU5NDJiNzU2NzM1MWEwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.20HDktAZdzW3RXZrkfAQy3i1LZC9--IrCZZ8sNfVj9c)

**Comment by linushio** [comment]
意思是等待新版本发布使用最新版本吗？

**Comment by UniqueMarvin** [comment]
> 意思是等待新版本发布使用最新版本吗？

对的新的代码会修复这个问题

**Comment by linushio** [comment]
好的

**Comment by linushio** [comment]
使用新版本0.6.0b0，日志是这样的
[root@root-kuscia-master kuscia]# kubectl get kj -A
NAMESPACE      NAME                             STARTTIME   COMPLETIONTIME   LASTRECONCILETIME   PHASE
cross-domain   secretflow-task-20240318170407   29m         28m              28m                 Succeeded
default        fate-task-20240318171423                                                          
default        fate-task-20240318173202
