### ISSUE TITLE
多机部署中心化集群执行测试作业失败

### ISSUE THREAD

**Issue by linushio** [secretflow/kuscia#236]
文档地址：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.5.0b0/deployment/deploy_master_lite_cn
系统为3台ubuntu系统

查看master容器中pods日志
  Warning  FailedScheduling  50s   kuscia-scheduler  0/2 nodes are available: failed to get task resource bob/ for pod. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod., can not find related task resource.
  Warning  FailedScheduling  48s   kuscia-scheduler  0/2 nodes are available: 2 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling., reject the pod secretflow-task-20240228161259-single-psi-0 even after PostFilter.

  Warning  FailedScheduling  3m1s   kuscia-scheduler  0/2 nodes are available: failed to get task resource alice/ for pod. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod., can not find related task resource.
  Warning  FailedScheduling  2m59s  kuscia-scheduler  0/2 nodes are available: 2 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling., reject the pod secretflow-task-20240228161259-single-psi-0 even after PostFilter.

（点对点模型也有此问题）

**Comment by gshilei** [comment]
> 文档地址：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.5.0b0/deployment/deploy_master_lite_cn 系统为3台ubuntu系统
> 
> 查看master容器中pods日志 Warning FailedScheduling 50s kuscia-scheduler 0/2 nodes are available: failed to get task resource bob/ for pod. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod., can not find related task resource. Warning FailedScheduling 48s kuscia-scheduler 0/2 nodes are available: 2 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling., reject the pod secretflow-task-20240228161259-single-psi-0 even after PostFilter.
> 
> Warning FailedScheduling 3m1s kuscia-scheduler 0/2 nodes are available: failed to get task resource alice/ for pod. preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod., can not find related task resource. Warning FailedScheduling 2m59s kuscia-scheduler 0/2 nodes are available: 2 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling., reject the pod secretflow-task-20240228161259-single-psi-0 even after PostFilter.
> 
> （点对点模型也有此问题）

Hi @linushio, 从你的上述日志中看到，"2 node(s) had untolerated taint {node.kubernetes.io/disk-pressure: }"。
猜测是你的机器磁盘不足导致调度问题。

1.. 查看kuscia master节点容器中node列表：kubectl get node 
2. 查看每个node上是否有污点：kubectl describe node xxxx | grep Taints
3. 可以使用 df -h 查看磁盘空间使用率。建议 Use 不要超过百分之90，否则会被kuscia k3s认为有磁盘压力
