### ISSUE TITLE
多机部署点对点集群是否支持secretpad

### ISSUE THREAD

**Issue by linushio** [secretflow/kuscia#238]
部署文档：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.5.0b0/deployment/deploy_p2p_cn
中心化集群部署文档下方有secretpad部署操作，但是点对点没有，是不支持吗？如果支持应该如何部署

**Comment by Chrisdehe** [comment]
支持的，请参考[Secretpad P2P方式部署文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad/latest/dbd670doqfio1puq)

**Comment by linushio** [comment]
好的，感谢
