### ISSUE TITLE
验证 Kuscia《如何运行一个secertflow任务》教程文档，包括文档流程和 create_example_job.sh 脚本

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#24]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
-  任务名称：验证 Kuscia《[如何运行一个secertflow任务](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/tutorial/run_secretflow_cn)》教程文档，包括验证文档流程和create_example_job.sh 脚本，保证文档和脚本的正确性
-  技术方向：Kuscia/docs
-  任务难度：热身🌟

## 详细要求
请基于 Kuscia master 验证上述文档的具体操作流程和脚本是否能够成功运行。在部署脚本的同时，也欢迎对文档内容通顺（语句与错别字）进行修正。

## 能力要求
-  了解基本 git 操作
-  熟悉 Docker、shell
-  对 Kuscia 有一定了解，成功运行过部分示例文档

## 操作指引
-  若脚本能够正常运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若脚本执行过程中报错，关联本 ISSUE 并提交修复后的代码提交至 https://github.com/secretflow/kuscia/tree/main/scripts/user
-  若文档存在错误，关联本 ISSUE 并将修复后的文档提交至 https://github.com/secretflow/kuscia/blob/main/docs/tutorial/run_secretflow_cn.md
   - 注意在提交修复后的文档之前，请先使用 make docs 命令验证文档正确性

**Comment by Ame-ReIori** [comment]
Ame-ReIori Give it to me

**Comment by Ame-ReIori** [comment]
## 文档流程验证

按照《[如何运行一个secretflow任务](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/tutorial/run_secretflow_cn)》给出的流程进行操作，使用容器中数据文件配置KusciaJob，验证成功，给出master节点中PSI任务的status、PSI任务的输出以及运行后`/home/kuscia/var/storage/data/`的目录结构，截图如下所示。

<img width="1440" alt="image" src="https://github.com/secretflow/kuscia/assets/52520144/941e4e0d-a440-4191-b9eb-e782172dd4b5">

## 脚本验证

在`scripts`目录下创建`templates`和`user`文件夹，在`templates`中添加`job.2pc_balanced_psi.yaml`和`task_input_config.2pc_balanced_psi.json`文件；在`user`文件夹中添加`create_example_job.sh
`脚本文件，并添加执行权限。进入`user`目录，使用`./create_example_job.sh`，成功运行，截图如下所示。

<img width="718" alt="image" src="https://github.com/secretflow/kuscia/assets/52520144/5495c606-4cbf-43d1-8c8b-882718896ecb">

**Comment by Eiji911** [comment]
LGTM

**Comment by Candicepan** [comment]
> Ame-ReIori Give it to me

Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx#) to complete the registration.
If you are an overseas developer, you can complete the event registration by sending an email. Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com) Title：[OSCP] sign up + GitHub ID Text：Name + GitHub ID + Current school/Company + Major/Technical fields
