### ISSUE TITLE
提交Kuscia示例中的job-best-effort-linear任务，执行失败

### ISSUE THREAD

**Issue by ForinMH** [secretflow/kuscia#242]
terminationLog: 'container[secretflow] terminated state reason "Error", message:
        "mp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal\" --node-name=job-psi-0-global.bob.svc`
        (via SIGTERM)\n2024-03-06 03:06:29,714\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet
        --raylet_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --store_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --object_manager_port=31370 --min_worker_port=10002 --max_worker_port=19999
        --node_manager_port=31369 --node_ip_address=job-psi-0-global.bob.svc --maximum_startup_concurrency=16
        --static_resource_list=node:job-psi-0-global.bob.svc,1.0,CPU,32,memory,19970496923,object_store_memory,9985248460
        \"--python_worker_command=/usr/local/bin/python /usr/local/lib/python3.8/site-packages/ray/_private/workers/setup_worker.py
        /usr/local/lib/python3.8/site-packages/ray/_private/workers/default_worker.py
        --node-ip-address=job-psi-0-global.bob.svc --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER
        --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --redis-address=None --storage=None --temp-dir=/tmp/ray --metrics-agent-port=56188
        --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=job-psi-0-global.bob.svc:31368
        RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER --redis-password=5241590000000000\"
        --java_worker_command= --cpp_worker_command= --native_library_path=/usr/local/lib/python3.8/site-packages/ray/cpp/lib
        --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --log_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --resource_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --metrics-agent-port=56188 --metrics_export_port=64567 --object_store_memory=9985248460
        --plasma_directory=/tmp --ray-debugger-external=0 --gcs-address=job-psi-0-global.bob.svc:31368
        --session-name=session_2024-03-06_03-06-25_973275_66 \"--agent_command=/usr/local/bin/python
        -u /usr/local/lib/python3.8/site-packages/ray/dashboard/agent.py --node-ip-address=job-psi-0-global.bob.svc
        --metrics-export-port=64567 --dashboard-agent-port=56188 --listen-port=52365
        --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --runtime-env-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal\" --node-name=job-psi-0-global.bob.svc`
        (via SIGTERM)\n2024-03-06 03:06:29,717\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/bin/python -u /usr/local/lib/python3.8/site-packages/ray/_private/log_monitor.py
        --logs-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --gcs-address=job-psi-0-global.bob.svc:31368
        --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` (via SIGTERM)\n2024-03-06
        03:06:29,719\tVINFO scripts.py:1023 -- Send termination request to `/usr/local/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet
        --raylet_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --store_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --object_manager_port=31370 --min_worker_port=10002 --max_worker_port=19999
        --node_manager_port=31369 --node_ip_address=job-psi-0-global.bob.svc --maximum_startup_concurrency=16
        --static_resource_list=node:job-psi-0-global.bob.svc,1.0,CPU,32,memory,19970496923,object_store_memory,9985248460
        \"--python_worker_command=/usr/local/bin/python /usr/local/lib/python3.8/site-packages/ray/_private/workers/setup_worker.py
        /usr/local/lib/python3.8/site-packages/ray/_private/workers/default_worker.py
        --node-ip-address=job-psi-0-global.bob.svc --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER
        --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --redis-address=None --storage=None --temp-dir=/tmp/ray --metrics-agent-port=56188
        --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=job-psi-0-global.bob.svc:31368
        RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER --redis-password=5241590000000000\"
        --java_worker_command= --cpp_worker_command= --native_library_path=/usr/local/lib/python3.8/site-packages/ray/cpp/lib
        --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --log_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --resource_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --metrics-agent-port=56188 --metrics_export_port=64567 --object_store_memory=9985248460
        --plasma_directory=/tmp --ray-debugger-external=0 --gcs-address=job-psi-0-global.bob.svc:31368
        --session-name=session_2024-03-06_03-06-25_973275_66 \"--agent_command=/usr/local/bin/python
        -u /usr/local/lib/python3.8/site-packages/ray/dashboard/agent.py --node-ip-address=job-psi-0-global.bob.svc
        --metrics-export-port=64567 --dashboard-agent-port=56188 --listen-port=52365
        --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --runtime-env-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal\" --node-name=job-psi-0-global.bob.svc`
        (via SIGTERM)\n2024-03-06 03:06:29,719\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/bin/python -u /usr/local/lib/python3.8/site-packages/ray/dashboard/agent.py
        --node-ip-address=job-psi-0-global.bob.svc --metrics-export-port=64567 --dashboard-agent-port=56188
        --listen-port=52365 --node-manager-port=31369 --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --runtime-env-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal --agent-id 1059961393`
        (via SIGTERM)\n2024-03-06 03:06:29,720\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/bin/python /usr/local/lib/python3.8/site-packages/ray/dashboard/dashboard.py
        --host=localhost --port=8265 --port-retries=0 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs
        --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66 --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --gcs-address=job-psi-0-global.bob.svc:31368
        --minimal --modules-to-load=UsageStatsHead` (via SIGTERM)\n2024-03-06 03:06:29,721\tINFO
        scripts.py:1051 -- 1/7 stopped.\r2024-03-06 03:06:29,813\tINFO scripts.py:1051
        -- 2/7 stopped.\r2024-03-06 03:06:29,813\tINFO scripts.py:1051 -- 3/7 stopped.\r2024-03-06
        03:06:29,985\tINFO scripts.py:1051 -- 4/7 stopped.\r2024-03-06 03:06:29,986\tINFO
        scripts.py:1051 -- 5/7 stopped.\r2024-03-06 03:06:29,986\tINFO scripts.py:1051
        -- 6/7 stopped.\r2024-03-06 03:06:30,318\tINFO scripts.py:1051 -- 7/7 stopped.\r2024-03-06
        03:06:30,318\tSUCC scripts.py:1063 -- Stopped all 7 Ray processes.\n"'

**Comment by Chrisdehe** [comment]
排查下：
1. kuscia版本
2. 将这两个日志也贴出：/home/kuscia/var/logs/k3s.log、/home/kuscia/var/logs/kuscia.log （如果找不到可以通过find / -iname 'k3s.log'查找 ）

**Comment by ForinMH** [comment]
Kuscia使用的0.5.0b0，secretflow使用的1.3.0b0
[
[kuscia.log](https://github.com/secretflow/kuscia/files/14505012/kuscia.log)
](url)

**Comment by ForinMH** [comment]
[k3s.zip](https://github.com/secretflow/kuscia/files/14505035/k3s.zip)

**Comment by Chrisdehe** [comment]
好的，你是什么p2p还是中心化呢，辛苦按照这个文档中的排查方法贴出需要的信息哈
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.5.0b0/reference/troubleshoot/runjobfailed

**Comment by ForinMH** [comment]
kubectl get kt job-psi -o yaml

apiVersion: kuscia.secretflow/v1alpha1
kind: KusciaTask
metadata:
  creationTimestamp: "2024-03-06T03:06:20Z"
  generation: 1
  labels:
    kuscia.secretflow/controller: kuscia-job
    kuscia.secretflow/job-id: job-best-effort-linear
    kuscia.secretflow/self-cluster-as-initiator: "true"
    kuscia.secretflow/task-alias: job-psi
  name: job-psi
  ownerReferences:
  - apiVersion: kuscia.secretflow/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KusciaJob
    name: job-best-effort-linear
    uid: f43b59ba-b3eb-40a9-a1c0-5005ff0702c3
  resourceVersion: "13058"
  uid: de81971b-19d0-405c-bca4-ee2d88cceae7
spec:
  initiator: alice
  parties:
  - appImageRef: secretflow-image
    domainID: alice
    template:
      spec: {}
  - appImageRef: secretflow-image
    domainID: bob
    template:
      spec: {}
  scheduleConfig: {}
  taskInputConfig: '{"sf_datasource_config":{"alice":{"id":"default-data-source"},"bob":{"id":"default-data-source"}},"sf_cluster_desc":{"parties":["alice","bob"],"devices":[{"name":"spu","type":"spu","parties":["alice","bob"],"config":"{\"runtime_config\":{\"protocol\":\"REF2K\",\"field\":\"FM64\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"},{"name":"heu","type":"heu","parties":["alice","bob"],"config":"{\"mode\":
    \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"}],"ray_fed_config":{"cross_silo_comm_backend":"brpc_link"}},"sf_node_eval_param":{"domain":"preprocessing","name":"psi","version":"0.0.1","attr_paths":["input/receiver_input/key","input/sender_input/key","protocol","precheck_input","bucket_size","curve_type"],"attrs":[{"ss":["id1"]},{"ss":["id2"]},{"s":"ECDH_PSI_2PC"},{"b":true},{"i64":"1048576"},{"s":"CURVE_FOURQ"}]},"sf_input_ids":["alice-table","bob-table"],"sf_output_ids":["psi-output"],"sf_output_uris":["psi-output.csv"]}'
status:
  allocatedPorts:
  - domainID: alice
    namedPort:
      job-psi-0/client-server: 23997
      job-psi-0/fed: 23999
      job-psi-0/global: 24000
      job-psi-0/node-manager: 24001
      job-psi-0/object-manager: 24002
      job-psi-0/spu: 23998
  - domainID: bob
    namedPort:
      job-psi-0/client-server: 31365
      job-psi-0/fed: 31367
      job-psi-0/global: 31368
      job-psi-0/node-manager: 31369
      job-psi-0/object-manager: 31370
      job-psi-0/spu: 31366
  completionTime: "2024-03-06T03:06:31Z"
  conditions:
  - lastTransitionTime: "2024-03-06T03:06:20Z"
    status: "True"
    type: ResourceCreated
  - lastTransitionTime: "2024-03-06T03:06:23Z"
    status: "True"
    type: Running
  - lastTransitionTime: "2024-03-06T03:06:31Z"
    status: "False"
    type: Success
  lastReconcileTime: "2024-03-06T03:06:31Z"
  message: The remaining no-failed party task counts 1 are less than the threshold
    2 that meets the conditions for task success. pending party[], running party[alice],
    successful party[], failed party[bob]
  partyTaskStatus:
  - domainID: alice
    phase: Failed
  - domainID: bob
    phase: Failed
  phase: Failed
  podStatuses:
    alice/job-psi-0:
      createTime: "2024-03-06T03:06:20Z"
      namespace: alice
      nodeName: root-kuscia-lite-alice
      podName: job-psi-0
      podPhase: Failed
      readyTime: "2024-03-06T03:06:23Z"
      startTime: "2024-03-06T03:06:22Z"
    bob/job-psi-0:
      createTime: "2024-03-06T03:06:20Z"
      namespace: bob
      nodeName: root-kuscia-lite-bob
      podName: job-psi-0
      podPhase: Failed
      readyTime: "2024-03-06T03:06:23Z"
      reason: Error
      startTime: "2024-03-06T03:06:22Z"
      terminationLog: 'container[secretflow] terminated state reason "Error", message:
        "mp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal\" --node-name=job-psi-0-global.bob.svc`
        (via SIGTERM)\n2024-03-06 03:06:29,714\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet
        --raylet_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --store_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --object_manager_port=31370 --min_worker_port=10002 --max_worker_port=19999
        --node_manager_port=31369 --node_ip_address=job-psi-0-global.bob.svc --maximum_startup_concurrency=16
        --static_resource_list=node:job-psi-0-global.bob.svc,1.0,CPU,32,memory,19970496923,object_store_memory,9985248460
        \"--python_worker_command=/usr/local/bin/python /usr/local/lib/python3.8/site-packages/ray/_private/workers/setup_worker.py
        /usr/local/lib/python3.8/site-packages/ray/_private/workers/default_worker.py
        --node-ip-address=job-psi-0-global.bob.svc --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER
        --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --redis-address=None --storage=None --temp-dir=/tmp/ray --metrics-agent-port=56188
        --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=job-psi-0-global.bob.svc:31368
        RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER --redis-password=5241590000000000\"
        --java_worker_command= --cpp_worker_command= --native_library_path=/usr/local/lib/python3.8/site-packages/ray/cpp/lib
        --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --log_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --resource_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --metrics-agent-port=56188 --metrics_export_port=64567 --object_store_memory=9985248460
        --plasma_directory=/tmp --ray-debugger-external=0 --gcs-address=job-psi-0-global.bob.svc:31368
        --session-name=session_2024-03-06_03-06-25_973275_66 \"--agent_command=/usr/local/bin/python
        -u /usr/local/lib/python3.8/site-packages/ray/dashboard/agent.py --node-ip-address=job-psi-0-global.bob.svc
        --metrics-export-port=64567 --dashboard-agent-port=56188 --listen-port=52365
        --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --runtime-env-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal\" --node-name=job-psi-0-global.bob.svc`
        (via SIGTERM)\n2024-03-06 03:06:29,717\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/bin/python -u /usr/local/lib/python3.8/site-packages/ray/_private/log_monitor.py
        --logs-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --gcs-address=job-psi-0-global.bob.svc:31368
        --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5` (via SIGTERM)\n2024-03-06
        03:06:29,719\tVINFO scripts.py:1023 -- Send termination request to `/usr/local/lib/python3.8/site-packages/ray/core/src/ray/raylet/raylet
        --raylet_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --store_socket_name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --object_manager_port=31370 --min_worker_port=10002 --max_worker_port=19999
        --node_manager_port=31369 --node_ip_address=job-psi-0-global.bob.svc --maximum_startup_concurrency=16
        --static_resource_list=node:job-psi-0-global.bob.svc,1.0,CPU,32,memory,19970496923,object_store_memory,9985248460
        \"--python_worker_command=/usr/local/bin/python /usr/local/lib/python3.8/site-packages/ray/_private/workers/setup_worker.py
        /usr/local/lib/python3.8/site-packages/ray/_private/workers/default_worker.py
        --node-ip-address=job-psi-0-global.bob.svc --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER
        --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --redis-address=None --storage=None --temp-dir=/tmp/ray --metrics-agent-port=56188
        --logging-rotate-bytes=536870912 --logging-rotate-backup-count=5 --gcs-address=job-psi-0-global.bob.svc:31368
        RAY_WORKER_DYNAMIC_OPTION_PLACEHOLDER --redis-password=5241590000000000\"
        --java_worker_command= --cpp_worker_command= --native_library_path=/usr/local/lib/python3.8/site-packages/ray/cpp/lib
        --temp_dir=/tmp/ray --session_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --log_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --resource_dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --metrics-agent-port=56188 --metrics_export_port=64567 --object_store_memory=9985248460
        --plasma_directory=/tmp --ray-debugger-external=0 --gcs-address=job-psi-0-global.bob.svc:31368
        --session-name=session_2024-03-06_03-06-25_973275_66 \"--agent_command=/usr/local/bin/python
        -u /usr/local/lib/python3.8/site-packages/ray/dashboard/agent.py --node-ip-address=job-psi-0-global.bob.svc
        --metrics-export-port=64567 --dashboard-agent-port=56188 --listen-port=52365
        --node-manager-port=RAY_NODE_MANAGER_PORT_PLACEHOLDER --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --runtime-env-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal\" --node-name=job-psi-0-global.bob.svc`
        (via SIGTERM)\n2024-03-06 03:06:29,719\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/bin/python -u /usr/local/lib/python3.8/site-packages/ray/dashboard/agent.py
        --node-ip-address=job-psi-0-global.bob.svc --metrics-export-port=64567 --dashboard-agent-port=56188
        --listen-port=52365 --node-manager-port=31369 --object-store-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/plasma_store
        --raylet-name=/tmp/ray/session_2024-03-06_03-06-25_973275_66/sockets/raylet
        --temp-dir=/tmp/ray --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66
        --runtime-env-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/runtime_resources
        --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --session-name=session_2024-03-06_03-06-25_973275_66
        --gcs-address=job-psi-0-global.bob.svc:31368 --minimal --agent-id 1059961393`
        (via SIGTERM)\n2024-03-06 03:06:29,720\tVINFO scripts.py:1023 -- Send termination
        request to `/usr/local/bin/python /usr/local/lib/python3.8/site-packages/ray/dashboard/dashboard.py
        --host=localhost --port=8265 --port-retries=0 --temp-dir=/tmp/ray --log-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66/logs
        --session-dir=/tmp/ray/session_2024-03-06_03-06-25_973275_66 --logging-rotate-bytes=536870912
        --logging-rotate-backup-count=5 --gcs-address=job-psi-0-global.bob.svc:31368
        --minimal --modules-to-load=UsageStatsHead` (via SIGTERM)\n2024-03-06 03:06:29,721\tINFO
        scripts.py:1051 -- 1/7 stopped.\r2024-03-06 03:06:29,813\tINFO scripts.py:1051
        -- 2/7 stopped.\r2024-03-06 03:06:29,813\tINFO scripts.py:1051 -- 3/7 stopped.\r2024-03-06
        03:06:29,985\tINFO scripts.py:1051 -- 4/7 stopped.\r2024-03-06 03:06:29,986\tINFO
        scripts.py:1051 -- 5/7 stopped.\r2024-03-06 03:06:29,986\tINFO scripts.py:1051
        -- 6/7 stopped.\r2024-03-06 03:06:30,318\tINFO scripts.py:1051 -- 7/7 stopped.\r2024-03-06
        03:06:30,318\tSUCC scripts.py:1063 -- Stopped all 7 Ray processes.\n"'
  serviceStatuses:
    alice/job-psi-0-fed:
      createTime: "2024-03-06T03:06:20Z"
      namespace: alice
      portName: fed
      portNumber: 23999
      readyTime: "2024-03-06T03:06:23Z"
      scope: Cluster
      serviceName: job-psi-0-fed
    alice/job-psi-0-global:
      createTime: "2024-03-06T03:06:20Z"
      namespace: alice
      portName: global
      portNumber: 24000
      readyTime: "2024-03-06T03:06:23Z"
      scope: Domain
      serviceName: job-psi-0-global
    alice/job-psi-0-spu:
      createTime: "2024-03-06T03:06:20Z"
      namespace: alice
      portName: spu
      portNumber: 23998
      readyTime: "2024-03-06T03:06:23Z"
      scope: Cluster
      serviceName: job-psi-0-spu
    bob/job-psi-0-fed:
      createTime: "2024-03-06T03:06:20Z"
      namespace: bob
      portName: fed
      portNumber: 31367
      readyTime: "2024-03-06T03:06:23Z"
      scope: Cluster
      serviceName: job-psi-0-fed
    bob/job-psi-0-global:
      createTime: "2024-03-06T03:06:20Z"
      namespace: bob
      portName: global
      portNumber: 31368
      readyTime: "2024-03-06T03:06:23Z"
      scope: Domain
      serviceName: job-psi-0-global
    bob/job-psi-0-spu:
      createTime: "2024-03-06T03:06:20Z"
      namespace: bob
      portName: spu
      portNumber: 31366
      readyTime: "2024-03-06T03:06:23Z"
      scope: Cluster
      serviceName: job-psi-0-spu
  startTime: "2024-03-06T03:06:20Z"

**Comment by ForinMH** [comment]
pod的日志
![image](https://github.com/secretflow/kuscia/assets/162400717/f0081f8b-b742-4e6f-849a-274cee435733)

**Comment by gshilei** [comment]
> Kuscia使用的0.5.0b0，secretflow使用的1.3.0b0 [ [kuscia.log](https://github.com/secretflow/kuscia/files/14505012/kuscia.log) ](url)

使用的 kuscia 版本和 sf 版本不匹配，匹配的sf版本为 "1.3.0.dev20231120"。对应的sf版本可以在 kuscia镜像自带的 standalone.sh 中查看。
命令为：grep -nr "SF_IMAGE" start_standalone.sh

**Comment by ForinMH** [comment]
> > Kuscia使用的0.5.0b0，secretflow使用的1.3.0b0 [ [kuscia.log](https://github.com/secretflow/kuscia/files/14505012/kuscia.log) ](url)
> 
> 使用的 kuscia 版本和 sf 版本不匹配，匹配的sf版本为 "1.3.0.dev20231120"。对应的sf版本可以在 kuscia镜像自带的 standalone.sh 中查看。 命令为：grep -nr "SF_IMAGE" start_standalone.sh

谢谢，现在可以跑起任务了，之前在另外一个环境用的1.3.0b0部署的可以使用，以为这边也可以。

**Comment by gshilei** [comment]
> > > Kuscia使用的0.5.0b0，secretflow使用的1.3.0b0 [ [kuscia.log](https://github.com/secretflow/kuscia/files/14505012/kuscia.log) ](url)
> > 
> > 
> > 使用的 kuscia 版本和 sf 版本不匹配，匹配的sf版本为 "1.3.0.dev20231120"。对应的sf版本可以在 kuscia镜像自带的 standalone.sh 中查看。 命令为：grep -nr "SF_IMAGE" start_standalone.sh
> 
> 谢谢，现在可以跑起任务了，之前在另外一个环境用的1.3.0b0部署的可以使用，以为这边也可以。

嗯，一般情况下， kuscia 镜像中的示例job的描述跟兼容的sf版本相对应。因为 sf 一直在迭代，所以不同的 sf 版本，可能组件描述会不一样。导致你遇到的这种情况。 

未来我们会维护一个 kuscia 版本和兼容的 sf 版本对应列表。
