### ISSUE TITLE
两个数据集做数据求交之后，如果id列名相同报错

### ISSUE THREAD

**Issue by ruhengChen** [secretflow/kuscia#245]
alice数据
id1
1
2
3
4
5

bob数据
id1,col2
1,4
2,5
3,32
4,12

隐私求交之后，做全表统计时报错       assert col not in unique_cols, f\"col {col} duplicate in multiple devices\"
![image](https://github.com/secretflow/kuscia/assets/20870282/b3199ff3-3d60-4993-8770-7b67cab9f1ce)

**Comment by zimu-yuxi** [comment]
列名不可以相同，可以改下数据表头，例如id1,id2

**Comment by Chrisdehe** [comment]
先关闭了 有问题reopen
