### ISSUE TITLE
二分类评估报错

### ISSUE THREAD

**Issue by ruhengChen** [secretflow/kuscia#246]
![image](https://github.com/secretflow/kuscia/assets/20870282/9d0548e4-1d10-4151-9cfd-82bb96a75215)

![image](https://github.com/secretflow/kuscia/assets/20870282/7355179f-8a77-4817-b536-a9b2474fc79a)
如图所示，样本表里面是有y标签的，但是报错 AttributeError: unknown cols {'y'} in col_selects
标签值不填也会报错

**Comment by Chrisdehe** [comment]
好的 我们正在查看

**Comment by Chrisdehe** [comment]
请问你的secretpad、kuscia、secretflow版本多少？

**Comment by ruhengChen** [comment]
secretpad:v0.3.0a2-25-gdfba7aab-20240111155241-dfba7a

kuscia-anolis:ACI-20231225-144440-d530e47

secretflow/teeapps-sim-ubuntu20.04           0.1.0b0.dev20231128

**Comment by ruhengChen** [comment]
SecretPad  安装包 部署的p2p 模式

**Comment by YanZhuangz** [comment]
可以看下组件的配置情况：在二分类评估的上游组件，可以看看选择标签列，以及保存标签列的开关，只有在开关打开的时候才会向下游传递。

**Comment by ruhengChen** [comment]
![2024-03-14 16 18 31](https://github.com/secretflow/kuscia/assets/20870282/f5794e56-c4fa-4d19-9e06-401ce67fd0ae)
目前确实没有保存标签列，但是二分类评估的上游 - 随机分割组件 应该是有标签列的， 预测组件提供了 预测值这列 

如果我开启保存标签列，会报错
```
Traceback (most recent call last):
  File \"/usr/local/lib/python3.8/site-packages/secretflow/device/device/spu.py\", line 190, in __del__
    actor.del_share.remote(self.shares_name[i])
  File \"/usr/local/lib/python3.8/site-packages/fed/_private/fed_actor.py\", line 108, in remote
    return self._fed_call_holder.internal_remote(*args, **kwargs)
  File \"/usr/local/lib/python3.8/site-packages/fed/_private/fed_call_holder.py\", line 74, in internal_remote
    ray_obj_ref = self._submit_ray_task_func(resolved_args, resolved_kwargs)
  File \"/usr/local/lib/python3.8/site-packages/fed/_private/fed_actor.py\", line 116, in _execute_impl
    return self._fed_actor_handle._execute_remote_method(
  File \"/usr/local/lib/python3.8/site-packages/fed/_private/fed_actor.py\", line 79, in _execute_remote_method
    ray_object_ref = self._actor_handle._actor_method_call(
  File \"/usr/local/lib/python3.8/site-packages/ray/actor.py\", line 1172, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
AttributeError: 'Worker' object has no attribute 'core_worker'
```
![2024-03-14 16 20 44](https://github.com/secretflow/kuscia/assets/20870282/1f745ca2-89bb-4d93-b40c-be129840cafa)

**Comment by ruhengChen** [comment]
特征过滤组件是把y标签过滤了，如果不加特征过滤，会报错
AssertionError: w shape is mismatch to x, w.shape[0]=44 and num_feat=44


![2024-03-14 16 29 51](https://github.com/secretflow/kuscia/assets/20870282/88597eb0-cd22-4fff-9b54-f9e124ddd0fd)

![2024-03-14 16 30 07](https://github.com/secretflow/kuscia/assets/20870282/ea66d865-7070-417d-8b3f-f5b0329cc17a)

**Comment by YanZhuangz** [comment]
逻辑回归训练中是有特征列和标签，在标签中按你的上下文来看是需要选择或者填入`y`，这个看下是否有配置。如果没有配置需要修改下，然后可以从逻辑回归训练这里重新跑任务。

**Comment by ruhengChen** [comment]
![2024-03-14 17 11 25](https://github.com/secretflow/kuscia/assets/20870282/75a9365a-3dfd-4bd8-bec8-529b3f188c93)
已经设置成y了的

**Comment by Chrisdehe** [comment]
辛苦将数据文件贴一下，我们做个复现

**Comment by ruhengChen** [comment]
[alice.csv](https://github.com/secretflow/kuscia/files/14609346/alice.csv)
[bob.csv](https://github.com/secretflow/kuscia/files/14609349/bob.csv)

**Comment by Chrisdehe** [comment]
好的，我们排期复现一下。

**Comment by Chrisdehe** [comment]
@ruhengChen 复现过程较多，为了避免不必要时间浪费，辛苦添加隐语技术支持（secretflow02）沟通，之后有技术问题也可以通过技术支持one by one直接解决。
