### ISSUE TITLE
Kuscia 集成引擎 Metrics

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#247]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

### 任务介绍
- 任务名称：Kuscia 集成引擎 Metrics
- 方向：Kuscia/功能开发
- 任务难度：困难🌟🌟🌟
- 期望完成时间：7-8 周

### 任务描述
kuscia上会同时运行多个引擎，同时每个引擎进程生命周期不同，会导致暴露的metrics端口不停的变化，不方便Prometheus等工具采集引擎监控指标；通过kuscia来统一采集引擎的metrics，再统一在一个端口中暴露采集的metrics，这样外部监控系统采集kuscia上运行的引擎监控项时，只需要使用固定的端口即可完成所有指标的采集。

### 详细要求
1. 提供一份操作文档;
2. 提交说明：
- 请先准备你的设计思路方案，并在 ISSUE 下评论提交方案;
- 经过 Reviewer 确认设计思路方案后再根据确认后的方案，进行相关的功能开发;
- 完成开发后，关联该 ISSUE 并提交代码至 [https://github.com/secretflow/kuscia/](https://github.com/secretflow/kuscia/);
- 代码规范：[https://github.com/uber-go/guide/blob/master/style.md](https://github.com/uber-go/guide/blob/master/style.md);

### 能力要求
- 了解Kuscia 原理
- 熟悉 golang

### 操作说明
Kuscia 开发参考：[https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_c](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by tonywu6** [comment]
tonywu6 Give it to me

**Comment by zhuiguang49** [comment]
give it to me

**Comment by zhuiguang49** [comment]
# Kuscia集成引擎Metrics 初步方案
## 基本思路
在kuscia集成引擎中，应用的pod通过k8s label暴露其metrics端点，公布监控接口，Agent发现这些端点并将信息传递给MetricExporter，后者负责将这些指标端点整合并提供给监控系统，以便后续进行数据抓取和后续分析。

## 关键环节
1.**指标暴露**：应用开发者在pods中通过label暴露指标声明metrics端点，使得Agent能够动态识别并追踪这些端点<br>
2.**Agent信息收集**：Agent监控pods变化，使用“list-watch”机制自动发现带有metrics标签的pods，并解析标签来获取指标暴露的信息<br>
3.**MetricExporter数据聚合与转发**：MetricExporter从Agent获取指标暴露的Pods的动态信息（哪些pod暴露了指标以及这些指标的IP地址和端口信息），不直接收集指标数据，而是聚合Pods指标端点的信息然后提供给监控系统。<br>

## 实现步骤

1.**指标暴露**：通过appImage中的metricsProbe字段，设置path和port，自动添加Pod的Label

2.**AppImage配置更新**：修改应用的AppImage的配置，添加metricsProbe字段，供Agent填充动态发现的metrics端点信息

>metricsProbe代码如下

	metricsProbe: #增加metricsProbe 配置
		path: /metrics #应用中用于暴露指标的端点
		port: 9100 #暴露指标的端口，假设它是9100
	initialDelaySeconds: 5 #用于容器启动多久之后开始第一次探测

3.**Agent动态发现**：Agent实施“list-watch”机制来监控Pod的状态和label变化，动态发现和记录metrics端点的地址

4.**MetricExporter数据聚合**：复用metricexporter.go文件中的代码实现Metricexporter的功能，定期从Agent获取最新的metrics端点列表。而metricsexporter接受到监控系统的请求，从pods收集数据并且返回给监控系统。

5.**Prometheus自动发现**：配置Prometheus使用k8s的label进行Pods的自动服务发现，使得Prometheus能够自动地发现这些指标。
