### ISSUE TITLE
make build时报错

### ISSUE THREAD

**Issue by LindaHu0701** [secretflow/kuscia#255]
2024年3月14日时，可以正常build；今天再次尝试，报如下错误，请问是否是最近版本更新的原因？
![1](https://github.com/secretflow/kuscia/assets/37866628/d0d61d49-fbf9-4b92-a0ed-c9510cb583e6)

**Comment by LeeTheByRiver** [comment]
用最新的代码build没有复现这个问题，可以自查一下，看是否有过本地代码或者golang的变更。

**Comment by LindaHu0701** [comment]
忘记说了，我用的是0.3.0b0这个版本

**Comment by LeeTheByRiver** [comment]
0.3.0b0发布很久了，不会被后续变更影响的。清理本地代码，重新拉取，编译试试

**Comment by LindaHu0701** [comment]
好的谢谢
