### ISSUE TITLE
kuscia算法组件

### ISSUE THREAD

**Issue by zhengyang16** [secretflow/kuscia#256]
请问是否有kuscia提供的算法组件清单？

以及应该如何在kuscia中运行自己的算法呢？

**Comment by Chrisdehe** [comment]
1. kuscia可调用SecretFlow 、TrustedFlow 、 Serving 在 Kuscia 上运行，可参考[secretflow组件列表](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/component/comp_list)
2. [开发kuscia](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/development)
3. 新鲜出炉的[隐语框架介绍](https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l)，可供参考

**Comment by Chrisdehe** [comment]
最新版本、咨讯等更多的技术交流可以添加技术支持微信（secretflow02）

**Comment by zhengyang16** [comment]
[开发kuscia](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.6.0b0/development)好像没有提及怎么在kuscia中自己开发算法？或者说我们目前有[secretflow组件列表](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.4.0b0/component/comp_list)之外的任务想要使用kuscia运行，想要自己实现，这是可以的吗？

**Comment by zhengyang16** [comment]
有【自定义模块】的相关文档可以参考吗？

**Comment by wenkesong-li** [comment]
暂时还没有这一块的文档建设，可以先自己try一下~

**Comment by yushiqie** [comment]
> 有【自定义模块】的相关文档可以参考吗？

可以根据 https://www.secretflow.org.cn/zh-CN/docs/kuscia/main/development/register_custom_image 注册自定义的应用镜像
