### ISSUE TITLE
use secretpad in p2p mode: occur error: domainroute.kuscia.secretflow "alice-bob" not found

### ISSUE THREAD

**Issue by tututt** [secretflow/kuscia#257]
start alice node:
`sh install.sh p2p -n alice -s 8081 -g 10001 -k 20001 -p 30001 -c ./p2p/alice`
start bob node:
`sh install.sh p2p -n bob -s 8082 -g 10002 -k 20002 -p 30002 -c ./p2p/bob`
when i add node, node status is unused, in kuscia server, occur error:
`ERROR controller/handshake.go:413 DestReplyHandshake for [alice-bob] failed, detail-> domainRoute [alice-bob] get error in dest domain [bob]: domainroute.kuscia.secretflow "alice-bob" not found`

**Comment by Chrisdehe** [comment]
一台电脑安装两个节点需保证两个节点名称/路径/端口均不同
你执行了两条节点名称都为bob的脚本

**Comment by tututt** [comment]
> 一台电脑安装两个节点需保证两个节点名称/路径/端口均不同 你执行了两条节点名称都为bob的脚本

请再看一下，我创建节点的时候没有写错，一个是alice，一个是bob

**Comment by tututt** [comment]
> 一台电脑安装两个节点需保证两个节点名称/路径/端口均不同 你执行了两条节点名称都为bob的脚本

找到问题了，需要互现添加合作节点才可以
