### ISSUE TITLE
验证 Kuscia 《如何运行一个 FATE 作业》教程文档，包括文档流程和 FATE 脚本

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#26]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
-  任务名称：验证 Kuscia 《[如何运行一个 FATE 作业](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/tutorial/run_fate_cn)》教程文档，包括文档流程和 FATE 脚本
-  技术方向：Kuscia/docs
-  任务难度：热身🌟

## 详细要求
请基于 Kuscia master 验证上述文档的具体操作流程和脚本是否能够成功运行。在部署脚本的同时，也欢迎对文档内容通顺（语句与错别字）进行修正。

## 能力要求
-  了解基本 git 操作
-  熟悉 Docker、shell
-  对 Kuscia、FATE 有一定了解

## 操作指引
-  若脚本能够正常运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若脚本执行过程中报错，关联本 ISSUE 并提交修复后的代码提交至 https://github.com/secretflow/kuscia/tree/main/thirdparty/fate
-  若文档存在错误，关联本 ISSUE 并将修复后的文档提交至 https://github.com/secretflow/kuscia/blob/main/docs/tutorial/run_fate_cn.md
   - 注意在提交修复后的文档之前，请先使用 make docs 命令验证文档正确性

**Comment by cs1317** [comment]
cs1317 Give it to me

**Comment by Candicepan** [comment]
> cs1317 Give it to me

Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx# ) to complete the registration.

If you are an overseas developer, you can complete the event registration by sending an email.
Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com)
Title：[OSCP] sign up + GitHub ID
Text：Name + GitHub ID + Current school/Company + Major/Technical fields

**Comment by cs1317** [comment]
先吐槽一下：FATE作业严重依赖内存和磁盘空间。
下载Kuscia源码：git clone https://github.com/secretflow/kuscia.git
准备节点:参考快速入门 或 https://github.com/secretflow/kuscia/issues/23
构建镜像:
![image](https://github.com/secretflow/kuscia/assets/50541363/18ddd3e8-29e0-445f-9575-d1a09c73ff3d)
![image](https://github.com/secretflow/kuscia/assets/50541363/1386c480-ccdb-44b9-80db-96ceb5012655)

**Comment by cs1317** [comment]
# 部署FATE: P2P模式：
![image](https://github.com/secretflow/kuscia/assets/50541363/05d83e79-2307-446d-b9b6-be9115bf31ce)
![image](https://github.com/secretflow/kuscia/assets/50541363/7eeb291e-4c81-49ed-91fa-1f08911d9638)
查看 FATE 部署日志
tail -f fate_cluster_install_1.11.1_release/allInone/logs/deploy-host.log
![image](https://github.com/secretflow/kuscia/assets/50541363/9cb038c4-54ca-44d8-9462-65b89aa61a62)
![image](https://github.com/secretflow/kuscia/assets/50541363/8be38abe-0d91-4619-af35-16373f833940)
![image](https://github.com/secretflow/kuscia/assets/50541363/46586df0-729d-4ae3-9486-1cf335985db5)

**Comment by cs1317** [comment]
#运行示例 FATE 作业
但是作业执行失败
![image](https://github.com/secretflow/kuscia/assets/50541363/8841de52-ed14-45a4-b6cc-b3d53b70a3bb)

**Comment by cs1317** [comment]
# 中心化组网模式 构建镜像
下载Kuscia源码：git clone https://github.com/secretflow/kuscia.git
准备节点:参考快速入门 或 https://github.com/secretflow/kuscia/issues/23
**make deploy-image**
 实在太长了，只截取最后成功的部分
![image](https://github.com/secretflow/kuscia/assets/50541363/82243e93-fb57-41e9-804d-ffb81c1faa7a)

**make fate-adaptor-app-image**
![image](https://github.com/secretflow/kuscia/assets/50541363/6ae888cd-b12f-401a-91b5-10f87d74fb6a)
![image](https://github.com/secretflow/kuscia/assets/50541363/15bc2c7a-c2a3-4307-aa1b-a74bb7f53da2)
![image](https://github.com/secretflow/kuscia/assets/50541363/a8ac1b0f-9179-46d7-aa7e-deab6749c2e1)

**Comment by cs1317** [comment]
# 中心化组网模式 部署FATE
![image](https://github.com/secretflow/kuscia/assets/50541363/97947ca1-2a5d-4d2b-972d-9989328a4b2c)
部署失败，已提交issue: https://github.com/secretflow/kuscia/issues/51

**Comment by gshilei** [comment]
Hi @cs1317，建议参考文档[FAQ](https://github.com/secretflow/kuscia/blob/main/docs/reference/faq_cn.md)
排查下Fate运行失败问题。
有条件的话，把当前部署的容器删除了，重新根据文档教程，一步一步走下去，确保不遗漏教程中的命令，看走到哪步开始出现异常。
停止容器和删除容器命令:
docker stop {container-name}
docker rm {container-name}

**Comment by cs1317** [comment]
用P2P模式重试了，中间步骤没有报错，但发现：
scripts/user/create_example_job.sh 是success的
而scripts/templates/fate/lr_job.sh  每次都failed
![image](https://github.com/secretflow/kuscia/assets/50541363/495e8903-5551-4cfb-bb2e-df57db09f43e)

**Comment by gshilei** [comment]
请检查下fate-alice容器是否就绪，参考文档[FAQ](https://github.com/secretflow/kuscia/blob/main/docs/reference/faq_cn.md)
![image](https://github.com/secretflow/kuscia/assets/136570416/e940dd59-6162-4a6d-a8ce-a28ba101afb2)

**Comment by cs1317** [comment]
> #P2P模式运行示例 FATE 作业 但是作业执行失败 ![image](https://user-images.githubusercontent.com/50541363/257246246-8841de52-ed14-45a4-b6cc-b3d53b70a3bb.png)
之前使用vmware的虚拟机搭建的，换成wsl之后，p2p模式运行fate的lr作业成功
![image](https://github.com/secretflow/kuscia/assets/50541363/14752710-8c37-4e57-9e6c-eb98d014d4fe)

**Comment by cs1317** [comment]
# 中心化组网模式 部署FATE
![image](https://github.com/secretflow/kuscia/assets/50541363/5f5cbea0-9358-4ba9-9016-431989d03e5e)

**Comment by cs1317** [comment]
# 中心化装模式  运行示例 FATE 作业
![image](https://github.com/secretflow/kuscia/assets/50541363/d8be4731-07ec-4d0f-8b03-4c77fffa7413)

**Comment by cs1317** [comment]
# 我在使用WSL运行FATE作业遇到以下问题
### 1.部分脚本文件(.sh文件)使用应该是在windows下写的，windows换行符与wsl(相当于ubuntu)**换行符不一致**
解决方法:
    (1)下载dos2unix : sudo apt install dos2unix 
    (2)使用dos2unix重写脚本文件: dos2unix xxx.sh
 ### 2.wsl构建 FATE 部署镜像make deploy-image,报"("语法错误(syntax error）
解决方法:修改thirdparty/fate/Makefile的第57行，将sh ./hack/build.sh改为bash ./hack/build.sh
### 3.wsl构建 AppImage 镜像make fate-adaptor-app-image，报错：
![Q39ZaToScr](https://github.com/secretflow/kuscia/assets/50541363/88e12524-4c81-4ad6-8bc7-3d6ab1d18fda)
解决方法:参考 https://blog.csdn.net/qq_42546635/article/details/129202394
    （1)把docker desktop卸载
      (2)windows命令行执行  mklink /J "C:\Program Files\Docker" "D:\Docker"
      (3)重装docker desktop
### 4.wsl中想要使用docker,必须安装docker desktop

**Comment by longshan-ant** [comment]
> # 我在使用WSL运行FATE作业遇到以下问题
> ### 1.部分脚本文件(.sh文件)使用应该是在windows下写的，windows换行符与wsl(相当于ubuntu)**换行符不一致**
> 解决方法: (1)下载dos2unix : sudo apt-get install dos2unix (2)使用dos2unix重写脚本文件: dos2unix xxx.sh
> 
> ### 2.wsl构建 FATE 部署镜像make deploy-image,报"("语法错误(syntax error）
> 解决方法:修改thirdparty/fate/Makefile的第57行，将sh ./hack/build.sh改为bash ./hack/build.sh
> 
> ### 3.wsl构建 AppImage 镜像make fate-adaptor-app-image，报错：
> ![Q39ZaToScr](https://user-images.githubusercontent.com/50541363/257756331-88e12524-4c81-4ad6-8bc7-3d6ab1d18fda.jpg) 解决方法:参考 https://blog.csdn.net/qq_42546635/article/details/129202394 （1)把docker desktop卸载 (2)windows命令行执行 mklink /J "C:\Program Files\Docker" "D:\Docker" (3)重装docker desktop
> 
> ### 4.wsl中想要使用docker,必须安装docker desktop
> 参考https://blog.csdn.net/qq_35492227/article/details/131222425

非常感谢，请针对1,2问题进行一下代码修复，并提交PR； 针对3,4问题，请帮忙修改[文档](https://github.com/secretflow/kuscia/blob/main/docs/tutorial/run_fate_cn.md) ，在文档开头标准使用WSL的注意事项，并提交PR。另外遇到的其他问题也可以补充到文档中。

**Comment by Mingbo-Lee** [comment]
Hello, @cs1317 ,确认一下,  关于你提到的
> 1.部分脚本文件(.sh文件)使用应该是在windows下写的，windows换行符与wsl(相当于ubuntu)换行符不一致

这部分脚本文件，是git clone 下载来的吗？或者直接下载解压缩，是怎么得到的？
如果是在Windows下进行git clone 下来的，还是在WSL上进行git clone下来的?

**Comment by cs1317** [comment]
WSL里进行的git clone

**Comment by Mingbo-Lee** [comment]
> WSL里进行的git clone

好的，谢谢回答，我没有问题了。

**Comment by cs1317** [comment]
@longshan-ant 部分内容在我提交PR前已经被修复了，就不重复提交PR了，其他部分已提交PR：

https://github.com/secretflow/kuscia/pull/63
