### ISSUE TITLE
关于如何使用secretpad训练好的模型，通过外部api调用预测服务（serving）的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/kuscia#269]
这个是我训练好的模型
![image](https://github.com/secretflow/kuscia/assets/42713276/31f0c95f-b152-47a4-9280-d69fcc86fa2e)
这个是我使用curl调用的结果
![image](https://github.com/secretflow/kuscia/assets/42713276/1c4f3de9-ede9-4bf2-b557-65e06da66815)
1.我想问下能否使用api调用到curl的结果，因为我部署了serving,可以通过apifox来请求Serving的结果（基于example的测试模型），但是直接使用api请求基于pad发布的模型我不清楚如何请求。
2.是有方法可以将pad的模型下载下来之后，放在部署好的Serving服务中，修改配置文件，才能通过外部api请求预测结果么？

**Comment by UniqueMarvin** [comment]
hi,  @Handikang  您的问题是想了解 如何在 kuscia容器外部通过http请求访问 预测服务么？
如果是的话，需要在部署kuscia时将 容器内部80端口暴露到 宿主机上指定的端口， 你现在拿到的版本默认是没有将 80端口暴露出来的，我们 0422 发布的版本会 默认暴露这个端口。

**Comment by Handikang** [comment]
好的，谢谢你，我明白了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月11日(周四) 中午11:26
收件人: ***@***.***&gt;;
抄送: "Han ***@***.******@***.***&gt;;
主题: Re: [secretflow/kuscia] 关于如何使用secretpad训练好的模型，通过外部api调用预测服务（serving）的问题 (Issue #269)




 
hi,  @Handikang  您的问题是想了解 如何在 kuscia容器外部通过http请求访问 预测服务么？
 如果是的话，需要在部署kuscia时将 容器内部80端口暴露到 宿主机上指定的端口， 你现在拿到的版本默认是没有将 80端口暴露出来的，我们 0422 发布的版本会 默认暴露这个端口。

**Comment by john8628** [comment]
> hi, @Handikang 您的问题是想了解 如何在 kuscia容器外部通过http请求访问 预测服务么？ 如果是的话，需要在部署kuscia时将 容器内部80端口暴露到 宿主机上指定的端口， 你现在拿到的版本默认是没有将 80端口暴露出来的，我们 0422 发布的版本会 默认暴露这个端口。

1:如果kusia 同时支持在线和离线模型，kusia需要多大的配置，能够支持QPS>10左右，RT<100ms的时延？这边有相关的benchmarks数据吗？

2: 如果通过pad生成的在线模型，在新机器上重新部署在线模型，是否有相关的文档支持？

**Comment by gshilei** [comment]
@john8628 针对上面两个问题：
1. 当前还没有 benckmarks 数据。当前需要用户自己的数据量，本地观察资源使用情况，然后设置合理的kuscia配置。
2. 当前还不支持本地模型，多节点模型拷贝，未来会支持。

**Comment by john8628** [comment]
> @john8628 针对上面两个问题：
> 
> 1. 当前还没有 benckmarks 数据。当前需要用户自己的数据量，本地观察资源使用情况，然后设置合理的kuscia配置。
> 2. 当前还不支持本地模型，多节点模型拷贝，未来会支持。

感谢回复
1: 通过kusia  API直接部署在线模型，是不是只要增加port透出就能使用了啊？
2: 期待新功能的发布
