### ISSUE TITLE
验证 Kuscia 开发文档《构建命令》的构建步骤和脚本正确性

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#27]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
-  任务名称：验证 Kuscia 开发文档《[构建命令](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn#kuscia)》的构建步骤和脚本正确性
-  技术方向：Kuscia/docs
-  任务难度：热身🌟

## 详细要求
请基于 Kuscia master 验证上述文档的具体操作流程和脚本是否能够成功运行。在部署脚本的同时，也欢迎对文档内容通顺（语句与错别字）进行修正。
说明：不需要编译 Kuscia-Envoy，依赖默认的 Kuscia-Envoy 镜像即可。

## 能力要求
-  了解基本 git 操作
-  熟悉 Docker、shell
-  对 Kuscia 有一定了解，成功运行过部分示例文档

## 操作指引
-  若脚本能够正常运行，则在本 ISSUE 下回复【验证成功 + 代码成功验证截图证明】
- 若脚本执行过程中报错，关联本 ISSUE 并提交修复后的代码提交至 https://github.com/secretflow/kuscia
-  若文档存在错误，关联本 ISSUE 并将修复后的文档提交至 https://github.com/secretflow/kuscia/tree/main/docs/development 
   - 注意在提交修复后的文档之前，请先使用 make docs 命令验证文档正确性

**Comment by BeaCox** [comment]
BeaCox Give it to me

**Comment by Candicepan** [comment]
> BeaCox Give it to me

Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx#) to complete the registration.
If you are an overseas developer, you can complete the event registration by sending an email. Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com) Title：[OSCP] sign up + GitHub ID Text：Name + GitHub ID + Current school/Company + Major/Technical fields

**Comment by BeaCox** [comment]
> > BeaCox Give it to me
> 
> Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx#) to complete the registration. If you are an overseas developer, you can complete the event registration by sending an email. Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com) Title：[OSCP] sign up + GitHub ID Text：Name + GitHub ID + Current school/Company + Major/Technical fields

我已于昨日完成注册，后台没有收到数据吗？
I've completed the registration yesterday, did the backend not receive the data?

**Comment by Candicepan** [comment]
> > > BeaCox Give it to me
> > 
> > 
> > Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx#) to complete the registration. If you are an overseas developer, you can complete the event registration by sending an email. > Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com) > Title：[OSCP] sign up + GitHub ID > Text：Name + GitHub ID + Current school/Company + Major/Technical fields
> 
> 我已于昨日完成注册，后台没有收到数据吗？ I've completed the registration yesterday, did the backend not receive the data?

找到您的注册信息啦～sorry～您无需再次报名哈～

**Comment by BeaCox** [comment]
> > > > BeaCox Give it to me
> > > 
> > > 
> > > Remember to complete the registration first, please click [here](https://www.wjx.top/vm/QKio0dq.aspx#) to complete the registration. If you are an overseas developer, you can complete the event registration by sending an email. > > > Send an email to [secretflow-contact@service.alipay.com](mailto:secretflow-contact@service.alipay.com) > > > Title：[OSCP] sign up + GitHub ID > > > Text：Name + GitHub ID + Current school/Company + Major/Technical fields
> > 
> > 
> > 我已于昨日完成注册，后台没有收到数据吗？ I've completed the registration yesterday, did the backend not receive the data?
> 
> 找到您的注册信息啦～sorry～您无需再次报名哈～

收到，感谢！
