### ISSUE TITLE
runk模式创建serving

### ISSUE THREAD

**Issue by henrysun007** [secretflow/kuscia#291]
通过kuscia创建了一个serving，runk模式下，发现pod在k8s里面，但service在kuscia k3s里面，有什么办法，能够在k8s访问service？是否可以将service在k8s里面创建？

**Comment by zimu-yuxi** [comment]
没有很明白咱这个问题。是如何发起服务预测和部署吗？
关于如何部署serving服务和请求预测服务的可以参考[如何部署 SecretFlow-Serving](https://www.secretflow.org.cn/zh-CN/docs/serving/0.2.1b0/topics/deployment/deployment)和[使用 Kuscia 部署 Serving](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.7.0b0/tutorial/run_sf_serving_with_api_cn)

**Comment by UniqueMarvin** [comment]
> 通过kuscia创建了一个serving，runk模式下，发现pod在k8s里面，但service在kuscia k3s里面，有什么办法，能够在k8s访问service？是否可以将service在k8s里面创建？

runk 模式下 kuscia 不会在k8s中创建 service， 若要访问serving 进行预测需要 访问 kuscia 80端口且带上 Host header 类似：
--header 'Host: serving-glm-test-1-service.alice.svc:53508'

**Comment by henrysun007** [comment]
好的，多谢
