### ISSUE TITLE
secretflow-lite-anolis8：1.6.0b0 镜像未找到

### ISSUE THREAD

**Issue by gxcuit** [secretflow/kuscia#312]
Hi
用最新的0.8.0b0 部署的时候，用的是secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.6.0b0 版本；未在镜像仓库里找到该镜像

master里用的1.5.0b0  , 而0.8.0b0 tag 发布的确是1.6.0b0

p.s. 不知道为啥传不了截图，去dockerhub 看一下就知道
**另外，部署脚本里的kuscia.sh 和delopy.sh 有什么区别？**

**Comment by gshilei** [comment]
Hi @gxcuit 

当前secretflow-lite-anolis8:1.6.0b0准备发布中。如果为了体验，可以先参考main分支文档。
![image](https://github.com/secretflow/kuscia/assets/136570416/d96d180b-4311-4dd8-aced-1b86a037ce2e)

kuscia.sh 是我们最近统一的部署脚本，未来会替换以前快速入门中的./start_standalone.sh和deploy.sh

**Comment by wenkesong-li** [comment]
你好，目前kuscia的最新版本是0.7，0.8还没正式发布。
相关版本参考：

https://github.com/secretflow/secretpad/blob/main/README.zh-CN.md

**Comment by gxcuit** [comment]
> 你好，目前kuscia的最新版本是0.7，0.8还没正式发布。 相关版本参考：
> 
> https://github.com/secretflow/secretpad/blob/main/README.zh-CN.md

ok。Thanks，以后release note 和版本兼容情况 都在这？

**Comment by wenkesong-li** [comment]
> > 你好，目前kuscia的最新版本是0.7，0.8还没正式发布。 相关版本参考：
> > https://github.com/secretflow/secretpad/blob/main/README.zh-CN.md
> 
> ok。Thanks，以后release note 和版本兼容情况 都在这？

是的，以后版本对应情况都会写在这里，会随着版本的更新而更新~
