### ISSUE TITLE
关于kuscia的DominMesh接口中数据源配置的问题

### ISSUE THREAD

**Issue by Handikang** [secretflow/kuscia#315]
1.接口文档中如果type是table,是否只能支持从kuscia容器本地读取csv文件？
![image](https://github.com/secretflow/kuscia/assets/42713276/df6c3a01-ba1e-400e-8186-f8539eefab52)
2.SCQL中使用kuscia的datamesh作为数据源路由，是不是从数据源灵活性上讲，没有embed方式的路由灵活，支持的数据源多？
3.SCQL关于如何读取gflag.conf的配置这部分的代码是在哪部分，我想看一下这部分的逻辑？

**Comment by wenkesong-li** [comment]
你好，关于您的问题。
1：可以参考数据源配置。https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/apis/domaindatasource_cn
2和3看一下这个文档。https://www.secretflow.org.cn/zh-CN/docs/scql/0.7.0b1/topics/deployment/run-scql-on-kuscia

**Comment by Handikang** [comment]
1.好的，感谢，这块文档我看过了，我想知道这块在代码中是哪块？我理解是不是目前使用kuscia的datemesh接口只能识别到本地的csv?
2.使用kuscia部署scql的话使用datemesh接口是不是也只能使用csv的数据源?

**Comment by cho-chem** [comment]
Hi @Handikang 
1. Kuscia 的 DataMesh 创建数据源的接口理论上是不限制数据源类型的，对 Kuscia 来说只是存储了一个字符串（localfs,oss,mysql 等），引擎（例如 SCQL）是否支持对应的数据源要看引擎的实现。
2. 使用 kuscia部署scql 当前支持 localfs 和 oss 类型的数据源，数据格式都是 csv。
