### ISSUE TITLE
docker启动kuscia时，/home/kuscia/etc/conf/kuscia.yaml 映射的本地路径可以指定嘛

### ISSUE THREAD

**Issue by secretflowcode** [secretflow/kuscia#316]
### Issue Type

Others

### Deployment

docker

### Kuscia Version

kuscia 0.7.0b0

### OS Platform and Distribution

centos 7

### Docker version

Docker 20.10.8

### K8s version

1.26

### App Running type

secretflow

### App Running version

1.5.0b0

### Configuration file used to run kuscia.

```shell
"HostConfig": {
            "Binds": [
                "root-kuscia-autonomy-sp5-containerd:/home/kuscia/containerd",
                "/home/admin/secretflow-allinone-package/root-kuscia-autonomy-sp5/kuscia.yaml:/home/kuscia/etc/conf/kuscia.yaml",
                "/tmp:/tmp",
                "/root/kuscia/autonomy/data/sp5:/home/kuscia/var/storage/data",
                "/root/kuscia/autonomy/sp5:/home/kuscia/var/stdout"
            ],
```

### What happend and What you expected to happen.

```shell
当我使用k8s 的yaml文件去启动镜像的时候，需要提前将镜像映射的本地文件创建好，
容器中/home/kuscia/etc/conf/kuscia.yaml 映射的文件/home/admin/secretflow-allinone-package/root-kuscia-autonomy-sp5/kuscia.yaml为install安装路径，当我使用k8s 的yaml文件去启动镜像的时候，应该怎么设置呢？
有没有k8s 的配置文件？
```

### Kuscia log output.

```shell
无
```

**Comment by cho-chem** [comment]
你好，在 K8s 中部署 Kuscia 请参考 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/deployment/K8s_deployment_kuscia/K8s_p2p_cn，你需要把 kuscia.yaml 配置成 ConfigMap 再挂载到 Kuscia 容器中
