### ISSUE TITLE
对secretpad、Kuscia部署方式的疑惑

### ISSUE THREAD

**Issue by lifelong-creator** [secretflow/kuscia#317]
对于kuscia中的Agent支持runC、runP、runK三种运行时，分别在部署时特别指定。对于secretpad，secretpad其实也包含了kuscia模块，部署时会一同部署kuscia，但是在部署secretpad时并没有按照runC、runP、runK三种方式来区分部署。按照https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/fn9h9yqoievouz2a部署secretpad后，kuscia是工作在什么模式呢？

**Comment by wenkesong-li** [comment]
你好，mvp包中默认的kuscia启动模式是runC的。
关于三种模式的说明：
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/architecture_cn#agent

**Comment by lifelong-creator** [comment]
> 你好，mvp包中默认的kuscia启动模式是runC的。 关于三种模式的说明： https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/architecture_cn#agent

好的，如何修改其他模式呢？
另外再问下kuscia部署时内置了一个k3s吗？即kuscia的Master节点启动时也会启动k3s的控制面板，kuscia的工作节点启动时也会跟着启动k3s的工作节点？

**Comment by wenkesong-li** [comment]
关于如何修改启动模式参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/deployment/K8s_deployment_kuscia/deploy_with_runp_cn#runp

关于k3s说明：
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/architecture_cn#k3s
