### ISSUE TITLE
根据 kuscia-入门教程 快速开始的例子无法以中心化组网模式安装kuscia

### ISSUE THREAD

**Issue by JiaIcecream** [secretflow/kuscia#318]
### Issue Type

Bug

### Deployment

docker

### Kuscia Version

kuscia v0.8.0b0

### OS Platform and Distribution

ubuntu 20.04

### Docker version

25.0.1

### App Running type

secretflow

### App Running version

secretflow 1.5.0b0

### Configuration file used to run kuscia.

```shell
安装报错
```

### What happend and What you expected to happen.

```shell
根据教程https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/getting_started/quickstart_cn 在中心化组网模式中的执行完 ./kuscia.sh center  出现报错； 报错内容为：Error response from daemon: manifest for secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/secretflow-lite-anolis8:1.6.0b0 not found: manifest unknown: manifest unknown
```

### Kuscia log output.

```shell
安装时报错，并未有日志输出
```

**Comment by zimu-yuxi** [comment]
Hi @JiaIcecream ：
可以先参考下[此版本文档](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.7.0b0/getting_started/quickstart_cn)进行安装kuscia，secretflow1.6.0b0镜像暂时还未发布
[此处](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.7.0b0/getting_started/quickstart_cn#id6)可以先指定kuscia的tag:0.7.0b0

**Comment by gshilei** [comment]
Hi @JiaIcecream 

你可以参考[v0.8.0b0](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/getting_started/quickstart_cn)分支文档进行相关操作.

以下是文档中快速体验的教程:

```
1. 指定Kuscia_Image
 export KUSCIA_IMAGE=secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.8.0b0
2. 准备部署脚本kuscia.sh
 docker pull $KUSCIA_IMAGE && docker run --rm $KUSCIA_IMAGE cat /home/kuscia/scripts/deploy/kuscia.sh > kuscia.sh && chmod u+x kuscia.sh
3. 安装kuscia
./kuscia.sh center
 4. 创建并启动作业（两方 PSI 任务）。
 docker exec -it ${USER}-kuscia-master scripts/user/create_example_job.sh
5. 查看作业状态。
 docker exec -it ${USER}-kuscia-master kubectl get kj -n cross-domain

使用该分支文档中的教程时，请保证kuscia镜像的版本为secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.8.0b0
 ```

此外，因为secretflow还处于不断迭代的过程，所以组件的参数和版本在不同的secretflow版本之间存在差异。因此，针对这种情况，我们从 v0.8.0b0 版本开始，会逐渐对 Kuscia 的版本和 secretflow 版本进行管理。 直接体现是正式分支的 v0.8.0b0 文档中，我们使用的是具体的 Kuscia镜像版本，而不是latest版本。

**Comment by JiaIcecream** [comment]
感谢回复，昨天换了版本之后可以重新安装了；然后在运行kuscia的第二个教程了解kuscia也遇到了报错，查看了一下secretflow的psi的实现代码，发现示例中的kusciaJob中的taskInputConfig 中的sf_node_eval_param属性有些参数对不上；麻烦您这边检查一下并及时更新文档。

**Comment by gshilei** [comment]
> 感谢回复，昨天换了版本之后可以重新安装了；然后在运行kuscia的第二个教程了解kuscia也遇到了报错，查看了一下secretflow的psi的实现代码，发现示例中的kusciaJob中的taskInputConfig 中的sf_node_eval_param属性有些参数对不上；麻烦您这边检查一下并及时更新文档。

你好，上面提到的kuscia的第二个教程是指哪个？

另外是参考的kuscia [v0.8.0b0](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/getting_started/quickstart_cn) 分支文档跑的教程吗？

**Comment by JiaIcecream** [comment]
使用的是kuscia0.7.0b0 以及对应的文档，我提到的第二个教程是这个 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.7.0b0/getting_started/run_secretflow_cn ，在配置kusciaJob这个步骤时教程提供的 job-best-effort-linear.yaml，但是没办法成功运行起示例，查看了一下secretflow的psi的实现代码，发现示例中的kusciaJob中的taskInputConfig 中的sf_node_eval_param属性有些参数对不上； 此外我想问一下现在实现的算子，有详细的参数文档吗，例如对于psi这个组件来说 attr_paths这个参数它需要配置的参数有哪些，参数对应的含义是什么，哪些是可选的哪些是必选的，目前我没有在官网中找到这个文档，这对于想使用kusciaAPI去编写一个kusciaJob并运行有着较大的阻碍。如果有相关文档麻烦您能给个答复，非常感谢！

**Comment by JiaIcecream** [comment]
> > 使用的是kuscia0.7.0b0 以及对应的文档，我提到的第二个教程是这个 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.7.0b0/getting_started/run_secretflow_cn ，在配置kusciaJob这个步骤时教程提供的 job-best-effort-linear.yaml，但是没办法成功运行起示例，查看了一下secretflow的psi的实现代码，发现示例中的kusciaJob中的taskInputConfig 中的sf_node_eval_param属性有些参数对不上； 此外我想问一下现在实现的算子，有详细的参数文档吗，例如对于psi这个组件来说 attr_paths这个参数它需要配置的参数有哪些，参数对应的含义是什么，哪些是可选的哪些是必选的，目前我没有在官网中找到这个文档，这对于想使用kusciaAPI去编写一个kusciaJob并运行有着较大的阻碍。如果有相关文档麻烦您能给个答复，非常感谢！
> 
> 使用kuscia0.7.0b0及对应文档可能会有这个问题。从kuscia0.8.0b0开始，会做kuscia版本和secretflow版本管理。在kuscia0.8.0b0分支文档中，示例教程设置的KUSCIA_IMAGE为secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.8.0b0，而不是latest。因此，建议你使用kuscia0.8.0b0以及对应的分支文档进行体验。

主要当前按照kuscia0.8.0b0 文档去安装kuscia是安装不了的，在这个issue的前面部分，[zimu-yuxi](https://github.com/zimu-yuxi)建议我用0.7.0b0，他提到secretflow1.6.0b0镜像暂时还未发布；
另外，我上面提到的算子文档请问目前有规划发布吗，非常感谢。

**Comment by gshilei** [comment]
@JiaIcecream 
1. secretflow 1.6.0b0镜像昨天已发布，建议使用最新的版本。
2. 算子描述可以参考secretflow的官方文档。Kuscia文档中有相关说明和链接。
https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/concepts/kusciajob_cn#create-kuscia-job
![image](https://github.com/secretflow/kuscia/assets/136570416/e210858f-9776-4bca-9b9c-ceecce728a0c)

**Comment by JiaIcecream** [comment]
> @JiaIcecream
> 
> 1. secretflow 1.6.0b0镜像昨天已发布，建议使用最新的版本。
> 2. 算子描述可以参考secretflow的官方文档。Kuscia文档中有相关说明和链接。
>    https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.8.0b0/reference/concepts/kusciajob_cn#create-kuscia-job
>    ![image](https://private-user-images.githubusercontent.com/136570416/332748015-e210858f-9776-4bca-9b9c-ceecce728a0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MjYxOTQsIm5iZiI6MTcxNjQyNTg5NCwicGF0aCI6Ii8xMzY1NzA0MTYvMzMyNzQ4MDE1LWUyMTA4NThmLTk3NzYtNGJjYS05YjljLWNlZWNjZTcyOGEwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMDU4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzAzNTUwNDkwODY0YTgyN2Q4YTIwNTgyNWZmZDQzZDlkNzZlYzE0MzEwZmZjM2Q4YzE1NzI5ODc2ZmE4YTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hw1pvFxyOejhFrDF1Lp8xCg-D8rkIB0hHurB4fR7-c4)

非常感谢你的回复。
1. 我们将会改用最新的版本进行尝试。
2.  对于你在图片中展示的 secretflow 算子运行配置文档 我查看了一下，发现这个文档是对组件标准的介绍而不是具体组件的使用描述，例如对于psi这个组件，文档会描述其所需要配置的属性参数，参数对应的含义是什么，哪些参数是可选的，哪些参数是必选的。

**Comment by gshilei** [comment]
Hi @JiaIcecream 

针对 secretflow 算子具体组件的使用描述，建议到 secretflow repo下单独提一个issue，后续会有 secretflow 相关同学进行答复。
