### ISSUE TITLE
是否有kuscia job/task taskInputConfig 配置的详细说明？

### ISSUE THREAD

**Issue by gxcuit** [secretflow/kuscia#320]
Hi， 我在使用kuscia 和secretpad。 我看隐语已经内置提供了许多算子

尽管有[secretpad 算子的文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/latest/pf7woou4dzgc90ol)

 以及[ 以及secretflow的相关文档](https://www.secretflow.org.cn/zh-CN/docs/secretflow/v1.6.0b0/component/comp_list)

但我看文档貌似不是最新的？
例如kuscia 0.7.0b0 里，psi 是 0.0.4 的版本。 0.8.0b0里是0.0.5的版本。

哪里有相关版本的参考呢？

Thanks！

**Comment by wenkesong-li** [comment]
组件相关版本参考：https://github.com/secretflow/secretpad/blob/main/config/components/secretflow.json

**Comment by gxcuit** [comment]
> 组件相关版本参考：https://github.com/secretflow/secretpad/blob/main/config/components/secretflow.json

Thanks！
