### ISSUE TITLE
Kuscia controllers 新增 Gc-controller 实现

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#33]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）](https://github.com/orgs/secretflow/discussions/1181)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx#)进行哈～

## 任务介绍
- 任务名称：Kuscia controllers 新增 Gc-controller 实现
- 技术方向：任务调度、资源管理
- 任务难度：挑战🌟🌟🌟
- 任务期望完成时间：7-8 周

## 详细要求
在 Kuscia 中有很多 Resource，例如 KusciaJob, DomainData 等。随着时间的推移，积攒的历史 Resource 会消耗 Kuscia 的存储，因此需要新增 Kuscia Gc-controller 来定时的清理无用的 Resource 。
- 功能性：
  - 支持定时清理 KusciaJob Resource
  - 支持定时清理 DomainData Resource
- 准确性：
  - 保证满足特定规则的无用的 Resource 成功被清理
  - 保证正常使用的 Resource 不会被清理
- 提交说明：
  - 请先准备你的设计思路方案，并在 ISSUE 下评论提交方案
  - 经过 Reviewer 确认设计思路方案后再根据确认后的方案，进行相关的功能开发
  - 完成开发后，关联该 ISSUE 并提交代码至 https://github.com/secretflow/kuscia/tree/main/pkg/controller
- 代码规范：https://github.com/uber-go/guide/blob/master/style.md

## 能力要求
- 对 Kuscia 原理比较了解
- 熟悉 K8s，熟悉  K8s CRD 
- 熟悉 golang

## 参考内容
- [Kuscia controllers 参考实现](https://github.com/secretflow/kuscia/tree/main/pkg/controllers/kusciajob)
- [KusciaJob 概念参考](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/concepts/kusciajob_cn)
- [DomainData 概念参考](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/concepts/domaindata_cn)
- [Kusica 开发参考](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by igffccm** [comment]
Give it to me

**Comment by 2002ljy** [comment]
Hello~ I completed the task.

**Comment by igffccm** [comment]
Hello, I have completed the design proposal

**Comment by igffccm** [comment]
基本思路：
定期找出符合“无用”标准的KusciaJob和DomainData进行标记，按照更新时间的远近依次进行删除，检测是否删除成功，删除成功后将删除的KusciaJob和DomainData的名称和删除时间记录到数据表中（用户可以设置是否记录）。
相关参数：
DomainData：
vendor：表示 DomainData 的来源，仅用作标识，对于你手动创建的 DomainData，可以将其设置为manual，对于应用算法组件生成的表，由算法组件本身填充，secretflow算法组件会填充secretflow。
nodeStatuses[].lastTransitionTime：表示 Kuscia Agent 最近一次发生更新的时间。
NotReady：表示 Kusica Agent 状态异常
KusciaJob：
Cancelled: 任务被某一方取消，被取消的任务不可被再次执行。
completionTime：表示 KusciaJob 运行完成的时间戳。
lastReconcileTime：表示 KusciaJob 上次更新的时间戳。

思路：
1、定期（两周）读取列表，找出符合以下条件的进行标记：
对于DomainData：
Vendor类型为secretflow，	满足设定的可以被自动删除的最少时间（两周）。
对于KusciaJob：
满足设定的可以被自动删除的最少时间（两周）。
2、按照更新时间的远近依次进行删除。
3、检测是否删除成功，若失败进行二次删除（多次失败后对用户进行报错）。
4、删除成功后将删除的KusciaJob和DomainData的名称和删除时间记录到数据表中（用户可以设置是否记录）。
操作（后期以代码完成）：
1、	清理
清理DomainData	DomainData
删除这个 KusciaJob 和这个KusciaJob 创建的 KusciaTask。	kubectl delete kj {job-name} -n cross-domain
运行以下命令清理 Domain	kubectl delete domain alice
2、	检查
检查 DomainData 是否已被清理。	kubectl get domaindata alice-table -n alice
Error from server (NotFound): domaindatas.kuscia.secretflow "alice-table" not found

**Comment by 2002ljy** [comment]
我完成了设计方案的完善和编写代码实现GC功能😊
