### ISSUE TITLE
kuscia如何调用Trustedflow？

### ISSUE THREAD

**Issue by zzx-QDU** [secretflow/kuscia#334]
您好，文档中说kuscia可以调用trustedflow，但是没有说如何调用或是给出示例，请问有没有比较详细或者流程完整的介绍？

感谢帮助！

**Comment by zimu-yuxi** [comment]
是的，目前没有关于和trustedFlow文档和示例。请问有什么需求需要关注kuscia管理trustedflow呢？
如果只是想要体验一下，可以使用allinone包的中心化部署模式，会自动帮您部署一个模拟环境的tee节点。可以看下[这里的文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.6.1b0/center_deploy/method3)

**Comment by zzx-QDU** [comment]
我们想使用trustedflow开发产品，同时想用kuscia来进行任务调度。目前正处于一个学习摸索的阶段，secretpad的枢纽模式我们之前部署过，但是这个对应的是trustedflow的仿真模式，我们想使用的是sgx模式。

**Comment by pchyuan** [comment]
> 请问会出用Kuscia来调度trustedflow的sgx模式示例吗？

暂时还没有排上这个计划，如果您急切有需要，可以一起进一步交流下，看下怎么更好满足您场景的需求

**Comment by zzx-QDU** [comment]
感谢您的帮助，这个需求暂时不是很急，但从长远来看，我们还是会学习用Kuscia来调度Trustedflow的，目前我们还是处于一个学习阶段，如果遇到问题，会再来请教的。
