### ISSUE TITLE
如何查看kuscia版本？

### ISSUE THREAD

**Issue by gxcuit** [secretflow/kuscia#335]
Hi，我部署的kuscia 0.8.0b0，但容器内 kuscia -v 却是0.7.0 的版本，请问改以哪个为准呢？
![image](https://github.com/secretflow/kuscia/assets/18736196/924071b7-7d04-4d3e-862c-dd692f80bffa)
![image](https://github.com/secretflow/kuscia/assets/18736196/e7b270f8-811c-4ba1-9197-a6f219106cd0)

**Comment by wenkesong-li** [comment]
你好，这个地方可能有bug，已经反馈了。
以实际安装使用版本为准~

**Comment by gxcuit** [comment]
Thanks ! I'll close this issue
