### ISSUE TITLE
secretflow-allinone-package 部署secretpad和kuscia，当我自定义了secretflow镜像，是否需要修改kuscia镜像

### ISSUE THREAD

**Issue by secretflowcode** [secretflow/kuscia#336]
### Issue Type

Others

### Search for existing issues similar to yours

Yes

### Kuscia Version

kuscia 0.7.0b0

### Question Details

```shell
secretflow-allinone-package 中images 有secretpad和kuscia和secretflow，目前当我重新打包secretflow镜像后，kuscia镜像是否要重新打包
```

**Comment by pchyuan** [comment]
如果接口没有改，版本等没有改，原则上是不用的。您可以自行尝试一下，遇到问题可以继续提issue。
