### ISSUE TITLE
kuscia api 远端无法联通

### ISSUE THREAD

**Issue by ruhengChen** [secretflow/kuscia#350]
### Issue Type

Install/Deploy

### Search for existing issues similar to yours

Yes

### OS Platform and Distribution

Centos

### Kuscia Version

0.9.0b0

### Deployment

docker

### deployment Version

24.0.4

### App Running type

secretflow

### App Running version

1.6.0b0

### Configuration file used to run kuscia.

```shell
mode: autonomy
domainID: alice
domainKeyData: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdHdtNmo3YW9ibGEwc3dSYTBQWVFsYWkyVFdFbkJqbHQyTFhtUzV4Q3hxQWg0by9ICnVPQlpSaFhzM1ZybDc1eTVBbld6aUtwcnNDdlIwVW96Q1hDQjhKRGMxNXJ2cjhIYjhlNHV0cVZDVUtqeHpDTWIKVkZxK29FNmE0ckh1SUE3MUdYcDJyWGVhWFZyUi9xYWY0cFVXZ0lXN1hoajBwWDBzUWFxVXFGUllzNjg5N0YydgpQK212cGl5dEpwN2hUaHZUNDhLRFBjcXhIeHpBRDBGSmgxdWt6Z0J0SkJLVHJLQTFSOEVMKzQrSjh3NFFoYThZCjhwTTZtNy9uUEkwcXllOUdvQXBMcFNGZk5lUWJQbUgzck9hWm1Xek41a0cxdlNNTGJBS1R0bjBmdEh4T1A2RTAKR0NEbHJGMjVXMWhQSDdJZkFRQ2sxWlhsS1B3VTJ5M1BVSytYUlFJREFRQUJBb0lCQUcyOXdvSTUxS0JiRWZvbgpDVUF4MTkyekNxSTROb3FQMGlGVlpoODlML2dndUZBN1BsYkZCQ0YyTWM3Qm1nemduVGd4VTVRRUFZN2RwdTNoCm05bnovNlE1Wm45S1lKeXpFV2pyRWt6bHBtM3Y3UkVrbDFVckZ4SE1MeWJ0NFVTTlV6eVVaU1U2Q1c0aGJyaE0KTko1SUh2YXR0NW9DUW1RYU9YZWhpNEdsR0kyWjVqTmY3NSswbXhEeW5SSE51cGlDU3hoV0RsV0ZPbm9mc2gvbApaRGJqOUxUM2RFNVRMalA4SjhSZS9wWnA1SFNYWjJPNWxjSlVGdWJIZUwzTTVyeloyaHYxTHMwcWFYVTU2WDVJCjJHUDcxTXc4dTYzc1IrSjk5VlVyelNzMk9TbXBFUDVjaFZhUkpvcDZTV2hmaTF5Mi9WQjNkc29ZV3lVa0RqeEUKMVZWa29uMENnWUVBN2xiWmJSbDFXaitpZXRGSnV0dUNEeUZTT0pSTm1EVldCUjhEUFg2QTZ2OGkzWXNwRDZ5eApvNXFINkl5R2RCQmxSeXk5cHF4Q1QvVW1hNzNWSTZ3d2VWT2h2WDlSVU83alhqQmpJY25tNHpzZnBLeUJFWDRzClNZQnNxZTB5WEk5YUhRbUxOUzBXZHZZSWV6MFpTMk9FRXAyWSt4aUtYTStrMzlsV000RjAyME1DZ1lFQXhKbloKSzZFeEkwVHpKSU1RVmFLb1BCenlPYjBMSWwxSVNGQS9FQW9oV0tEbVpuU2VuU3hYNkY3U1JWbFdQczNPSTFWNwoyRHpIWktrMEF4RXM1S1ZvRkRlWTNEWEVWbU96SWIwVTN6S3ZMaElrYmNmQjBNajRESFBxRXVQc1pwNFpWWGpLCmp3b1FENVNTazdyQTV3Y1J2V2J3QmdqM0Y4ODVmUzRTdXRCS3B0Y0NnWUVBb0ZCR3UzMnVVK0FOdURMaU53L0QKTWM0bDhleS9MS3hqaWRwTVlhYWZySEdrMEFQMHdKaFdmRWRMTjM2ZVNaOWxvRFJWOUxCVmdsYlJXeE03TkYxegoxWWdOZU5zVXBTMnFQZ2FxQjJZNUtZcnhRK0RNaUNtb1BHQm50dnpYTFM4M1crUzVnREV0dFNMVW5hQ0JUUlpKCkZnUnZqQ1g3bTJZSDdwSFB5NkUrS3VVQ2dZQlZhdXFhTkN5ZlFFUExwMDRmaHM1RlgrWTJBOWFrbFpia0pFbGgKOUtUTVZ3d0RrOE9lVWpmWGMrc3p5ajdZaHA1N1o1YXBPcTcvSXl5LzhHUnE2eHF2UGdDaUhKSXpYcG5qbkwxRwp4RVNzWmFHQ09Qb1NkbDZmT25XR3c1UmdlV3hVWUdqUmdQTzljVFhHRGF2bU5JSVdvblRDaW42Z3o1NFFyMFhmCitNT1dmUUtCZ0ZUeDFVQVoycVAwUWxwSDdGOStzOTlIQms1bkwxU2JLYjVJY2d6MU9kUE9rOTBTaHZlcmlFdFoKWHdpVnlWdkNHZ0ZkcGtnbzBybDR5ZEQxWUphL2xGOTJXbm9WTVl2QU1QTEdCdGZRV0Z3M1FjYTZCbUhDSEhVdAo5Vm9jTWFKR08wNWNPUFRCVUZxdHZxYkl6aGtsaDRDYkdQTCtrQVA0aTBud2xDQmNzaHVFCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
logLevel: INFO
runtime: runc
runk:
  namespace: ""
  dnsServers: []
  kubeconfigFile: ""
capacity:
  cpu: ""
  memory: ""
  pods: ""
  storage: ""
reservedResources:
  cpu: ""
  memory: ""
image:
  pullPolicy: ""
  defaultRegistry: ""
  registries: []
datastoreEndpoint: ""
```

### What happend and What you expected to happen.

```shell
遇到了和https://github.com/secretflow/kuscia/issues/278 同样的问题，远端的ip不在证书列表内，请问哪个版本已经解决这个问题吗？
```

### Kuscia log output.

```shell
无
```

**Comment by zimu-yuxi** [comment]
> <img alt="2024-06-25 16 11 49@2x" width="1496" src="https://private-user-images.githubusercontent.com/20870282/342639343-78ae5526-9727-415f-bab0-2061c01b1ef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ4MDUsIm5iZiI6MTcyMDA4NDUwNSwicGF0aCI6Ii8yMDg3MDI4Mi8zNDI2MzkzNDMtNzhhZTU1MjYtOTcyNy00MTVmLWJhYjAtMjA2MWMwMWIxZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YWVlZTNjYzdiMTRiOGM0NTljNGQ4ZWViYWRhYjA3MzM2MzAzNmVjZmYzZjcxYzQ0ZjU5OGQ1MTBhYmUyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8S7KDV1hamXJLrBA-XOoHDeUG82B4KlLMHpqyTOiAjA">

kuscia.yaml修改protocol的值为notls

**Comment by ruhengChen** [comment]
> > <img alt="2024-06-25 16 11 49@2x" width="1496" src="https://private-user-images.githubusercontent.com/20870282/342639343-78ae5526-9727-415f-bab0-2061c01b1ef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwODQ4MDUsIm5iZiI6MTcyMDA4NDUwNSwicGF0aCI6Ii8yMDg3MDI4Mi8zNDI2MzkzNDMtNzhhZTU1MjYtOTcyNy00MTVmLWJhYjAtMjA2MWMwMWIxZWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA5MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YWVlZTNjYzdiMTRiOGM0NTljNGQ4ZWViYWRhYjA3MzM2MzAzNmVjZmYzZjcxYzQ0ZjU5OGQ1MTBhYmUyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8S7KDV1hamXJLrBA-XOoHDeUG82B4KlLMHpqyTOiAjA">
> 
> kuscia.yaml修改protocol的值为notls

这个方案试过了，但是这样相当于不需要证书访问了，治标不治本吧？
