### ISSUE TITLE
k8s点对点runp模式运行时，运行部署文档的测试作业时出现：SSL routines::wrong version number

### ISSUE THREAD

**Issue by PlanetAndMars** [secretflow/kuscia#360]
### Issue Type

Api Usage

### Search for existing issues similar to yours

No

### Kuscia Version

Kuscia 0.8.0b0

### Question Details

按照文档 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.9.0b0/deployment/K8s_deployment_kuscia/K8s_p2p_cn#alice  
运行测试数据时，
curl创建数据源，出现如下错误：
![image](https://github.com/secretflow/kuscia/assets/62392971/607c2fe4-c86c-43bc-ba2b-78c0be9f73a1)

**Comment by zimu-yuxi** [comment]
使用最新的kuscia镜像，0.9.0b0试下
