### ISSUE TITLE
Kusica是否可以启动多方的联邦学习任务

### ISSUE THREAD

**Issue by JiaIcecream** [secretflow/kuscia#364]
### Issue Type

Api Usage

### Search for existing issues similar to yours

Yes

### Kuscia Version

kuscia v0.8.0b0

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.9.0b0/reference/concepts/kusciajob_cn#create-kuscia-job

### Question Details

```shell
如题，我想知道使用kuscia是否可以编排一个多方联合训练的联邦学习任务，例如使用多方数据训练一个逻辑回归模型。如果可以的话是否能给出一个KusciaJob的例子，非常感谢。
```

**Comment by zimu-yuxi** [comment]
建议先通过secretflow先跑一下多方的联邦学习，然后将spu，ray等配置填充taskinputconfig，如果有问题，可以针对性的解决。感谢
