### ISSUE TITLE
Kuscia中心化模式部署后/scripts/deploy/register_app_image.sh文件自动删除

### ISSUE THREAD

**Issue by zhuiguang49** [secretflow/kuscia#367]
### Issue Type

Install/Deploy

### Search for existing issues similar to yours

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04.6 LTS

### Kuscia Version

kuscia v0.9.0b0

### Deployment

k8s

### deployment Version

k8s

### App Running type

secretflow

### App Running version

secretflow 1.6.0b0

### Configuration file used to run kuscia.

default

### What happend and What you expected to happen.

在编译镜像，通过`./kuscia.sh center`命令中心化模式部署kuscia后，/scripts/deploy/register_app_image.sh文件自动删除，导致更改kuscia源代码重新编译部署后出现报错：`OCI runtime exec failed: exec failed: unable to start container process: exec: "scripts/deploy/register_app_image.sh": stat scripts/deploy/register_app_image.sh: no such file or directory: unknown`，手动从kuscia仓库复制该文件后编译部署报错：`OCI runtime exec failed: exec failed: unable to start container process: exec: "scripts/deploy/register_app_image.sh": permission denied: unknown`

### Kuscia log output.

无法部署

**Comment by yushiqie** [comment]
0.9.0版本，请参照 https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.9.0b0/development/register_custom_image

**Comment by zhuiguang49** [comment]
好的谢谢
