### ISSUE TITLE
创建kuscia job的参数字段含义

### ISSUE THREAD

**Issue by wangzeyu135798** [secretflow/kuscia#369]
### Issue Type

Others

### Search for existing issues similar to yours

Yes

### Kuscia Version

kuscia0.6

### Question Details

```shell
{"sf_node_eval_param":{"inputs":[{"data_refs":[{"format":"csv","uri":"7099withLabel_50w_1095660995.csv","party":"testa"}],"meta":{"line_count":"-1","@type":"type.googleapis.com/secretflow.spec.v1.IndividualTable"},"type":"sf.table.individual"},{"data_refs":[{"format":"csv","uri":"5099withoutLabel_50w_1567254027.csv","party":"testc"}],"meta":{"line_count":"-1","@type":"type.googleapis.com/secretflow.spec.v1.IndividualTable"},"type":"sf.table.individual"}],"domain":"data_prep","name":"psi","attr_paths":["input/receiver_input/key","input/sender_input/key","protocol","disable_alignment","skip_duplicates_check","check_hash_digest","ecdh_curve"],"version":"0.0.2","attrs":[{"ss":["id1"],"is_na":false},{"ss":["id2"],"is_na":false},{"s":"PROTOCOL_RR22","is_na":false},{"is_na":true},{"is_na":true},{"is_na":true},{"s":"CURVE_FOURQ","is_na":false}]},"sf_output_uris":["cwzc-ghvbkbfv-node-3-output-0"],"sf_input_ids":["oqdwbdia","bofzluno"],"sf_datasource_config":{"testc":{"id":"default-data-source"},"testa":{"id":"default-data-source"}},"sf_cluster_desc":{"devices":[{"name":"spu","parties":["testc","testa"],"type":"spu","config":"{\"runtime_config\":{\"protocol\":\"SEMI2K\",\"field\":\"FM128\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"},{"name":"heu","parties":["testc","testa"],"type":"heu","config":"{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"}],"ray_fed_config":{"cross_silo_comm_backend":"brpc_link"},"parties":["testc","testa"]},"sf_output_ids":["cwzc-ghvbkbfv-node-3-output-0"]}
以上是通过secretpad创建一个kuscia job的具体参数，有几个字段含义不明确，想咨询一下：
1、sf_node_eval_param：inputs：data_refs：uri 此字段在secretpad sqlite数据库中哪个位置？
2、sf_node_eval_param：inputs：meta：line_count和@type这两个字段值是如何得出的，固定值么？
3、sf_node_eval_param：inputs：type 此字段值是固定值么？
4、sf_node_eval_param：domain 此字段是固定值么？
5、sf_node_eval_param：attr_paths 这个字段里面的内容是如何获取的，不同组件任务是不一样么？
6、sf_node_eval_param：version 这个字段是从数据库里面获取的么？对应什么的版本信息？
7、sf_node_eval_param：sf_input_ids 这个字段是在数据库什么位置？
```

**Comment by wangzeyu135798** [comment]
上面这个案例是隐私求交

**Comment by zimu-yuxi** [comment]
1.project_datatable看一下
2.固定值
3.代表不同的组件，组件不同，值不同
4.domain是你创建的计算方
5.组件页面配置
6.组件版本号，/config/components/secretflow.json

如果想要了解入参来源，建议可以本地部署secretpad源码，进行debug，会比较方便一点，参考[此文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.8.1b0/development/ru_in_idea_cn)

**Comment by PlanetAndMars** [comment]
> 1.project_datatable看一下 2.固定值 3.代表不同的组件，组件不同，值不同 4.domain是你创建的计算方 5.组件页面配置 6.组件版本号，/config/components/secretflow.json
> 
> 如果想要了解入参来源，建议可以本地部署secretpad源码，进行debug，会比较方便一点，参考[此文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.8.1b0/development/ru_in_idea_cn)

sf_node_eval_param.inputs 这个参数，什么时候需要什么时候不需要？
我创建了一个Job，抓到pad传递给KusciaAPI的请求参数，发现很多task中没有sf_node_eval_param.inputs这个参数，不清楚什么时候需要什么时候不需要

**Comment by zimu-yuxi** [comment]
> > 1.project_datatable看一下 2.固定值 3.代表不同的组件，组件不同，值不同 4.domain是你创建的计算方 5.组件页面配置 6.组件版本号，/config/components/secretflow.json
> > 如果想要了解入参来源，建议可以本地部署secretpad源码，进行debug，会比较方便一点，参考[此文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.8.1b0/development/ru_in_idea_cn)
> 
> sf_node_eval_param.inputs 这个参数，什么时候需要什么时候不需要？ 我创建了一个Job，抓到pad传递给KusciaAPI的请求参数，发现很多task中没有sf_node_eval_param.inputs这个参数，不清楚什么时候需要什么时候不需要

你可以看下kusciaapi的文档，在文档中是没有inputs参数的哈。这边给的是secretpad拉到的日志吗？

**Comment by PlanetAndMars** [comment]
> > > 1.project_datatable看一下 2.固定值 3.代表不同的组件，组件不同，值不同 4.domain是你创建的计算方 5.组件页面配置 6.组件版本号，/config/components/secretflow.json
> > > 如果想要了解入参来源，建议可以本地部署secretpad源码，进行debug，会比较方便一点，参考[此文档](https://www.secretflow.org.cn/zh-CN/docs/secretpad/v0.8.1b0/development/ru_in_idea_cn)
> > 
> > 
> > sf_node_eval_param.inputs 这个参数，什么时候需要什么时候不需要？ 我创建了一个Job，抓到pad传递给KusciaAPI的请求参数，发现很多task中没有sf_node_eval_param.inputs这个参数，不清楚什么时候需要什么时候不需要
> 
> 你可以看下kusciaapi的文档，在文档中是没有inputs参数的哈。这边给的是secretpad拉到的日志吗？

是的，抓到的secretpad给kusciaAPI的请求参数

**Comment by zimu-yuxi** [comment]
可以看下 org.secretflow.secretpad.service.graph.chain.JobRenderHandler#doHandler
在任务处理的时候set inputs参数~
