### ISSUE TITLE
Kuscia 统一数据源访问代理 DataProxy 支持通用数据源

### ISSUE THREAD

**Issue by Candicepan** [secretflow/kuscia#37]
> 此 ISSUE 为 [隐语开源共建计划（SecretFlow Open Source Contribution Plan，简称 SF OSCP）第二期](https://github.com/orgs/secretflow/discussions/741)任务 ISSUE，欢迎社区开发者参与共建～
> 若有感兴趣想要认领的任务，但还未报名，辛苦先完成[报名](https://www.wjx.top/vm/QKio0dq.aspx# )进行哈～

## 任务介绍
- 任务名称：Kuscia 统一数据源访问代理 DataProxy 支持通用数据源
- 技术方向：多数据源适配、存储
- 任务难度：进阶🌟🌟

## 详细要求
Kuscia 统一数据源访问代理 DataProxy 旨在为用户屏蔽异构数据源的差异，提供统一的读写接口；并支持文件上传下载的方式，将本地文件上传到 Remote 数据源，或将 Remote 数据源上的数据下载到本地文件系统。
欢迎社区开发者一起共建，支持更多的数据源类型。
-  功能性:期望优先支持除 OSS 之外的文件存储(对接 OSS 内部已认领)，例如 HDFS 等，实现读写、文件上传和下载接口。
- 提交说明：关联该 ISSUE 并提交代码至 https://github.com/secretflow/kuscia/tree/main/pkg
- 代码规范：https://github.com/uber-go/guide/blob/master/style.md

## 能力要求
- 了解基本 git 操作
- 对 Kuscia 有一定了解
- 了解 分布式文件存储
- 熟悉 Golang

## 操作说明
- 请在认领该 ISSUE 后，说明计划对接的数据源类型，请在 ISSUE 下评论提交方案，经过我们确认后进行开发。
- [Kuscia开发参考](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/development/build_kuscia_cn)

**Comment by happyhorse2** [comment]
happyhorse give it to me

**Comment by happyhorse2** [comment]
happyhorse2 give it to me

**Comment by Candicepan** [comment]
> happyhorse2 give it to me

hello～目前设计方案准备得如何了呢，按照规则需要尽快提交设计方案噢，不然该任务将被回收呢

**Comment by Eiji911** [comment]
这个暂时可以hold一下，等Kusica发布初版DataProxy，再按照接口扩展。

**Comment by Candicepan** [comment]
> happyhorse2

该任务关联 Kuscia 的一些功能，将在下一个版本中发布～目前该任务先行回收～这位小伙伴可以认领本次 OCSP 的其他任务哈～https://github.com/orgs/secretflow/discussions/741

欢迎小伙伴们在 Kuscia 新版本发布后再来认领哈～
