### ISSUE TITLE
创建serving服务，当采用OSS存储，涉及的accessKey、secretKey的安全问题

### ISSUE THREAD

**Issue by killomsc** [secretflow/kuscia#372]
### Issue Type

Api Usage

### Search for existing issues similar to yours

Yes

### Kuscia Version

0.6.0.bo

### Question Details

```shell
通过kuscia api创建serving服务，需要把所有参与方的party config的配置填入。当采用OSS或者minio存储的时候，需要把各方配置ossSourceMeta也要填入，包含了accessKey，secretKey。这里如何拿到合作方的AK/SK的信息，另外还有安全问题如何解决？
```

**Comment by zimu-yuxi** [comment]
目前serving暂时不支持使用OSS。OSS存储，AK/SK和安全问题内部正在优化中，敬请期待
