### ISSUE TITLE
PSI运行报错

### ISSUE THREAD

**Issue by ruhengChen** [secretflow/kuscia#379]
### Issue Type

Install/Deploy

### Search for existing issues similar to yours

Yes

### OS Platform and Distribution

Linux ecs-46f7 4.19.90-17.5.ky10.aarch64 #1 SMP Fri Aug 7 13:35:33 CST 2020 aarch64 aarch64 aarch64 GNU/Linux

### Kuscia Version

0.9.0b0

### Deployment

docker

### deployment Version

24.0.8

### App Running type

secretflow

### App Running version

1.7.0b0

### Configuration file used to run kuscia.

```shell
# alice
mode: autonomy
domainID: alice
domainKeyData: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBMVFvelMwbEFYM1JOM2xxV0QzZHJBcmN6V3c1dW5RdGhWcXJMMjAzTHU5Mml3RXVSCkRjZjJabWJGSXJwMGtxc0U1bWpMcXJRZSs1TXBSZnNwbmg3dU9mU2RUaWR5R09kbE9TNWhyS2NIZGxkWTc2Mk4KNnJmSHFCd2hEY05mcmZPU21TRG5Ld2VKU0o4bmRkOWZiTVo0WlZzVTVaUENNdDI0ekU3MjVYZU9CZjdpVm5SZApRQzllMHJyRlk4eUVneG8zckpuWnRVbTBDMllrcWNCSXRITFpIUjlDNmpsTmxxZ0tFT2VnN3dFbytWVFA4T2QxCjdHMWJyRFdoQ1kwUXRGZUxQSnFlM2NIVCtXZ1R6RnVOYXNPREwxcWJ6STZwZysxcS9LVEVoNXB4UDRoUEhhSHEKMGErTE03V2Q4RFVza2xQWUFHZTRmeHFEUXJ3djVIK040YWpoU3dJREFRQUJBb0lCQVFDY3RKOGNmdXBpREh3RwoxaDFSalNiaTNYMWlPbEIxSmx6WVVsUVhvYmIrSHI3THNnb2wxL1BRU1VJekZISVJQTWtpN3V6NVNQc05WS2RrCmVhYVlUK291S1ZmWW1EMWVRajk3K3prUHRlRlFWRm53RzNxcnI3bW1WK0tjYkIwaUtHdXFSY0NsTHlyMWgxU1EKYU5tWmVyZ3UzZnVXRDhVbWcxK2VzV3I5U1o3bm1zZlhPMTNBb3J3VE1KZkllcy9rK090NERJTVBpMXk2aktDNAp1bTZGVm9Wa04vNjQ4dUxaUHZjbHlCRTVoQnlQT3ZxOGszZTB4YnRQQldud2hhWWVhTlU1VnJIWXhkSTQvdkMyCkt1VXROcXJUOHkveGZ1Y3lNNmZzVDZtZk9PbFNjSzRTTENUS0JQTWdDSzViR0IrVFhKb3MrY3lpcURZYlVjcmEKS2FQVnQrbVpBb0dCQU5tVCtnZElRVnZyN2FFb3g0eUFkZTVhV3lpMCttd2JoOVpjeE92OXIrZ0grQVF1WDZ4WQpDcmE2TnJlUHRlWThXUjJMTlVkQTdPdWtXNElKNmVYQUlFeGE0dHFNUlhzL0hHQ0FrU2pBN2VkQjQzZTVSM093CjFlTmFjQ2RSU1dsYSt1eGF3SWZCR2hXc0p5WXFZblVIQmEwcnozVVVsdGN2TDh4aWxXRXFjck05QW9HQkFQcXAKRVB6UHhtUkk0RXZndW5DdzU1RTJ6UGttQURwOGN4WTRmUFRsYkkyVkd5b0VvYlR2V2g2ejlseUZRd1M4c3VtSgpyd2w2elg4eTFnMnlrYnJ3MHB3TlpZWHgzaXVLenhlM083eThnYmhRV3k2YmloTldqQkVMNlhDakU1K1lFa21KCm1IeE43UThwRUUrb3NBSitOdFNXQVpPYlFuWVpLdGlFalNtWFd3OG5Bb0dCQU5aZ3JBRVMyM3N6cWU2Wm5JdysKWW5SWVNPdUI3aUFvdkIybFNFM3hwcW1yZUY2K1Jud3NQMW90Zmc0OUpnL1ZORVVjellFSVlxZ0hTRGFIaUJOYwp5ellRY3VhOVFSU2ZhVmxZTkM2QWNhZmpUcm0vTDd5NDV2WGRQUll3VEhIbk44YzczK21paFE0SGtvZFRTYkZmCkd1TzJmL0V2T1RTS2hNRVAvWGxBZHNWTkFvR0FJYnZuSVY4RklESCtuYmVjMzlXdkZJZi9oZmhyUjNQQU9WbFkKMTh5WWsyVmh4b0hoRVd5MUFEVFFEeHVRTFc4SDFRNUdsRXdHby91L2V4QnhOR3Q4ckt2UTRmbnZJSVVKNGZNegpBdStMdGJaNnp3YjN5aXAzcDBPbkl4V1Bhb2NZenZUSnBORUgrbVpZWDZBZ0wvVzBnMSs4enBTeW1ScEIvZW00CjVjUU02VGtDZ1lBV2pOMllRaERrL3FveU5EU1FveDl2MlZUNFdBNnY1V3ZlMk93aFloY1UrRXgvZ1B0TjQwYkoKaGNFZlFZZjJLRGsxZk5YZm0ydFoyVVBWOU1LTlBwK3lKVE9VclZVR0t1RjR2TFkrL0VRcEdEU2ZKR2JZdGFIcQpzZEFjeXJyRWtKS2VybFRNMVh3SDVvWDFsOWpEVko1ZC9lR3B2WGtPc2psWmVxQjhYWVBHR3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
logLevel: INFO
protocol: mtls
runtime: runc
runk:
  namespace: ""
  dnsServers: []
  kubeconfigFile: ""
capacity:
  cpu: ""
  memory: ""
  pods: ""
  storage: ""
reservedResources:
  cpu: ""
  memory: ""
image:
  pullPolicy: ""
  defaultRegistry: ""
  registries: []
datastoreEndpoint: ""

#bob
mode: autonomy
domainID: bob
domainKeyData: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBM0xHUlpEQVcxSlJtd2VwZjBKWWtQSitSWWhRTm9LSzNESmNHR0dWTFUxZHNkM3U4ClNsbTIyby94R0Q3RGJlVThwWkpkdGNlTkdVWjlSamlvSTVkL2tGcVlqS25kTnBWbWRHelBtRFhoMmJhcXBkQVUKaldFOXMzWTg0N1BqYXZZWDBhMnZyTk5WQUNVVUY4bHhKazAvQzRCQ2t6d3pvUTJ5c29iZkFzTGRiL0l4cUwxSApCL1B4YlNoNGthYjhPTEFkY0tnUElBWVkxd3NKZ1JRVkhsWVIvZTZHelZxYTIxRmRrNTRDNXpFb2FRSmxINVpVCnBZN280aTB4MXlwTlkyRXdvUC9UU3RjTXlBeHA3cXRMaUlZZzh3UWlFdy9OdWFBY3luZ0RKZUgvTnZybkVVWHAKdnFwVTJKRGRnM2J3Q0ZJSHJXNjZteG1QbWVSb3pHa3V1eFFxa1FJREFRQUJBb0lCQUFMaDd0dzRKSlF5UEFWYwpZbFAvSWdvSXE0VjBiWmtqaHZDTEtIRTVJWHE5TVpWOThEK29YRk1PZmorcTBqS2xROTJGdytPVDc2dmMxOVlLCjkyYy9tMUx2Vy82NldVRlZRamxURW9NU2NSaSs0Z3U0WkF4VXNOR2ZRYnhYcFNqSWZoY25CWnhrUmoveVBBanoKZ0o3WGMzTmJBWU9hemJIVTAvaXcra2kyOHQxN2JpRzgxRGVCSHNkaW13NFFDVWt3ek44WElHd09lVEZ5QjlwSwowV1ZNRjlLM05sVEM0clhGL3BRdlpGRmlYeFBDeUx3bXU3blA0dWVtSHJTUUc5aVZvbWtSYWI5YWZhbUJaL2syCkRBeXRQdTZNeExKdWhHa3g1Q1d6eUhRS3U1bm1UZ29nV2paNFZNYTBSNjhnaXZFSUtiMjJjdDhDT0J5Tnh2NU4KRGJrMDVnRUNnWUVBM3RVSzhYSUxsYXBPUzJDaGFuV2pFcmxRT0VhOFBEQUgzT2lJVHBiT0ZhNTJBYXY3dzJJbwpHRVdFV2l1cTRncmp5ZXVaNWhJYS9YcmZNNmFKbVlMeEg1elpxZjV0QmVSMUx4NUZQNDNJRUQxRnIxSVhWLzkxCk5JcnI0aXZBVjk5SWk0NVdIZEkyeUk5WUZoQnBNYW8vbDBVUHovOSt1UmxLNDUwVTlmSFFuNmtDZ1lFQS9Zc0oKRTdFRmxRZlNST3EyejVuQkQ0aXdnaWlTZGN4VUlidWltUWw2ZmR6ckRGRGJhVGhhTmt4UWlXWEpJS1ZXcnFsZwo5R1RxSXBJUVI0NUtjeEk4N1lRenJLaDBmVkhzNnhQN005WjNtbGRVTk1tVVVlenJHcHpnYXpLWll2ZHMvaEw0CkVhaXpMTitpaURtUXRyZ1BONTlYa0hQTldCRElUMVJtS0k4UEpLa0NnWUVBeDg2R1VudXRzWlVWUVhlekpXKzQKT3RqWitxeEtxemx5UTM1cWd2V3NjenFOYS9CWC94bHIxRis1VHRWckUrY3AyK3diZ25abnB6VGZJVVJLaTlFaQovdks1SmpvU2JqOHRhSU9mR2w2NnJ2MFNHQ1BtOUt3RzM0ZFYvZWEzUU5QaEMrb2tnL2J6MHFEZUhtSzJ3S2JsCkFISVh2SzFmWndBcjY2NzFsWmN3TjRrQ2dZQVFuN0licVdxdFI5TUFrOGNpdTNrT0ZLOUdDWFQ0NWtuSjRHeWIKemlSSzVsWSsrM28zWHV1RFRlT2w3cGVPWFdqZWtOcDdpN1pTUi9OclRhZ1IvV3NqUTV6RHdGUEs5N2twL0tobQowTFFNMlpiNjB4QzNnbW96MTM5Ylovam9wVUp2TWowem96VUVSekYzN3haTzlLaUN4QjdRcU5jWTVCak9Jc0dECi9VVkg2UUtCZ0hSdUtUeGhFZ1d4REh0bjhjQXJzTk1IVzQ3Tk9sbFlqVzZOS2g2b2hSOHBERmNYVTVXTmc0UXgKN2l1bUh3MExwZ2VmWnNXRm9CMmRMc2Z4UW9LMjRnZXI0WWdnUWVWNkhNVndrZ2tjMitTUlQxRDFnOUFBVmNhagpuS0xIb3h4MU5oY0UvWWQxeW1OT0UxdHd2Z1hSc2NUM3NSb0F3QWkydjlTYzhOU1pBRXFLCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
logLevel: INFO
protocol: mtls
runtime: runc
runk:
  namespace: ""
  dnsServers: []
  kubeconfigFile: ""
capacity:
  cpu: ""
  memory: ""
  pods: ""
  storage: ""
reservedResources:
  cpu: ""
  memory: ""
image:
  pullPolicy: ""
  defaultRegistry: ""
  registries: []
datastoreEndpoint: ""
```

### What happend and What you expected to happen.

```shell
运行psi的时候报错

[root@root-kuscia-autonomy-bob-ecs-46f7 kuscia]# kubectl get kt wilf-erstuqug-node-36 -n cross-domain -o yaml
apiVersion: kuscia.secretflow/v1alpha1
kind: KusciaTask
metadata:
  annotations:
    kuscia.secretflow/initiator: alice
    kuscia.secretflow/interconn-bfia-parties: ""
    kuscia.secretflow/interconn-kuscia-parties: bob
    kuscia.secretflow/interconn-self-parties: bob
    kuscia.secretflow/job-id: wilf
    kuscia.secretflow/party-master-domain: bob
    kuscia.secretflow/self-cluster-as-initiator: "false"
    kuscia.secretflow/task-alias: wilf-erstuqug-node-36
  creationTimestamp: "2024-07-16T05:34:32Z"
  generation: 1
  labels:
    kuscia.secretflow/controller: kuscia-job
    kuscia.secretflow/job-uid: f1c2f723-8cfb-4d85-91bc-e5bb1e44425b
  name: wilf-erstuqug-node-36
  namespace: cross-domain
  ownerReferences:
  - apiVersion: kuscia.secretflow/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: KusciaJob
    name: wilf
    uid: f1c2f723-8cfb-4d85-91bc-e5bb1e44425b
  resourceVersion: "107802"
  uid: d619b8a4-521d-43a9-864a-c0e662ae9375
spec:
  initiator: alice
  parties:
  - appImageRef: secretflow-image
    domainID: bob
    template:
      spec: {}
  - appImageRef: secretflow-image
    domainID: alice
    template:
      spec: {}
  scheduleConfig: {}
  taskInputConfig: |-
    {
      "sf_datasource_config": {
        "bob": {
          "id": "default-data-source"
        },
        "alice": {
          "id": "default-data-source"
        }
      },
      "sf_cluster_desc": {
        "parties": ["bob", "alice"],
        "devices": [{
          "name": "spu",
          "type": "spu",
          "parties": ["bob", "alice"],
          "config": "{\"runtime_config\":{\"protocol\":\"SEMI2K\",\"field\":\"FM128\"},\"link_desc\":{\"connect_retry_times\":60,\"connect_retry_interval_ms\":1000,\"brpc_channel_protocol\":\"http\",\"brpc_channel_connection_type\":\"pooled\",\"recv_timeout_ms\":1200000,\"http_timeout_ms\":1200000}}"
        }, {
          "name": "heu",
          "type": "heu",
          "parties": ["bob", "alice"],
          "config": "{\"mode\": \"PHEU\", \"schema\": \"paillier\", \"key_size\": 2048}"
        }],
        "ray_fed_config": {
          "cross_silo_comm_backend": "brpc_link"
        }
      },
      "sf_node_eval_param": {
        "domain": "data_prep",
        "name": "psi",
        "version": "0.0.5",
        "attr_paths": ["input/receiver_input/key", "input/sender_input/key", "protocol", "sort_result", "allow_duplicate_keys", "allow_duplicate_keys/no/skip_duplicates_check", "fill_value_int", "ecdh_curve"],
        "attrs": [{
          "is_na": false,
          "ss": ["uid"]
        }, {
          "is_na": false,
          "ss": ["uid"]
        }, {
          "is_na": false,
          "s": "PROTOCOL_RR22"
        }, {
          "b": true,
          "is_na": false
        }, {
          "is_na": false,
          "s": "no"
        }, {
          "is_na": true
        }, {
          "is_na": true
        }, {
          "is_na": false,
          "s": "CURVE_FOURQ"
        }],
        "inputs": [{
          "type": "sf.table.individual",
          "meta": {
            "@type": "type.googleapis.com/secretflow.spec.v1.IndividualTable",
            "line_count": "-1"
          },
          "data_refs": [{
            "uri": "record_451306974.csv",
            "party": "alice",
            "format": "csv"
          }]
        }, {
          "type": "sf.table.individual",
          "meta": {
            "@type": "type.googleapis.com/secretflow.spec.v1.IndividualTable",
            "line_count": "-1"
          },
          "data_refs": [{
            "uri": "payment_352938295.csv",
            "party": "bob",
            "format": "csv"
          }]
        }],
        "checkpoint_uri": "ckwilf-erstuqug-node-36-output-0"
      },
      "sf_output_uris": ["wilf-erstuqug-node-36-output-0"],
      "sf_input_ids": ["shzphbsr", "stivuccf"],
      "sf_output_ids": ["wilf-erstuqug-node-36-output-0"]
    }
status:
  allocatedPorts:
  - domainID: bob
    namedPort:
      wilf-erstuqug-node-36-0/client-server: 30356
      wilf-erstuqug-node-36-0/fed: 30358
      wilf-erstuqug-node-36-0/global: 30353
      wilf-erstuqug-node-36-0/node-manager: 30354
      wilf-erstuqug-node-36-0/object-manager: 30355
      wilf-erstuqug-node-36-0/spu: 30357
  conditions:
  - lastTransitionTime: "2024-07-16T05:34:32Z"
    status: "True"
    type: ResourceCreated
  lastReconcileTime: "2024-07-16T06:35:00Z"
  partyTaskStatus:
  - domainID: bob
    phase: Pending
  - domainID: alice
    phase: Failed
  phase: Pending
  podStatuses:
    bob/wilf-erstuqug-node-36-0:
      createTime: "2024-07-16T05:34:32Z"
      message: '0/1 nodes are available: task resource bob/wilf-erstuqug-node-36-ac882fcc7044
        status phase is Failed, skip scheduling pod. last failed scheduling result:
        domain [bob] can not reserve resources for pods. preemption: 0/1 nodes are
        available: 1 Preemption is not helpful for scheduling., reject the pod wilf-erstuqug-node-36-0
        even after PostFilter.'
      namespace: bob
      podName: wilf-erstuqug-node-36-0
      podPhase: Pending
      reason: Unschedulable
  serviceStatuses:
    bob/wilf-erstuqug-node-36-0-fed:
      createTime: "2024-07-16T05:34:32Z"
      namespace: bob
      portName: fed
      portNumber: 30358
      scope: Cluster
      serviceName: wilf-erstuqug-node-36-0-fed
    bob/wilf-erstuqug-node-36-0-global:
      createTime: "2024-07-16T05:34:32Z"
      namespace: bob
      portName: global
      portNumber: 30353
      scope: Domain
      serviceName: wilf-erstuqug-node-36-0-global
    bob/wilf-erstuqug-node-36-0-spu:
      createTime: "2024-07-16T05:34:32Z"
      namespace: bob
      portName: spu
      portNumber: 30357
      scope: Cluster
      serviceName: wilf-erstuqug-node-36-0-spu
  startTime: "2024-07-16T05:34:32Z"
```

### Kuscia log output.

```shell
too long
```

**Comment by wenkesong-li** [comment]
你好，可以附件上传一下日志信息，以便更好排查~

**Comment by ruhengChen** [comment]
[kuscia-alice.log](https://github.com/user-attachments/files/16244218/kuscia-alice.log)
[kuscia-bob.log](https://github.com/user-attachments/files/16244220/kuscia-bob.log)

**Comment by wenkesong-li** [comment]
你好，请检查一下磁盘空间和内存空间~

**Comment by ruhengChen** [comment]
[root@ecs-46f7 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.5G     0  7.5G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G   20M  7.7G   1% /run
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
/dev/vda2        39G   25G   12G  69% /
tmpfs           7.7G   64K  7.7G   1% /tmp
/dev/vda1      1022M  5.8M 1017M   1% /boot/efi
tmpfs           1.6G     0  1.6G   0% /run/user/0
overlay          39G   25G   12G  69% /var/lib/docker/overlay2/00626d91713bc9ff720b57033ce00003090fabe691ed1c1ac3c5012cb7f8ba90/merged
overlay          39G   25G   12G  69% /var/lib/docker/overlay2/bcc69f619a98555dce1835b216eae462edfb8086a23fb6984262d4814c9152cb/merged
overlay          39G   25G   12G  69% /var/lib/docker/overlay2/939b60b3c97410e6bc150475b870cc360303938dc1a68e72aa233505bfc01173/merged
overlay          39G   25G   12G  69% /var/lib/docker/overlay2/0c16f58d56413cdd16e5de8a70df48b9b5297eec6bba71f6f28020a63069917c/merged
overlay          39G   25G   12G  69% /var/lib/docker/overlay2/71ea8c68e821b82958497bbf9fcd789cf0b6833a8a273e074957551938f579a9/merged
overlay          39G   25G   12G  69% /var/lib/docker/overlay2/ac61fe3b656c4bbfae107c21fe109ebe03d66224db3b8d75f31dc0e184c38290/merged
[root@ecs-46f7 ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:          15760        4425        1487        9319        9848         523
Swap:             0           0           0


这样不够吗

**Comment by aokaokd** [comment]
容器里执行下： kubectl describe node 看下

**Comment by ruhengChen** [comment]
[root@root-kuscia-autonomy-bob-ecs-46f7 kuscia]#  kubectl describe node
Name:               root-kuscia-autonomy-bob-ecs-46f7
Roles:              agent
Labels:             beta.kubernetes.io/arch=aarch64
                    beta.kubernetes.io/os=linux
                    domain=bob
                    kubernetes.io/apiVersion=0.26.6
                    kubernetes.io/arch=aarch64
                    kubernetes.io/hostname=root-kuscia-autonomy-bob-ecs-46f7
                    kubernetes.io/os=linux
                    kubernetes.io/role=agent
                    kuscia.secretflow/namespace=bob
                    kuscia.secretflow/runtime=runc
Annotations:        node.alpha.kubernetes.io/ttl: 0
CreationTimestamp:  Mon, 15 Jul 2024 18:17:58 +0800
Taints:             kuscia.secretflow/agent=v1:NoSchedule
                    node.kubernetes.io/memory-pressure:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  root-kuscia-autonomy-bob-ecs-46f7
  AcquireTime:     <unset>
  RenewTime:       Tue, 16 Jul 2024 15:38:41 +0800
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                   Message
  ----                 ------  -----------------                 ------------------                ------                   -------
  NetworkUnavailable   False   Tue, 16 Jul 2024 13:24:47 +0800   Tue, 16 Jul 2024 13:24:47 +0800   RouteCreated             RouteController created a route
  PIDPressure          False   Tue, 16 Jul 2024 13:24:47 +0800   Tue, 16 Jul 2024 13:24:47 +0800   AgentHasSufficientPID    Agent has sufficient PID available
  MemoryPressure       True    Tue, 16 Jul 2024 15:38:18 +0800   Tue, 16 Jul 2024 13:24:47 +0800   AgentHasMemoryPressure   Memory is about to run out, total=15.4GB, available=576.5MB
  DiskPressure         False   Tue, 16 Jul 2024 15:38:18 +0800   Tue, 16 Jul 2024 13:24:47 +0800   AgentHasNoDiskPressure   Agent has no disk pressure. @agent_volume: space=24.6GB/36.2GB(68.1%) inode=278.3k/2.6M(10.9%)
  OutOfDisk            False   Tue, 16 Jul 2024 15:38:18 +0800   Tue, 16 Jul 2024 13:24:47 +0800   AgentHasSufficientDisk   Agent has sufficient disk space available. @agent_volume: free_space=11.5GB, free_inode=2.3M
  Ready                True    Tue, 16 Jul 2024 15:38:18 +0800   Tue, 16 Jul 2024 13:24:47 +0800   AgentReady               Agent is ready
Addresses:
  InternalIP:  172.18.0.6
Capacity:
  cpu:      8
  memory:   16139200Ki
  pods:     500
  storage:  39988608Ki
Allocatable:
  cpu:      8
  memory:   459520Ki
  pods:     500
  storage:  11986828Ki
System Info:
  Machine ID:                 94118d27-3e36-4e55-bf94-945fb0e7ead3
  System UUID:
  Boot ID:                    1721107223-1721107487570958605
  Kernel Version:             4.19.90-17.5.ky10.aarch64
  OS Image:                   docker://linux/anolis:23 (guest)
  Operating System:           linux
  Architecture:               aarch64
  Container Runtime Version:
  Kubelet Version:            v0.9.0b0-2-g7663c20
  Kube-Proxy Version:
PodCIDR:                      10.42.0.0/24
PodCIDRs:                     10.42.0.0/24
Non-terminated Pods:          (0 in total)
  Namespace                   Name    CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
  ---------                   ----    ------------  ----------  ---------------  -------------  ---
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests  Limits
  --------           --------  ------
  cpu                0 (0%)    0 (0%)
  memory             0 (0%)    0 (0%)
  ephemeral-storage  0 (0%)    0 (0%)
  storage            0         0
Events:              <none>

**Comment by wenkesong-li** [comment]
你好，节点信息中显示：node.kubernetes.io/memory-pressure:NoSchedule
内存不足所导致的，kuscia最少需要6g内存，如果使用docker环境运行
请使用docker update --memory 调整内存资源

**Comment by ruhengChen** [comment]
好的 感谢~

**Comment by ruhengChen** [comment]
<img width="738" alt="2024-07-16 17 06 53@2x" src="https://github.com/user-attachments/assets/bfd1f01a-e1e4-4f0c-ad5e-27156d118e11">
你好，我这边已经把内存调整到6g了，但是还是显示                    node.kubernetes.io/memory-pressure:NoSchedule
请问该怎么解决

**Comment by wenkesong-li** [comment]
你好，调整资源分配后重新启动一下镜像~

**Comment by ruhengChen** [comment]
已经重新启动过了

**Comment by ruhengChen** [comment]
可以了 应该还是内存不够的原因
