### ISSUE TITLE
Kuscia有没有helmchart提供部署

### ISSUE THREAD

**Issue by magic-hya** [secretflow/kuscia#405]
### Issue Type

Api Usage

### Search for existing issues similar to yours

Yes

### Kuscia Version

k8s中心化部署kuscia  v0.8.0b0

### Question Details

```shell
Kuscia有没有helmchart配置提供部署
```

**Comment by 383004576** [comment]
原生k8s是支持helm chart的，跟kuscia没有关系，可以自行尝试一下。

**Comment by magic-hya** [comment]
抱歉没说清楚，我的意思是，部署kuscia时，有没有现成的helmchart脚本。kuscia的部署流程比较复杂，我现在项目需要直接使用helmchart部署，如果没有现成的，我可能就需要自己弄了。

**Comment by 383004576** [comment]
没有helmchart脚本的

**Comment by magic-hya** [comment]
好的，那我先自行探索一下，有问题我会反馈
