### ISSUE TITLE
想要实现亿级别隐私求交的问题

### ISSUE THREAD

**Issue by ShaneGu4Real** [secretflow/kuscia#412]
### Issue Type

Feature

### Search for existing issues similar to yours

Yes

### Kuscia Version

v0.9.0b0

### Question Details

```shell
如果部署在云环境里，想要实现“单任务”双方1亿数据量级别的多字段隐私求交（比对差不多10个字段），假定云资源充足，是否只能在双方一共两个容器里，进行求交，还是说可以调起多个容器，并发实现一个任务，来提高效率，如果可以应该怎么做。
```

**Comment by 383004576** [comment]
您好，单任务分到多容器运算目前是不支持的，您对亿级别数据量的期望运算时间是多久呢？

**Comment by ShaneGu4Real** [comment]
您好，亿级别希望在几小时级别是可以接受的，如果可以实现的话，是在单容器里，我们是部署在云环境的k8s集群里，需要我们分配多大的内存、cpu和带宽呢

**Comment by 383004576** [comment]
secretflow 1.9版本psi，亿级别规模可以参考双方节点配置（16C，内存64G，500G）是能够达到几小时的要求的，可以尝试一下，精准的时间还会受实际环境网络和测试数据大小等因素影响

**Comment by ShaneGu4Real** [comment]
谢谢，您的回复，我们回头再试下
