### ISSUE TITLE
发现文档里的一个疑似接口介绍错误

### ISSUE THREAD

**Issue by AgravicCastle** [secretflow/kuscia#42]
这个项《[查询Job状态](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/apis/kusciajob_cn#query-job-status)》好像是多余的。上一项《查询Job》中已经描述了/api/v1/job/query接口，并且《查询Job状态》的返回值描述也与实际请求的返回对不上。
![image](https://github.com/secretflow/kuscia/assets/25099083/ce19006a-4ebe-4986-a36c-d370c38738c0)

https://github.com/secretflow/kuscia/blob/38dd13cd5b6e41eb53213e0e17c808dbbcb0f657/pkg/kusciaapi/bean/http_server_bean.go#L166 中也没有其他的接口了。
综上，怀疑是多余的内容。
#28

**Comment by cho-chem** [comment]
是的这是一个错误，我们会在下一个迭代中修复这个问题，感谢反馈。
