### ISSUE TITLE
kuscia开发环境问题，请教大佬指点，拜谢

### ISSUE THREAD

**Issue by neaos** [secretflow/kuscia#421]
### Issue Type

Api Usage

### Search for existing issues similar to yours

Yes

### Kuscia Version

kuscia:0.8.0b0

### Question Details

```shell
现基于业务场景【增加数据库类型数据资源】，故需改造kuscia代码，现搭建kuscia开发环境遇到一些问题。
前提环境：
linux arm64环境下，
bash install.sh autonomy -n com2023011620063473637 -s 8081 -g 40803 -k 40802 -p 10080 -q 15081
通过上面这条命令一键部署的，得到secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.8.0b0容器。
现步骤：
1、clone代码到/opt/isafelinke/goProject/kuscia目录，
git clone --branch v0.8.0b0 --single-branch https://github.com/secretflow/kuscia.git
git checkout -b feature-from-v0.8.0b0
2、在/opt/isafelinke/goProject/kuscia目录下，执行
make build
make image
得到镜像 secretflow/kuscia:v0.8.0b0-20240909104042
问题:
1、怎么将新打的kuscia镜像secretflow/kuscia:v0.8.0b0-20240909104042，替换之前一键部署并正在使用的容器secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia:0.8.0b0呢？
2、怎么打造可debug调试的kuscia开发环境呢？
```

**Comment by neaos** [comment]
<img width="1089" alt="46cfdbf8ae5646ca0c8811b5b7613d9" src="https://github.com/user-attachments/assets/94611203-b0e8-4c0f-aed0-853f5b17ee5c">

**Comment by 1139763082** [comment]
您的安装包是在哪下载的？

**Comment by neaos** [comment]
![image](https://github.com/user-attachments/assets/f5c56e5c-e512-4068-b9e3-cfef6f925317)
https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/deployment_package
这里下载的

**Comment by neaos** [comment]
> 您的安装包是在哪下载的？

https://www.secretflow.org.cn/zh-CN/docs/secretpad-all-in-one/v1.8.0b0/deployment_package

**Comment by neaos** [comment]
![image](https://github.com/user-attachments/assets/257ff72f-6647-4a08-ae6a-01cab964b37e)
如果是数据库类型的数据这里该怎么改呢 ，有拓展的地方吗

**Comment by zimu-yuxi** [comment]
1.暂时没法替换，你可以重新部署安装，使用你自己打的镜像
2.可以打日志的形式
3.请问二开kuscia的目的是为了支持其它数据源吗？想要支持哪些数据源呢？

**Comment by neaos** [comment]
> 1.暂时没法替换，你可以重新部署安装，使用你自己打的镜像 2.可以打日志的形式 3.请问二开kuscia的目的是为了支持其它数据源吗？想要支持哪些数据源呢？

3.目的是为了支持其他数据源，诸如达梦、PG、Oracle等主流数据库。

能不能提供一个手工启动kuscia的命令

**Comment by 1139763082** [comment]
暂时只支持oss和本地的数据源，后续会支持odps。其他的数据源暂时没有计划支持
kuscia部署可以参考官方文档：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/Docker_deployment_kuscia/deploy_master_lite_cn#id8
