### ISSUE TITLE
创建节点间路由失败

### ISSUE THREAD

**Issue by zwj-edas** [secretflow/kuscia#429]
### Issue Type

Running

### Search for existing issues similar to yours

Yes

### OS Platform and Distribution

centos7

### Kuscia Version

kuscia0.11.0b0

### Deployment

docker

### deployment Version

docker

### App Running type

others

### App Running version

kuscia

### Configuration file used to run kuscia.

```shell
kuscia点对点部署
```

### What happend and What you expected to happen.

```shell
创建节点间路由，alice-sam，使用kuscia-api，用源节点alice的证书，调用alice节点的CreateDomainRoute接口
```

### Kuscia log output.

```shell
输出报错：找不到sam节点
```

**Comment by lanyy9527** [comment]
可以检查下alice节点下检查 domainid：sam 是否存在，若不存在，需要在alice中添加sam的证书信息，可以参考：https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/deployment/Docker_deployment_kuscia/deploy_p2p_cn#bob-alice

**Comment by zwj-edas** [comment]
请问颁发证书有api接口么，那节点间路由相当于颁发证书的下一步，是授权么？

**Comment by lanyy9527** [comment]
> 请问颁发证书有api接口么，那节点间路由相当于颁发证书的下一步，是授权么？

需要手动将合作方的domain.crt复制到本方容器中，路由其实就相当于授权了，配置路由之前要先颁发证书；

**Comment by zwj-edas** [comment]
在secreatpad上看可以在页面添加合作节点，这一步也仅是创建路由么，合作方的证书也是事先手动拷贝过去的么？

**Comment by lanyy9527** [comment]
> 在secreatpad上看可以在页面添加合作节点，这一步也仅是创建路由么，合作方的证书也是事先手动拷贝过去的么？

1. pad中两个操作都会涉及到；
2. 部署脚本中会完成，不需要手动，可以参考脚本：https://github.com/secretflow/kuscia/blob/main/scripts/deploy/add_domain.sh
