### ISSUE TITLE
发现FATE作业文档疑似有误

### ISSUE THREAD

**Issue by cs1317** [secretflow/kuscia#43]
在验证kuscia《如何运行一个 FATE 作业》教程文档时，发现文档疑似有误
https://github.com/secretflow/kuscia/issues/26

![image](https://github.com/secretflow/kuscia/assets/50541363/47e7e6d1-da1d-4471-8206-7a59eac8aa97)
没有找到${USER}-fate-kuscia-lite-bob容器：
![image](https://github.com/secretflow/kuscia/assets/50541363/0cf6d054-2690-4a8e-9795-827128e8c21c)

登入 Bob lite 容器，应该是：
docker exec -it ${USER}-kuscia-lite-bob bash

但是登入${USER}-kuscia-lite-bob后，执行crictl ps，并没有找到  部署 FATE 的 container：fate-deploy-bob
![image](https://github.com/secretflow/kuscia/assets/50541363/6a215855-c0ef-49ab-aaa2-6b4d905a6eb5)

**Comment by gshilei** [comment]
感谢你的反馈，这里的容器名称是写错了。在下一个版本，我们会更正。

**Comment by cs1317** [comment]
@gshilei 
还有一个问题：
我登入 Bob lite 容器(${USER}-kuscia-lite-bob)后，执行crictl ps，并没有找到  部署 FATE 的 container：fate-deploy-bob
![image](https://github.com/secretflow/kuscia/assets/50541363/00dd5590-a5f5-44da-ab1b-500353d1140a)

**Comment by gshilei** [comment]
> @gshilei 还有一个问题： 我登入 Bob lite 容器(${USER}-kuscia-lite-bob)后，执行crictl ps，并没有找到 部署 FATE 的 container：fate-deploy-bob ![image](https://user-images.githubusercontent.com/50541363/255865362-00dd5590-a5f5-44da-ab1b-500353d1140a.png)

针对这个问题，先登陆到master容器中查看Pod fate-deploy-bob 是否Running。
# 进入 Master 容器，确认 Bob 机构的 FATE 启动完成（能看到 fate-deploy-bob 开头的 Pod 启动正常）
docker exec -it ${USER}-kuscia-master bash
kubectl get pods -A

如果Pod fate-deploy-bob 是Pending状态，可通过命令 kubectl describe pod fate-deploy-bob-xxxx -n bob 查看Pending的原因。

**Comment by cs1317** [comment]
![image](https://github.com/secretflow/kuscia/assets/50541363/d1768fd8-40ec-4c1f-aaf3-c96d4a29be4a)
这个是什么原因造成的呢？

**Comment by gshilei** [comment]
> ![image](https://user-images.githubusercontent.com/50541363/255884458-d1768fd8-40ec-4c1f-aaf3-c96d4a29be4a.png) 这个是什么原因造成的呢？

初步怀疑机器上内存不足导致的。正常流程 fate-deploy-bob Pod 需要8G的内存，可以通过下面命令查看bob节点资源是否满足，以下命令都是在master容器中执行：
1. 查看节点列表
kubectl get node

2. 查看bob节点内存可用情况
kubectl describe node xxx-kuscia-lite-bob | grep -A3 Allocatable

ps: 可以尝试将 fate-deploy-bob Pod 所需 Request 内存调小点，命令如下:
kubectl patch deploy fate-deploy-bob --patch '{"spec": {"template": {"spec": {"containers": [{"name": "fate-deploy-bob","resources": {"requests": {"memory": "1G"}}}]}}}}'

执行完上述命令后，通过下面命令查看Pod是否启动：
kubectl get pod -n bob

**Comment by gshilei** [comment]
@cs1317 你好，请问上述答疑是否已解决你的问题？如果已解决的话，我就关掉这个Issue了。

**Comment by cs1317** [comment]
执行这个命令的 时候，显示 deployments.app 中找不到fate-deploy-bob
kubectl patch deploy fate-deploy-bob --patch '{"spec": {"template": {"spec": {"containers": [{"name": "fate-deploy-bob","resources": {"requests": {"memory": "1G"}}}]}}}}'

**Comment by gshilei** [comment]
> 执行这个命令的 时候，显示 deployments.app 中找不到fate-deploy-bob kubectl patch deploy fate-deploy-bob --patch '{"spec": {"template": {"spec": {"containers": [{"name": "fate-deploy-bob","resources": {"requests": {"memory": "1G"}}}]}}}}'

不好意思，命令中里面缺少了 -n bob 参数。使用下面命令再尝试下
kubectl patch deploy fate-deploy-bob -n bob --patch '{"spec": {"template": {"spec": {"containers": [{"name": "fate-deploy-bob","resources": {"requests": {"memory": "1G"}}}]}}}}'

**Comment by cs1317** [comment]
执行了这个命令之后，fate-deploy-bob仍然是pending状态
![image](https://github.com/secretflow/kuscia/assets/50541363/9684f007-8d6b-4297-8dff-5195aa3808b0)

**Comment by gshilei** [comment]
> 执行了这个命令之后，fate-deploy-bob仍然是pending状态 ![image](https://user-images.githubusercontent.com/50541363/256114014-9684f007-8d6b-4297-8dff-5195aa3808b0.png)

运行下面命令，查看下bob节点资源可用情况
kubectl describe node xxx-kuscia-lite-bob | grep -A3 Allocatable

**Comment by cs1317** [comment]
![image](https://github.com/secretflow/kuscia/assets/50541363/9d693277-2fc4-4aa3-9b48-f015a09c89cf)

**Comment by gshilei** [comment]
> ![image](https://user-images.githubusercontent.com/50541363/256132251-9d693277-2fc4-4aa3-9b48-f015a09c89cf.png)

从上面结果看，可使用的memory大约是6G，不满足正常流程 启动 fate-deploy-bob 所需要的内存 8G
![image](https://github.com/secretflow/kuscia/assets/136570416/37ec1370-0e1b-494d-87ee-7dec2878d553)

麻烦再按下面命令输出信息贴一下
1. 查看pod信息
kubectl describe pod -n bob

2. 查看bob node信息
kubectl describe node xiaomi-kuscia-lite-bob

**Comment by cs1317** [comment]
kubectl describe pod -n bob
![image](https://github.com/secretflow/kuscia/assets/50541363/19f2eeb5-2484-482d-b972-49fb9258e186)
![image](https://github.com/secretflow/kuscia/assets/50541363/6a36dc86-7e26-484d-996b-7b8cc65ed808)

kubectl describe node xiaomi-kuscia-lite-bob
![image](https://github.com/secretflow/kuscia/assets/50541363/2e8e95aa-0457-40ca-9809-2634278dbfb5)
![image](https://github.com/secretflow/kuscia/assets/50541363/840aa3f6-db9f-4148-b447-2468722ceeea)

**Comment by gshilei** [comment]
> kubectl describe pod -n bob ![image](https://user-images.githubusercontent.com/50541363/256135863-19f2eeb5-2484-482d-b972-49fb9258e186.png) ![image](https://user-images.githubusercontent.com/50541363/256135961-6a36dc86-7e26-484d-996b-7b8cc65ed808.png)
> 
> kubectl describe node xiaomi-kuscia-lite-bob ![image](https://user-images.githubusercontent.com/50541363/256136328-2e8e95aa-0457-40ca-9809-2634278dbfb5.png) ![image](https://user-images.githubusercontent.com/50541363/256136463-840aa3f6-db9f-4148-b447-2468722ceeea.png)

从上面结果看，通过kubectl patch命令修改memory为1G已经生效，现在Pod Pending的原因是机器磁盘空间不足了，可以清理下磁盘空间，再看看。
![image](https://github.com/secretflow/kuscia/assets/136570416/ba003f9f-0a8b-434b-9579-dfdc6e52e350)

![image](https://github.com/secretflow/kuscia/assets/136570416/c2b961e9-9f7c-431b-84b1-6c8a071d8f01)

**Comment by cs1317** [comment]
感谢，问题得到解决！
