### ISSUE TITLE
使用 SCQL 进行联合分析，如何创建localfs的数据源，指定路径为本地磁盘

### ISSUE THREAD

**Issue by moon-177** [secretflow/kuscia#433]
### Issue Type

Api Usage

### Search for existing issues similar to yours

Yes

### Kuscia Version

Kuscia 0.11.0b0  scql 0.9.0b0

### Question Details

```shell
之前创建domaindatasource，尝试的都是指定路径为服务器容器内的相对路径，例如/home/kuscia/var/storage/data/alice这样；请问该如何将path指定为本地路径呢，例如D:\test\data这样的自己电脑的路径。

我尝试了一下，在联合分析时会提示：no files found that match the pattern ……

是只能指定kuscia容器内的路径嘛
```

**Comment by BrainWH** [comment]
你好，如果使用kuscia部署的话，在执行./kuscia.sh start的时候加一下-d 指定一下本地的路径，可以尝试一下

**Comment by moon-177** [comment]
添加-d后，部署kuscia会报错：docker: Error response from daemon: invalid mode: /home/kuscia/var/storage/data

**Comment by BrainWH** [comment]
你好，可以贴一下你的执行命令

**Comment by moon-177** [comment]
./kuscia.sh strat -c node.yaml -p ** -k ** -g ** -q ** -x ** -d /c/data
已经部署成功，正在验证后续问题

**Comment by moon-177** [comment]
在部署kuscia时添加-d指定了本地路径为：-d /c/data；
创建domaindatasource时指定localfs的path为：C://data；
后续步骤均按照 如何在 Kuscia 上运行 SCQL 联合分析任务 的说明进行；
在执行联合分析任务时报错，提示：code：320，message：RunExecutionPlan run jobs(e52c8398-87b1-11ef-86a2-c6d585a223c) failed, catch std::exception[external/yacl/yacl/link/transport/channel.cc:427] Get data timeout, key=e52c8398-87b1-11ef-86a2-c6d58b5a223c-0:1:ALLGATHER, detail=[]
这是什么原因导致的呢？
