### ISSUE TITLE
数据授权咨询

### ISSUE THREAD

**Issue by beng003** [secretflow/kuscia#442]
### Issue Type

Api Usage

### Search for existing issues similar to yours

No

### Kuscia Version

kuscia v0.11.0b0

### Link to Relevant Documentation

https://github.com/secretflow/kuscia/blob/v0.11.0b0/python/kuscia/proto/api/v1alpha1/datamesh/domaindatagrant_pb2_grpc.py

### Question Details

```shell
我发现在https://github.com/secretflow/kuscia/blob/v0.11.0b0/python/kuscia/proto/api/v1alpha1/datamesh/domaindatagrant_pb2_grpc.py
和https://github.com/secretflow/kuscia/blob/v0.11.0b0/python/kuscia/proto/api/v1alpha1/datamesh/domaindatagrant_pb2.py中有关于数据授权的代码接口，我想请教一下针对具体的domain_id,domaindata_id和grant_domain使用流程
```

**Comment by BrainWH** [comment]
你好，目前是在做二开吗？可以讲一下具体的场景吗？

**Comment by BrainWH** [comment]
1、你好，相关的数据授权的概念，可以参照https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.11.0b0/reference/concepts/domaindatagrant_cn2
2、如果是已经存在的表， 在secretpad 中调用，可以调用 KusciaAPI 去添加；如果是相关的算子，可以调用kuscia 的 DataMesh 接口去创建数据
