### ISSUE TITLE
关于的kuscia的疑问

### ISSUE THREAD

**Issue by xiaoran33** [secretflow/kuscia#453]
### Issue Type

Document

### Search for existing issues similar to yours

Yes

### Kuscia Version

0.7.0b0

### Link to Relevant Documentation

https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l

### Question Details

```shell
https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l
在这个文档的架构图中，kuscia在算法层上面
https://blog.csdn.net/m0_69580723/article/details/134949659
在这个文档的架构图中，kuscia在算法层下面
咨询一下官方同学，哪个是正确的？
```

**Comment by xiaoran33** [comment]
https://www.secretflow.org.cn/zh-CN/docs/blog/latest/tox42l
![1](https://github.com/user-attachments/assets/9865dd34-a633-47b2-8d26-b7c748e49e4e)
https://blog.csdn.net/m0_69580723/article/details/134949659
![2](https://github.com/user-attachments/assets/2132b742-5408-4719-a6ee-72b2aa6d35fc)

**Comment by BrainWH** [comment]
1、第一张图呢，是从用户的视角出发，从产品层一直到最底层的硬件层，图中箭头的指向表示了用户的数据的流向，用户直接接触的是产品层，而产品层直接接触的又是调度层的Kuscia;
2、第二张图中，是按照总体架构自底向上展示的，最底层是硬件层，这样直接接触的是Kuscia,  然后通过Kuscia进行调度，这样最上层就是产品层，提供API/白屏操作/黑屏操作
