### ISSUE TITLE
如何使用KusciaJob执行一个PSI和PIR任务？

### ISSUE THREAD

**Issue by yaoyizhuo** [secretflow/kuscia#457]
### Issue Type

Others

### Search for existing issues similar to yours

Yes

### Kuscia Version

latest

### Link to Relevant Documentation

latest

### Question Details

```shell
latest
如何使用KusciaJob执行一个PSI和PIR任务？
有看到暂时不支持PIR,预计什么时候可以支持呢？
```

**Comment by BrainWH** [comment]
当前可以使用KusciaJob执行PSI任务，可以参考https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.12.0b0/reference/apis/kusciajob_cn#create-job；当前的版本还不支持KusciaJob执行PIR，可以等待后续的版本，后续可以支持的。

**Comment by yaoyizhuo** [comment]
> 当前可以使用KusciaJob执行PSI任务，可以参考[https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.12.0b0/reference/apis/kusciajob_cn#create-job；当前的版本还不支持KusciaJob执行PIR，可以等待后续的版本，后续可以支持的。](https://www.secretflow.org.cn/zh-CN/docs/kuscia/v0.12.0b0/reference/apis/kusciajob_cn#create-job%EF%BC%9B%E5%BD%93%E5%89%8D%E7%9A%84%E7%89%88%E6%9C%AC%E8%BF%98%E4%B8%8D%E6%94%AF%E6%8C%81KusciaJob%E6%89%A7%E8%A1%8CPIR%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%AD%89%E5%BE%85%E5%90%8E%E7%BB%AD%E7%9A%84%E7%89%88%E6%9C%AC%EF%BC%8C%E5%90%8E%E7%BB%AD%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E7%9A%84%E3%80%82)

你好，我调用API创建成功了一个PSI任务，参数如下：
`{
  "job_id": "job-alice-bob-008",
  "initiator": "alice",
  "tasks": [
    {
      "task_id": "job-psi-008",
      "app_image": "secretflow-image",
      "parties": [
        {
          "domain_id": "alice"
        },
        {
          "domain_id": "bob"
        }
      ],
      "dependencies": [], 
      "alias": "job-psi",
    "task_input_config": "{\"sf_datasource_config\":{\"alice\":{\"id\":\"demo-local-datasource\"},\"bob\":{\"id\":\"cliente-bbf51cea-98bb-4039-adc8-56bd41394f79\"}},\"sf_cluster_desc\":{\"parties\":[\"alice\",\"bob\"],\"devices\":[{\"name\":\"spu\",\"type\":\"spu\",\"parties\":[\"alice\",\"bob\"],\"config\":\"{\\\\\"runtime_config\\\\\":{\\\\\"protocol\\\\\":\\\\\"REF2K\\\\\",\\\\\"field\\\\\":\\\\\"FM64\\\\\"},\\\\\"link_desc\\\\\":{\\\\\"connect_retry_times\\\\\":60,\\\\\"connect_retry_interval_ms\\\\\":1000,\\\\\"brpc_channel_protocol\\\\\":\\\\\"http\\\\\",\\\\\"brpc_channel_connection_type\\\\\":\\\\\"pooled\\\\\",\\\\\"recv_timeout_ms\\\\\":1200000,\\\\\"http_timeout_ms\\\\\":1200000}}\"},{\"name\":\"heu\",\"type\":\"heu\",\"parties\":[\"alice\",\"bob\"],\"config\":\"{\\\\\"mode\\\\\": \\\\\\\"PHEU\\\\\\\", \\\\\\\"schema\\\\\\\": \\\\\\\"paillier\\\\\\\", \\\\\\\"key_size\\\\\\\": 2048}\"}],\"ray_fed_config\":{\"cross_silo_comm_backend\":\"brpc_link\"}},\"sf_node_eval_param\":{\"domain\":\"data_prep\",\"name\":\"psi\",\"version\":\"0.0.5\",\"attr_paths\":[\"protocol\",\"sort_result\",\"allow_duplicate_keys\",\"allow_duplicate_keys/yes/join_type\",\"allow_duplicate_keys/yes/join_type/left_join/left_side\",\"input/receiver_input/key\",\"input/sender_input/key\"],\"attrs\":[{\"s\":\"PROTOCOL_RR22\"},{\"b\":true},{\"s\":\"yes\"},{\"s\":\"left_join\"},{\"ss\":[\"alice\"]},{\"ss\":[\"id\"]},{\"ss\":[\"id\"]}]},\"sf_input_ids\":[\"d123456\",\"d123457\"],\"sf_output_ids\":[\"psi-output\"],\"sf_output_uris\":[\"psi-output.csv\"]}",
      "priority": 100 
    }
  ]
}`


获取任务状态发现失败，发现是bob节点json解析失败，尝试跑了一下默认的任务，也是同样的json解析失败
{
    "status": {
        "code": 0,
        "message": "success",
        "details": []
    },
    "data": {
        "jobs": [
            {
                "job_id": "job-alice-bob-008",
                "status": {
                    "state": "Failed",
                    "err_msg": "",
                    "create_time": "2024-11-19T05:54:22Z",
                    "start_time": "2024-11-19T05:54:22Z",
                    "end_time": "2024-11-19T05:54:28Z",
                    "tasks": [
                        {
                            "task_id": "job-psi-008",
                            "state": "Failed",
                            "err_msg": "The remaining no-failed party task counts 1 are less than the task success threshold 2. pending party[], running party[alice], successful party[], failed party[bob]",
                            "create_time": "2024-11-19T05:54:22Z",
                            "start_time": "2024-11-19T05:54:22Z",
                            "end_time": "2024-11-19T05:54:28Z",
                            "parties": [
                                {
                                    "domain_id": "alice",
                                    "state": "Failed",
                                    "err_msg": "",
                                    "endpoints": [
                                        {
                                            "port_name": "fed",
                                            "scope": "Cluster",
                                            "endpoint": "job-psi-008-0-fed.alice.svc"
                                        },
                                        {
                                            "port_name": "global",
                                            "scope": "Domain",
                                            "endpoint": "job-psi-008-0-global.alice.svc:21053"
                                        },
                                        {
                                            "port_name": "spu",
                                            "scope": "Cluster",
                                            "endpoint": "job-psi-008-0-spu.alice.svc"
                                        }
                                    ]
                                },
                                {
                                    "domain_id": "bob",
                                    "state": "Failed",
                                    "err_msg": "container[secretflow] terminated state reason \"Error\", message: \"WARNING:root:Since the GPL-licensed package `unidecode` is not installed, using Python's `unicodedata` package which yields worse results.\\nTraceback (most recent call last):\\n  File \\\"/usr/local/lib/python3.10/runpy.py\\\", line 196, in _run_module_as_main\\n    return _run_code(code, main_globals, None,\\n  File \\\"/usr/local/lib/python3.10/runpy.py\\\", line 86, in _run_code\\n    exec(code, run_globals)\\n  File \\\"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\\\", line 547, in <module>\\n    main()\\n  File \\\"/usr/local/lib/python3.10/site-packages/click/core.py\\\", line 1157, in __call__\\n    return self.main(*args, **kwargs)\\n  File \\\"/usr/local/lib/python3.10/site-packages/click/core.py\\\", line 1078, in main\\n    rv = self.invoke(ctx)\\n  File \\\"/usr/local/lib/python3.10/site-packages/click/core.py\\\", line 1434, in invoke\\n    return ctx.invoke(self.callback, **ctx.params)\\n  File \\\"/usr/local/lib/python3.10/site-packages/click/core.py\\\", line 783, in invoke\\n    return __callback(*args, **kwargs)\\n  File \\\"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/entry.py\\\", line 489, in main\\n    task_conf = KusciaTaskConfig.from_file(task_config_path)\\n  File \\\"/usr/local/lib/python3.10/site-packages/secretflow/kuscia/task_config.py\\\", line 126, in from_file\\n    configs[\\\"task_input_config\\\"] = json.loads(configs[\\\"task_input_config\\\"])\\n  File \\\"/usr/local/lib/python3.10/json/__init__.py\\\", line 346, in loads\\n    return _default_decoder.decode(s)\\n  File \\\"/usr/local/lib/python3.10/json/decoder.py\\\", line 337, in decode\\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\\n  File \\\"/usr/local/lib/python3.10/json/decoder.py\\\", line 355, in raw_decode\\n    raise JSONDecodeError(\\\"Expecting value\\\", s, err.value) from None\\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\\n\"",
                                    "endpoints": [
                                        {
                                            "port_name": "fed",
                                            "scope": "Cluster",
                                            "endpoint": "job-psi-008-0-fed.bob.svc"
                                        },
                                        {
                                            "port_name": "global",
                                            "scope": "Domain",
                                            "endpoint": "job-psi-008-0-global.bob.svc:27556"
                                        },
                                        {
                                            "port_name": "spu",
                                            "scope": "Cluster",
                                            "endpoint": "job-psi-008-0-spu.bob.svc"
                                        }
                                    ]
                                }
                            ],
                            "alias": "job-psi"
                        }
                    ],
                    "stage_status_list": [
                        {
                            "domain_id": "alice",
                            "state": "JobCreateStageSucceeded"
                        },
                        {
                            "domain_id": "bob",
                            "state": "JobCreateStageSucceeded"
                        }
                    ],
                    "approve_status_list": [
                        {
                            "domain_id": "alice",
                            "state": "JobAccepted"
                        },
                        {
                            "domain_id": "bob",
                            "state": "JobAccepted"
                        }
                    ]
                }
            }
        ]
    }
}

**Comment by BrainWH** [comment]
可以提供一下当前secretflow的版本

**Comment by yaoyizhuo** [comment]
> 可以提供一下当前secretflow的版本

不好意思，我这边配置问题。已经跑成功了～麻烦了
