### ISSUE TITLE
中心组网模式 部署 FATE失败

### ISSUE THREAD

**Issue by cs1317** [secretflow/kuscia#51]
https://github.com/secretflow/kuscia/issues/26
拉取镜像错误
![image](https://github.com/secretflow/kuscia/assets/50541363/26ba2bdd-7b9d-473d-a6f5-9eeac9eeefb0)
**kubectl describe pod fate-deploy-bob-6b85647f8b-7qkvx -n bob**
![image](https://github.com/secretflow/kuscia/assets/50541363/295b6105-0d5a-4930-b58f-b826764ffebb)
![image](https://github.com/secretflow/kuscia/assets/50541363/fc6e872e-acff-4415-8634-1e1c76d1986e)

但是我有secretflow/fate-deploy-basic这个镜像的：
![image](https://github.com/secretflow/kuscia/assets/50541363/2a55af9a-e739-49ad-929b-23a2e45a9a9e)

**Comment by bigdadel** [comment]
LMHI

**Comment by bigdadel** [comment]
![image](https://github.com/secretflow/kuscia/assets/116157482/d66d9664-8472-45cb-a601-720bc98fb18e)
这个 ${USER} 是个参数，要换成具体的 USER

**Comment by cs1317** [comment]
> ![image](https://user-images.githubusercontent.com/116157482/257425045-d66d9664-8472-45cb-a601-720bc98fb18e.png) 这个 ${USER} 是个参数，要换成具体的 USER

这个不用换的:
![img_v2_aa95fc1d-9f9b-4b19-ae84-f8b349aa9d5l_MIDDLE](https://github.com/secretflow/kuscia/assets/50541363/3b9668af-dab2-488b-887c-1a924455cc6f)

**Comment by gshilei** [comment]
Hi @cs1317，部署Fate失败，排查文档可参考[FAQ](https://github.com/secretflow/kuscia/blob/main/docs/reference/faq_cn.md)

这里还是希望你能把当前部署的节点全部删除了，重新根据[如何运行一个 FATE 作业](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/tutorial/run_fate_cn)，按文档上的命令，一步一步执行下，复现下，到哪一步出错了。
停止容器和删除容器命令:
docker stop {container-name}
docker rm {container-name}

**Comment by cs1317** [comment]
![image](https://github.com/secretflow/kuscia/assets/50541363/ffec9ccc-f2d3-4743-a23f-14ae85f5d394)
部署成功!
之前用的是vmware的虚拟机，换成wsl后就可以了

**Comment by bigdadel** [comment]
经排查是由于 lite-bob 容器中缺少 secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/fate-deploy-basic 镜像，正常的 lite-bob 容器镜像如下：
![image](https://github.com/secretflow/kuscia/assets/116157482/25bc7177-0ffb-4d35-a6fd-d14eef119e07)

在 lite-bob 节点中执行 ``crictl rmi secretflow/fate-deploy-basic:0.0.1``移除已有的 fate 部署镜像，之后删除所有节点重新部署即可解决。
