### ISSUE TITLE
docker部署kuscia点对点服务时,报genrsa: Can't open "ca.key" for writing, Permission denied

### ISSUE THREAD

**Issue by liuhaichaogithub** [secretflow/kuscia#60]
![image](https://github.com/secretflow/kuscia/assets/40063899/0a4efede-6341-46b3-ba47-3eaf135f70ad)
证书目录是空的

**Comment by cho-chem** [comment]
hi @liuhaichaogithub 可以用 ls 看下 kuscia-autonomy-alice-certs 目录吗
```
ls -l kuscia-autonomy-alice-certs
```

**Comment by liuhaichaogithub** [comment]
是空的

**Comment by cho-chem** [comment]
你可以尝试手动在 kuscia-autonomy-alice-certs 目录中写入一个文件吗，看看是否成功。

**Comment by liuhaichaogithub** [comment]
![image](https://github.com/secretflow/kuscia/assets/40063899/0040f969-9acc-4a99-8851-aee0a15be3ee)
写不进去

**Comment by liuhaichaogithub** [comment]
![image](https://github.com/secretflow/kuscia/assets/40063899/37219f19-64ae-4058-b555-c1b2992a2fa4)
我加上这个可以解决，但是又报了另外错误unknown flag: --mount  正在看

**Comment by liuhaichaogithub** [comment]
这个应该是docker版本曹成的，我更新一下试试

**Comment by liuhaichaogithub** [comment]
![image](https://github.com/secretflow/kuscia/assets/40063899/ab40db64-9c4b-4b07-b480-660cb3166253)
![image](https://github.com/secretflow/kuscia/assets/40063899/1c3e29b6-c064-43e2-93c3-1030defca7ea)
在执行bob 给 alice 签发 MTLS 证书：的命令时出错

**Comment by cho-chem** [comment]
Hi @liuhaichaogithub 麻烦确认下 crs 文件是否存在且格式是否正确
```
ls -l ${DOMAIN_CERTS_DIR}/${ALICE_DOMAIN_ID}.domain.csr

openssl req -text -in ${DOMAIN_CERTS_DIR}/${ALICE_DOMAIN_ID}.domain.csr -noout -verify
```
