### ISSUE TITLE
使用Kuscia多机部署点对点网络进行psi,是否支持上百G的csv文件,需要什么样的配置，谢谢

### ISSUE THREAD

**Issue by liuhaichaogithub** [secretflow/kuscia#69]
使用Kuscia多机部署点对点网络进行psi,是否支持上百G的csv文件,需要什么样的配置，谢谢，上百G的文件多字段组合求交集大概需要多久？有没有测试数据

**Comment by 6fj** [comment]
hi @liuhaichaogithub 

请参考https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/developer/benchmark/psi_benchmark，总的时间和你两边的id数量相关，可以简单按照线性增长预估一下。

感谢

**Comment by liuhaichaogithub** [comment]
对我们的机器配置有要求吗，比如多大的内存，一个节点是否够用，另外还有一个问题我们想要将不是交集的数据也在文件输出出来，有办法做到吗？需要修改哪部分的代码

**Comment by 6fj** [comment]
8c16g应该是可以了。

目前没有输出非交集数据这个功能，需要自行修改secretflow的代码，重新打包之后部署。

近期我们会给出修改secretflow组件的教程。

**Comment by liuhaichaogithub** [comment]
好的感谢
