### ISSUE TITLE
kuscia支持运行mpc方式建模任务吗

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/kuscia#79]
mpc方式的数据预处理、特征工程、模型训练和预测，kuscia是否有支持的接口

**Comment by yushiqie** [comment]
> mpc方式的数据预处理、特征工程、模型训练和预测，kuscia是否有支持的接口

目前这些kuscia都是以KusciaJob方式支持（详情见https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/tutorial/run_secretflow_cn#configure-kuscia-job），跟示例PSI KusciaJob不同的是，taskInputConfig需要配置成"mpc方式的数据预处理、特征工程、模型训练和预测"相对应的SecretFlow引擎组件配置（详见https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/component/comp_list#id14）

**Comment by daydayuphere** [comment]
怎么区分哪些组件是mpc建模用的，哪些是联邦学习建模用的呢
https://www.secretflow.org.cn/docs/secretflow/latest/zh-Hans/component/comp_list#id14）
