### ISSUE TITLE
kuscia多机部署手册

### ISSUE THREAD

**Issue by wsk95** [secretflow/kuscia#89]
你好，之前有多机部署的手册，现在找不到了，请问是在更新吗，什么时候可以提供

**Comment by daydayuphere** [comment]
我们在用kuscia，环境挂掉，重装，发现咱们多机p2p镜像和部署指导都不提供了，这能不能再提供下

**Comment by gshilei** [comment]
Hi @daydayuphere @wsk95， Kuscia文档在更新，等下会恢复。恢复好之后，我会在这里同步大家。

**Comment by gshilei** [comment]
Hi @wsk95 , @daydayuphere , Kuscia 文档已更新完成。若本地重新安装，建议重新拉一下Kuscia镜像，否则有些文档上的功能无法体验。 命令如下：
`docker pull secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia`
