### ISSUE TITLE
多节点部署

### ISSUE THREAD

**Issue by dtera** [secretflow/kuscia#90]
文档[多机部署点对点集群](https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/deploy/deploy_p2p_cn)
![image](https://github.com/secretflow/kuscia/assets/45172737/75a222c9-df77-4675-94c5-1035ce71e0ad)
上面显示的部署alice和bob节点，每一方只能一个节点吗（如果是，生产环境下基本是不可用的，也不叫集群了），怎么往每一方添加节点呢

**Comment by yushiqie** [comment]
> 

当前kuscia支持的是“节点的单实例部署”，“节点的多实例部署”在我们的规划中，敬请期待

**Comment by yushiqie** [comment]
我们暂定在10月初的版本支持 “节点多实例部署”。
