### ISSUE TITLE
MVP 平台相关问题

### ISSUE THREAD

**Issue by integrationex01** [secretflow/kuscia#93]
1、MVP平台部署时创建账户秘密遗忘如何修改？是否只能够重新部署。

2、MVP平台是否可以更改默认配置例如增加节点、导入数据，是否有类似配置文件的方式？

**Comment by UniqueMarvin** [comment]
你好
1 是的，目前账密遗忘无法修改，只能重新部署。
2 当前版本（截止0828）还不可以新增节点，预计0908发布的新版可以新增节点。新数据导入可参考官方文档：https://www.secretflow.org.cn/docs/quickstart/bxqxipfiahmm7rbh#k74Yv  【添加数据】 章节

**Comment by integrationex01** [comment]
> 你好 1 是的，目前账密遗忘无法修改，只能重新部署。 2 当前版本（截止0828）还不可以新增节点，预计0908发布的新版可以新增节点。新数据导入可参考官方文档：https://www.secretflow.org.cn/docs/quickstart/bxqxipfiahmm7rbh#k74Yv 【添加数据】 章节

你好、请问是否可以通过不操作前端页面的方式对流程进行部署

**Comment by Eiji911** [comment]
> > 你好 1 是的，目前账密遗忘无法修改，只能重新部署。 2 当前版本（截止0828）还不可以新增节点，预计0908发布的新版可以新增节点。新数据导入可参考官方文档：https://www.secretflow.org.cn/docs/quickstart/bxqxipfiahmm7rbh#k74Yv 【添加数据】 章节
> 
> 你好、请问是否可以通过不操作前端页面的方式对流程进行部署

不使用平台的话，也可以直接基于脚本进行部署。请参考https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/quickstart_cn

**Comment by integrationex01** [comment]
> > > 你好 1 是的，目前账密遗忘无法修改，只能重新部署。 2 当前版本（截止0828）还不可以新增节点，预计0908发布的新版可以新增节点。新数据导入可参考官方文档：https://www.secretflow.org.cn/docs/quickstart/bxqxipfiahmm7rbh#k74Yv 【添加数据】 章节
> > 
> > 
> > 你好、请问是否可以通过不操作前端页面的方式对流程进行部署
> 
> 不使用平台的话，也可以直接基于脚本进行部署。请参考https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/quickstart_cn

好的、感谢
