### ISSUE TITLE
kuscia资源控制问题

### ISSUE THREAD

**Issue by daydayuphere** [secretflow/kuscia#94]
kuscia api创建job，如何控制任务容器占用的资源，cpu，内存等
https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/apis/kusciajob_cn
这里没找到

**Comment by yushiqie** [comment]
> kuscia api创建job，如何控制任务容器占用的资源，cpu，内存等 https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/apis/kusciajob_cn 这里没找到
job中task会指定运行的应用镜像名app_image  https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/apis/kusciajob_cn#task， 其中task的资源限制是通过在app_image中设置 https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/reference/concepts/appimage_cn
![Screen Shot 2023-08-29 at 14 15 51](https://github.com/secretflow/kuscia/assets/21165026/b2a5cb08-ace4-4bae-99cd-cfc10a9ab0cd)

**Comment by daydayuphere** [comment]
不配置的话，默认是多少呢

**Comment by yushiqie** [comment]
> 
默认就是节点本身的资源限制，目前节点启动的时候不会限制资源，所以就是节点本身所在的主机限制

**Comment by daydayuphere** [comment]
好的 谢谢
