### ISSUE TITLE
AttributeError: 'SPURuntime' object has no attribute 'id'

### ISSUE THREAD

**Issue by wsk95** [secretflow/kuscia#96]
![image](https://github.com/secretflow/kuscia/assets/44944342/64cd1e92-bcf5-4930-a372-922a9f8f3d46)
部署方式是kusica多机部署，在alice节点运行示例任务，bob节点会报这个错误导致任务失败。

**Comment by longshan-ant** [comment]
你是用的示例的 create_example_job.sh 提交的任务，还是提交的自己定义的Job？

**Comment by wsk95** [comment]
示例create_example_job.sh

**Comment by 6fj** [comment]
错误是因为网络原因造成的，前面出现了connect to mesh failed.

**Comment by wsk95** [comment]
https://github.com/secretflow/kuscia/issues/65
根据这个方式部署的

**Comment by longshan-ant** [comment]
> #65 根据这个方式部署的

可以再参考一下这个文档，是不是最后授权没有建立（2个方向都需要授权）
https://www.secretflow.org.cn/docs/kuscia/latest/zh-Hans/getting_started/deploy/deploy_p2p_cn#bob-alice

**Comment by wsk95** [comment]
已解决，感谢
